### PR TITLE
Remove hard coded product version

### LINKED ISSUE #650: Server installer wizard version message seems incorrect
After installing mSupply server, last page of wizard:

image

I believe this should say `v1.0.0`. Perhaps the string in the wizard isn't coming from a common source? Perhaps based on git tags but got the wrong one?

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #650
Just an update to the suf file to use the product version

### CODE REVIEW

File: client/packages/host/src/components/Login/LoginIcon.tsx [hunk 1]
```diff
@@ -11,8 +11,8 @@ export const LoginIcon = ({ small = false }: { small?: boolean }) => {
   const [customLogo] = useLocalStorage('/theme/logo');
   const isSmallScreen = useIsSmallScreen() || small;
   const logoStyle = isSmallScreen
-    ? { width: 61, height: 90 }
-    : { width: 122, height: 180 };
+    ? { width: 155, height: 90 }
```
Comment (mark-prins) [inline client/packages/host/src/components/Login/LoginIcon.tsx:14]: and an offroad.. to allow the PNG custom theme to have a logo that isn't squashed up. The normal logo looks fine, as well as the PNG.

**Comment by mark-prins** [comment]
and this is me testing all of the custom logos. I was using the PNG theme, so the drawer background is black.. but you get the idea

logos

**Review by andreievg — APPROVED** [review]
Looks great 🙏
