### PR TITLE
2204 Fix encounter list sorting issue

### LINKED ISSUE #2204: Sorting doesn't work well in Encounters list window
## What went wrong? 😲
Sorting doesn't work well in Encounters list window

## Expected behaviour 🤔
List should be able to be sorted in both ascending and descending order.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Go to Dispensary>Encounters
image

2. Try to sort the encounters list
3. You'll see the list sorted in ascending order
4. Sort again by clicking on the same field
5. See error: the list doesn't get sorted in descending order this time.

## Your environment 🌱

 - Version: v1.3.00
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #2204 

# 👩🏻‍💻 What does this PR do? 
 
Fix encounter list sorting issue

# 🧪 How has/should this change been tested? 

1. Go to Dispensary>Encounters
2. Try to sort the encounters list

### CODE REVIEW

File: client/packages/system/src/Encounter/ListView/ListView.tsx [hunk 1]
```diff
@@ -18,22 +19,24 @@ import { EncounterFragment, useEncounter } from '@openmsupply-client/programs';
 
 const EncounterListComponent: FC = () => {
   const {
-    updateSortQuery,
     updatePaginationQuery,
-    queryParams: { sortBy, page, first, offset },
+    queryParams: { page, first, offset },
```
Comment (mark-prins) [inline client/packages/system/src/Encounter/ListView/ListView.tsx:23]: can you revert these changes please. We want to use the URL query for the sort params!
I've found the bug in the URL query params - there's actually a wider problem.. where all table sort change of direction is failing!

**Review by mark-prins — CHANGES_REQUESTED** [review]
Thanks @raviSussol for picking this one up 😃 
While reviewing, I've found that there's a site wide sorting bug!
I've made a suggestion in [this branch](https://github.com/openmsupply/open-msupply/compare/2204-fix-encouter-list-sorting-issue...2204-fix-encounter-list-sort-suggestion)

can you have a look and see if it's ok for you? Basically this is reverting a change made to the `useUrlQueryParams` hook, and then changing the encounter list view back to using the url query for the sorting (which I prefer, it means that we can bookmark the page and have the sort working)

File: client/packages/system/src/Encounter/ListView/ListView.tsx [hunk 2]
```diff
@@ -58,15 +57,7 @@ const EncounterListComponent: FC = () => {
...
 export const EncounterListView: FC = () => (
-  <TableProvider
-    createStore={createTableStore}
-    queryParamsStore={createQueryParamsStore<EncounterFragment>({
-      initialSortBy: {
-        key: EncounterSortFieldInput.StartDatetime,
-        isDesc: true,
-      },
-    })}
-  >
```
Comment (raviSussol) [inline client/packages/system/src/Encounter/ListView/ListView.tsx:69]: Removing it since the `EncounterListComponent` is no longer consuming query param store resource(s) now.

File: client/packages/system/src/Patient/Encounter/ListView.tsx [hunk 3]
```diff
@@ -70,15 +63,7 @@ const EncounterListComponent: FC = () => {
...
 export const EncounterListView: FC = () => (
-  <TableProvider
-    createStore={createTableStore}
-    queryParamsStore={createQueryParamsStore<EncounterFragmentWithStatus>({
-      initialSortBy: {
-        key: EncounterSortFieldInput.StartDatetime,
-        isDesc: true,
-      },
-    })}
-  >
```
Comment (raviSussol) [inline client/packages/system/src/Patient/Encounter/ListView.tsx:81]: Same as above.

File: client/packages/system/src/Encounter/ListView/ListView.tsx (hunk 1 above)
Comment (raviSussol) [reply client/packages/system/src/Encounter/ListView/ListView.tsx]: Right. Good to fix the original cause at first place. 3a6e872be

File: client/packages/system/src/Encounter/ListView/columns.ts [hunk 4]
```diff
@@ -66,9 +66,8 @@ export const useEncounterListColumns = ({
 
   const columnList: ColumnDescription<EncounterRowFragment>[] = [
     {
-      key: 'encounter-type',
+      key: 'type',
```
Comment (clemens-msupply) [inline client/packages/system/src/Encounter/ListView/columns.ts:69]: Any reason why changing it? with 'encounter-type' you might avoid potential name clashes if using a more specific key...

File: client/packages/system/src/Patient/Encounter/ListView.tsx (hunk 3 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: The problem here is that if you select a sort option and change tabs back end forth to the encounter list you would expect that the sort/filter options are remembered. With these changes they are reverted to the default though. This was the reason why there were store and the url query params...

I think what we want is a way to store the filter/sort params in the url AND in the store and when you revisit a tab the url params are initialized from the store params. I would suggest creating a new hook for this...
@mark-prins what do you think?

File: client/packages/system/src/Encounter/ListView/ListView.tsx (hunk 2 above)
Comment (clemens-msupply) [reply client/packages/system/src/Encounter/ListView/ListView.tsx:69]: Thanks this wasn't needed here (see other comment)

File: client/packages/system/src/Encounter/ListView/columns.ts (hunk 4 above)
Comment (raviSussol) [reply client/packages/system/src/Encounter/ListView/columns.ts:69]: `Type` column wasn't sorting cause of invalid `key` value i.e. `encounter-type`. It was expecting the data element key value here. `EncounterRowFragment[]`

File: client/packages/system/src/Patient/Encounter/ListView.tsx (hunk 3 above)
Comment (mark-prins) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: Yeah, that could work. I'd be a little concerned about how difficult that could be, and we'd need to write out requirements and test cases; we've spent so much time fixing the URL query params already.. it's a complex area.

Comment (clemens-msupply) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: Yes, happy to move it to another issue.

@richardmoizeau how much do we want to remember encounter filter/sort options when switching between tabs in the patient view?

Comment (richardmoizeau) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: I don't there is any filter for the patient view right ? I think that's OK not to save the sort order (would definitely be nice though).

Comment (raviSussol) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: I tried to look at the `useQueryParamsStore` hook thinking that it supposed to work or persist the last sorted key and its direction (of which it is being made for) at first place. But the problem I can see is the `useQueryParamsStore` is being used with state initialized as a props from the `TableProvider`. The patient encounter `EncounterListView` component gets remounted every time the tab gets changed resulting the reset of all states of `useQueryParamsStore` to its initialized props value. If we separate the `useQueryParamsStore` usage from `TableProvider` to external store then no sorting would work at all cause the `useTableStore` hook is being used to handle all datatable action and is the consumer of `TableProvider` so need to be subscribed under `TableProvider` component to function all table actions. The only option I can see working is to make `useQueryParamsStore` persistence using `localStorage`. But this would give another complication to handle mount/unmount of `EncounterListView` component to reset sorting to its default state.

So I'm also inclining towards not to implement this sort persistence in the datatable (unless user specifically asks for).

Comment (mark-prins) [reply client/packages/system/src/Patient/Encounter/ListView.tsx:81]: agree - that's getting too complex for this issue. Something to consider another time perhaps.

**Review by mark-prins — APPROVED** [review]
🎉  thanks @raviSussol!
