### PR TITLE
2046 Patient created in oms are not syncing well to mSupply Desktop

### LINKED ISSUE #2046: Patient created in oms are not syncing well to mSupply Desktop
## What went wrong? 😲
Patient created in oms are not syncing well to mSupply Desktop dispensary despite the store pref `Patients created in other stores not visible in this store` OFF

## Expected behaviour 🤔
With that `Patients created in other stores not visible in this store` store pref OFF, all created patients should sync well to the cloud?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a sync setup with multiple remote sites: both oms and mSupply desktops
2. Create a patient1 from oms first and sync
3. Login to Desktop and see error: patient1 is not showing despite that store pref
4. Also try checking that pref ON/OFF (for desktop store) as [in the recording](https://recordit.co/hTYPju5l8h)
5. SYnc well
6. See error: you'll now notice the patient1's homestore is changed to that Desktop store.

## Screenshots
https://recordit.co/hTYPju5l8h

## Your environment 🌱

 - Version: v1.1.12 server, apk
 - Platform:
   - [x] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [x] server (windows)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2046

# 👩🏻‍💻 What does this PR do? 
Saves supplying store for patients when created on omSupply so that it shows/hides the patients if the `Patients created in other stores not visible in this store` pref is ON/OFF

# 🧪 How has/should this change been tested? 
Make sure both stores are `dispensaries`
- [ ] Create a patient in om in Store A(need to run programs 4dInit script to create patients)
- [ ] Log in to Store B in central and turn ON `Patients created in other stores not visible in this store` pref
- [ ] Newly created patient should not show up in the patient list of Store B
- [ ] Turn `Patients created in other stores not visible in this store` OFF
- [ ] Should see newly created patient

### CODE REVIEW

File: server/service/src/programs/patient/patient_updated.rs [hunk 1]
```diff
@@ -38,6 +38,7 @@ pub fn create_patient_name_store_join(
 /// Updates the names table for the updated patient.
 pub fn update_patient_row(
     con: &StorageConnection,
+    store_id: Option<String>,
```
Comment (roxy-dao) [inline server/service/src/programs/patient/patient_updated.rs:41]: Made it optional since this function is used in `sync_upsert_document` as well...

File: server/service/src/programs/patient/patient_updated.rs [hunk 2]
```diff
@@ -82,9 +83,11 @@ pub fn update_patient_row(
         r#type: NameType::Patient,
         is_customer: existing_name.map(|n| n.is_customer).unwrap_or(true),
         is_supplier: existing_name.map(|n| n.is_supplier).unwrap_or(false),
-        supplying_store_id: existing_name.and_then(|n| n.supplying_store_id.clone()),
-        first_name: first_name,
-        last_name: last_name,
+        supplying_store_id: existing_name
```
Comment (andreievg) [inline server/service/src/programs/patient/patient_updated.rs:86]: Can you add a comment please: // supplying_store_id is the home store for patient, needed for compatibility with mSupply

**Review by andreievg — APPROVED** [review]
Look good thanks, just one request for comment please. I haven't tested though
