### PR TITLE
358 fix bug with reduction of total number of packs in outbound shipment status change

### LINKED ISSUE #358: Double reduction of total number of packs via outbound shipment status change
@mark-prins identified data discrepancy he noticed, where total_number_of_packs was below available_number_of_packs on stock_line, this is potential due to double reduction when status is changed from shipped to picked in outbound shipment.

### PR DESCRIPTION
**Pull request by andreievg**
closes #358 

I really like test driven dev for things like this, i've added the test first, it failed, then fixed test.

I've also added stock line to invoice line repository query, there was actually an issue to do that in remote server repo, and it makes the logic in update/generate of osline a bit nicer. Also renamed some things

### CODE REVIEW

File: server/service/src/invoice/outbound_shipment/update/generate.rs [hunk 1]
```diff
@@ -77,7 +81,7 @@ fn should_update_batches(
         let new_invoice_status_index = new_invoice_status.index();
 
         new_invoice_status_index >= InvoiceRowStatus::Picked.index()
-            && invoice_status_index < new_invoice_status_index
+            && invoice_status_index < InvoiceRowStatus::Picked.index()
```
Comment (andreievg) [inline server/service/src/invoice/outbound_shipment/update/generate.rs:84]: actual fix. 
btw this method was refactored a few times, wanted to check if it was the refactor that cause the problem, it did seem like it was the refactor that cause the issue, but the refactor was done because more statuses was added, it looked like this at the start:
```
pub fn should_update_batches(invoice: &InvoiceRow, patch: &UpdateOutboundShipment) -> bool {
    match (&invoice.status, &patch.status) {
        (InvoiceRowStatus::Draft, Some(InvoiceStatus::Confirmed)) => true,
        (InvoiceRowStatus::Draft, Some(InvoiceStatus::Finalised)) => true,
        _ => false,
    }
}
```

Might have been safer to use above type of check of status, it would mean two extra match clauses. But I think the safest would have been to add more thorough test cases for this sort of side effect (i.e. write test not just to validate that it works, but to make sure it's not broken in the future)

Comment (mark-prins) [inline server/service/src/invoice/outbound_shipment/update/generate.rs:84]: This is a case where I find the verbose version easier to read - this is pretty clear what the behaviour is, and is fewer lines of code

```
fn should_update_batches_total_number_of_packs(
    invoice: &InvoiceRow,
    status: &Option<UpdateOutboundShipmentStatus>,
) -> bool {
    match (&invoice.status, status) {
        (InvoiceRowStatus::New, Some(UpdateOutboundShipmentStatus::Picked)) => true,
        (InvoiceRowStatus::New, Some(UpdateOutboundShipmentStatus::Shipped)) => true,
        (InvoiceRowStatus::Allocated, Some(UpdateOutboundShipmentStatus::Picked)) => true,
        (InvoiceRowStatus::Allocated, Some(UpdateOutboundShipmentStatus::Shipped)) => true,
        _ => false,
    }
}
```

**Review by mark-prins — APPROVED** [review]
👍 LGTM! thanks - I have a formatting opinion, but the code functions as expected, so we're good to go 😁 

One gripe is the lack of a test procedure in the PR or issue - I had to guess how to replicate the issue. Fortunately having unit tests helps with that.

**Comment by andreievg** [comment]
> One gripe is the lack of a test procedure in the PR or issue -

Yes, I shouldn't be expecting reviewers to look at unit test and decipher the test condition, should have made it very clear in the issue, will improve on that front

File: server/service/src/invoice/outbound_shipment/update/generate.rs (hunk 1 above)
Comment (andreievg) [reply server/service/src/invoice/outbound_shipment/update/generate.rs:84]: @clemens-msupply has a similar comment, I thought it was ok, but can see it looks better with match:

I took a little break from reviewing and made a branch to see how it look for all of the places where invoice status index is used (I think it's a little bit too much for main branch, will PR to develop when this is merged and when main is merged into develop) [i think it does look better](https://github.com/openmsupply/open-msupply/compare/358-Fix-bug-with-reduction-of-total-number-of-packs-in-outbound-shipment-status-change...Change-status-check-to-use-match)

**Comment by mark-prins** [comment]
thanks - merge away. I've done the other changes to develop, so I'll try a merge from dev after you've merged this one in.

Dev is safe to merge, all the new work has been done on the feature branch, and only release-ready fixes are in develop atm
