### PR TITLE
469 fix query params

### LINKED ISSUE #469: Remember sort, filter options when changing tabs
Currently, sort options are shared between all tabs. In the worst case the sort option is not applicable in another tab and an error message is shown.

### PR DESCRIPTION
**Pull request by clemens-msupply**
Closes #469 

The query params are reset after leaving the list view but at least it is not crashing other list views...

@mark-prins might be good to merge useQueryParamsStore and useUrlQueryParams in the future and have a single configurable query params provider that takes the params either from the url or from the store. Had to change the provider the components and some hooks, while ideally only the provider would need to be updated...

### CODE REVIEW

File: client/packages/system/src/Patient/ListView/ListView.tsx [hunk 1]
```diff
@@ -11,8 +11,8 @@ import {
   ColumnAlign,
   useAlertModal,
   useTranslation,
-  useUrlQueryParams,
   ReadOnlyCheckboxCell,
+  useQueryParamsStore,
```
Comment (mark-prins) [inline client/packages/system/src/Patient/ListView/ListView.tsx:15]: I also don't think that this page should be changed. It makes the list view different from all others in the site and removes the ability to bookmark the list view sort options

File: client/packages/system/src/Patient/api/hooks/document/useProgramEnrolments.ts [hunk 2]
```diff
@@ -1,20 +1,28 @@
...
+  const params: ProgramEnrolmentListParams = {
+    sortBy: {
+      key: sortBy?.key ?? ProgramEnrolmentSortFieldInput.EnrolmentDatetime,
+      isDesc: sortBy?.isDesc,
+    },
     filterBy: { patientId: { equalTo: patientId } },
   };
   return {
-    ...useQuery(api.keys.paramList(params), () =>
+    ...useQuery(api.keys.enrolmentParmList(params), () =>
```
Comment (mark-prins) [inline client/packages/system/src/Patient/api/hooks/document/useProgramEnrolments.ts:25]:
```suggestion
    ...useQuery(api.keys.enrolmentParamList(params), () =>
```

File: client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts [hunk 3]
```diff
@@ -10,6 +14,8 @@ export const usePatientApi = () => {
     history: (id: string) => [...keys.base(), 'history', storeId, id] as const,
     list: () => [...keys.base(), storeId, 'list'] as const,
     paramList: (params: ListParams) => [...keys.list(), params] as const,
+    enrolmentParmList: (params: ProgramEnrolmentListParams) =>
```
Comment (mark-prins) [inline client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts:17]:
```suggestion
    enrolmentParamList: (params: ProgramEnrolmentListParams) =>
```

**Review by mark-prins — APPROVED** [review]
🎉  Cool - thanks! that's better.

I'd prefer keeping the URL params for the top level list views ( patient and encounter ) as these don't require changing - and changing them makes them inconsistent, and removes functionality

File: client/packages/system/src/Patient/ListView/ListView.tsx (hunk 1 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/ListView/ListView.tsx]: thanks!, yes I was a bit eager I used the url parameter again for the patient end encounter list view.

How the API hooks are used here is a bit confusing too me. For example, the "list encounter" hook was reused from the "main" encounter list view which uses a different hook to obtain the query params, I needed a while to track this down and fix it. Maybe something to discuss at a later point.

File: client/packages/system/src/Encounter/ListView/ListView.tsx [hunk 4]
```diff
@@ -25,10 +25,9 @@ const encounterEventCellValue = (events: ProgramEventFragment[]) => {
 
 const EncounterListComponent: FC = () => {
   const {
-    updateSortQuery,
-    updatePaginationQuery,
-    queryParams: { sortBy, page, first, offset },
-  } = useUrlQueryParams();
+    sort: { sortBy, onChangeSortBy },
```
[the remark this answers is not in the document]
Comment (clemens-msupply) [reply client/packages/system/src/Encounter/ListView/ListView.tsx]: Done (see other comment)
