### PR TITLE
#995 #1578 Name indexes and programs migrations fixes

### LINKED ISSUE #995: Add name DB indexes
To lookup patient we need indexes on the `name` table.

- [x] identify column needing an index, e.g. `first name`, `last name`, `code`, `code2`

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #995 #1578

# 👩🏻‍💻 What does this PR do? 
 

Have done what's required (I think), but putting it in Draft for now as it's giving errors. See inline comments for some explanations and problems. @clemens-msupply I'll have a look at the remaining issues with you on Monday if that's okay?

# 🧪 How has/should this change been tested?

### CODE REVIEW

File: server/repository/migrations/postgres/2023-04-21_T10-00_changes_made_in_develop/down.sql [hunk 1]
```diff
@@ -0,0 +1,81 @@
+-- This file should undo anything in `up.sql`
+
+-- 2021-08-15T10-00_create_name_table
+CREATE TYPE gender_type_original AS ENUM (
```
Comment (CarlosNZ) [inline server/repository/migrations/postgres/2023-04-21_T10-00_changes_made_in_develop/down.sql:4]: There's no convenient way to remove values from an existing Enum. Hence this whole routine 🙄

File: server/repository/migrations/sqlite/2023-04-21_T10-00_changes_made_in_develop/up.sql [hunk 2]
```diff
@@ -0,0 +1,65 @@
+-- These changes were originally inserted into an earlier migration on develop,
+-- which means they won't run when updating to a "programs" branch if the
+-- earlier migrations had already run.
+
+-- 2021-08-15T10-00_create_name_table
+CREATE TABLE name_new (
```
Comment (CarlosNZ) [inline server/repository/migrations/sqlite/2023-04-21_T10-00_changes_made_in_develop/up.sql:6]: So the reason for this recreation of the table is that you can't modify a "CHECK" constraint in SQLite. All the guides I found online said you need to create new table, move the data into it, then rename.

However, this is a little unsafe as it relies on this version of the table schema being identical to its current state, and this doesn't guarantee that. As it is, I had to add one column (is_sync_update) that had been added subsequent to the original creation. And it's still giving errors on the "type" constraint which I don't understand.

File: server/repository/migrations/sqlite/2023-04-21_T10-00_changes_made_in_develop/up.sql [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+);
+
+INSERT INTO name_new SELECT * FROM name;
+DROP name;
+ALTER TABLE name_new RENAME to name;
+
+-- 2022-03-15T10-00_report_table
+
+
+-- 2022-03-25T14-30_create_user_permission_table
```
Comment (CarlosNZ) [inline server/repository/migrations/sqlite/2023-04-21_T10-00_changes_made_in_develop/up.sql:64]: Nothing required for these two, even though there was for the postgres one. @clemens-msupply, you'd just added new enum values, but in SQLite you'd made the field "TEXT" with no constraint, so no constraint modifications required.

**Review by clemens-msupply — COMMENTED** [review]
Have some annoying requests:
- Some migration dirs have an extra _, e.g. `2023-04-21_T10-00` (its actually kind of important because this would sort differently than without underscore, if there is another migration on the same day)
- Could you please rename the migration dirs to reflect what the migration does? e.g. `name_table_add_national_health_number_column` or similar?

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+        'TRANSGENDER',
+        'TRANSGENDER_MALE',
+        'TRANSGENDER_MALE_HORMONE',
+        'TRANSGENDER_MALE_SURGICAL',
+        'TRANSGENDER_FEMALE',
+        'TRANSGENDER_FEMALE_HORMONE',
+        'TRANSGENDER_FEMALE_SURGICAL',
+        'UNKNOWN',
+        'NON_BINARY'
+    )),
```
Comment (clemens-msupply) [inline server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:38]: Since its difficult to modify enums in Sqlite we started to only document/enforce enum constraints in Postgres. Using a strongly typed language should prevent DB inconsistency, at least if you are not running your code on the wrong DB migration version...

Could you please remove the check here (for gender and type) so that the column is just a TEXT?

@andreievg do you want to have a look as well?

Comment (CarlosNZ) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:38]: Shall I remove the constraint for the type as well ("FACILITY", "PATIENT", etc)?

Comment (clemens-msupply) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:38]: yes please

**Comment by CarlosNZ** [comment]
Okay, @clemens-msupply this seems to be all working now. Have tested with deleting databases, with both Postgres and SQLite. 

Ran "down" scripts manually after initialisation and seem to do what they're supposed do.

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql [hunk 5]
```diff
@@ -0,0 +1,23 @@
+-- These changes were originally inserted into an earlier migration on develop,
+-- which means they won't run when updating to a "programs" branch if the
+-- earlier migrations had already run.
+
+-- 2021-08-15T10-00_create_name_table
+ALTER TABLE name ADD COLUMN type_new TEXT NOT NULL DEFAULT "FACILITY";
```
Comment (clemens-msupply) [inline server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:6]: Now, the column has a default constraint that it doesn't have in develop. Since it's more tricky than expected, I would suggest to just leave `type` as it is (since it's not really required right now and was just an additional clean-up...). Otherwise, I don't see another way than recreating the whole table...

Comment (CarlosNZ) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:6]: It's only because it already has a `NOT NULL` constraint, so something has to be set for a DEFAULT value. However, this default gets immediately overwritten by the current `type` value in the next line:
```
UPDATE name SET type_new =  type;
```

But you can't create a column with NOT NULL without a default if there are existing records, and you can't change constraints after they're created (in SQLite).

Is there a problem leaving it with a default value? One should always be specified when adding records, anyway.

Duplicating the table and transferring the data comes with its own headaches and seems riskier to me.

Comment (clemens-msupply) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:6]: Yes, for this reason I would leave the type column as it is. Not sure how likely it is that we ever add another type variant to the name table... I would defer this problem to the point when we really need it and keep the column with the correct constraint till then.

Comment (CarlosNZ) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql]: Okay have reverted the type change, it's now as it was (with no change to constraint): 0dcae214f

**Review by clemens-msupply — CHANGES_REQUESTED** [review]
Just noticed there is another change in the `server/repository/migrations/sqlite/2022-03-15T10-00_report_table/up.sql` that hasn't been update in this PR (PATIENT, DISPENSARY was added)...

**Comment by CarlosNZ** [comment]
> Just noticed there is another change in the `server/repository/migrations/sqlite/2022-03-15T10-00_report_table/up.sql` that hasn't been update in this PR (PATIENT, DISPENSARY was added)...

Oh, right, yeah. Done now: 925e9c444

(Removing the enum constraint as per the others, but putting it back in the `down` script)

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/down.sql [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+        'REQUISITION',
+        'STOCKTAKE',
+        'RESOURCE'
+    )) NOT NULL,
+    comment TEXT,
+    sub_context TEXT,
+    argument_schema_id TEXT REFERENCES form_schema(id)
+);
+
+INSERT INTO report_original SELECT id, name, type, template, context, comment, sub_context, argument_schema_id FROM report;
```
Comment (CarlosNZ) [inline server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/down.sql:27]: For some reason this doesn't work with `INSERT INTO report_original SELECT * FROM report;` but it does with every column explicitly specified. 🤷‍♂️

Comment (clemens-msupply) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/down.sql:27]: Aren't the old field missing in the context enum? Not sure if this is the reason though...

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+
+ALTER TABLE name ADD COLUMN is_deceased BOOLEAN;
+ALTER TABLE name ADD COLUMN national_health_number TEXT;
+
+-- 2022-03-15T10-00_report_table
+CREATE TABLE report_new
+(
+    id TEXT NOT NULL PRIMARY KEY,
+    name TEXT NOT NULL,
+    type TEXT CHECK (type IN ('OM_SUPPLY')) NOT NULL,
```
Comment (clemens-msupply) [inline server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql:19]: The new fields are missing ('PATIENT' and  'DISPENSARY')... Or better just remove the check.

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/down.sql (hunk 6 above)
Comment (CarlosNZ) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/down.sql:27]: No, that's not the reason, as the complaint is for any of the fields with "NOT_NULL" constraints, regardless of any additional constraints.

File: server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql (hunk 7 above)
Comment (CarlosNZ) [reply server/repository/migrations/sqlite/2023-04-21T10-00_name_table_add_columns_update_types/up.sql]: Cool 90030202f

**Review by clemens-msupply — APPROVED** [review]
Looks good! I haven't fully tested it yet because I am working on some other migration issues from a `develop` merge, will do a test then...
