### PR TITLE
1701 Pending approval response requisition appears as editable in list

### LINKED ISSUE #1701: Pending approval response requisition appears as editable in list
## What went wrong? 😲

Pending approval response requisition appears as editable in list

## Expected behaviour 🤔

Appears as not editable

## How to Reproduce 🔨

Can use (short) version of data file and instructions to create pending response requisition, and see it editable in the list (it's not editable in detail view, which is correct)
Screenshot 2023-05-05 at 5 42 01 PM

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1701

# 👩🏻‍💻 What does this PR do? 
Grey out requisitions that are pending or denied in Requisition View

# 🧪 How has/should this change been tested? 
- Have a pending or denied requisition
- Click on Requisition in sub-menu
- See that requisitions which are pending or denied is greyed out

### CODE REVIEW

File: client/packages/requisitions/src/utils.ts [hunk 1]
```diff
@@ -67,7 +67,11 @@ export const isRequestDisabled = (request: RequestRowFragment): boolean => {
 };
 
 export const isResponseDisabled = (request: RequestRowFragment): boolean => {
-  return request.status !== RequisitionNodeStatus.New;
+  return (
```
Comment (mark-prins) [inline client/packages/requisitions/src/utils.ts:70]: I was confused by the use of Request in this function. Would you mind fixing a previous copy paste error?
```
export const isResponseDisabled = (response: ResponseRowFragment): boolean => {
  return (
    response.status !== RequisitionNodeStatus.New ||
    response.approvalStatus === RequisitionNodeApprovalStatus.Pending ||
    response.approvalStatus === RequisitionNodeApprovalStatus.Denied
  );
};
```

**Review by mark-prins — APPROVED** [review]
👍  works nicely thanks.
I have a side request to fix up the variable naming.. not a blocker tho

**Review by mark-prins — APPROVED** [review]
👍  works nicely thanks.
I have a side request to fix up the variable naming.. not a blocker tho
