### PR TITLE
1588 stocktake add all item with stock at once

### LINKED ISSUE #1588: Stocktake: add all item with stock at once
## What went wrong? 😲

you have a way to add all items (with stock > 0 ?) to your stocktake from the `New Stocktake` modal

## Expected behaviour 🤔

you should be able to do that - current workaround would be to manually add each item individually which could be a very long process

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1588 

# 👩🏻‍💻 What does this PR do? 
Allows the user to create a master list with items that have stock

# 🧪 How has/should this change been tested? 
Try to create a master list with items that have stock

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

File: client/packages/system/src/Stock/api/hooks/line/useSortedStockLines.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import {
+  SortBy,
+  StockLineNode,
+  useQuery,
+  useUrlQueryParams,
+} from 'packages/common/src';
+import { useStockApi } from '../utils/useStockApi';
+
+export const useSortedStockLines = (sortBy: SortBy<StockLineNode>) => {
```
Comment (roxy-dao) [inline client/packages/system/src/Stock/api/hooks/line/useSortedStockLines.ts:9]: Couldn't use useStockLines without messing the column sorting....

**Review by mark-prins — CHANGES_REQUESTED** [review]
😁  that's working nicely thanks!

I have a suggestion, which I've put into a [new branch](https://github.com/openmsupply/open-msupply/compare/1588-stocktake-layout-suggestion) 

two small things
- update the intro message to say that you can select items in stock. I spent a little while trying to choose a masterlist AND check the checkbox. If we at least tell people not to do it, that might help?
- the alignment of the label and inputs isn't quite right, so I've tweaked that..

before:
Screenshot 2023-04-24 at 12 20 51 PM

after:
Screenshot 2023-04-24 at 12 20 20 PM

**Review by mark-prins — APPROVED** [review]
👍 LGTM!
