### PR TITLE
#1368 Leading 0 in filter fix

### LINKED ISSUE #1368: When filtering an item in internal order, the leading 0 are removed.
## What went wrong? 😲
 
When trying to filter items showing in the internal order, the leading 0 are removed automatically from your filter. It is not a big thing but would be useful for refining search

https://drive.google.com/file/d/1ajrp7CuBo0QcjK8qEADGuP9pxsTOOQ9F/view?usp=share_link

## Expected behaviour 🤔
I think we should keep the leading 0 to refine search. Also when adding an item to an internal order the leading 0 is kept when filtering.

It is keeping leading 0 when filtering to add an item.
https://drive.google.com/file/d/1zHd-o75-coD2m03enjmicKfkHcA2BUFU/view?usp=sharing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order
2. Click on 'add from master_list'
3. Go the filter field and type 06
4. See error. The 0 is removed from the filter and you see only '6'.

## Your environment 🌱
 - Version [e.g. 1.1.5]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #1368

# 👩🏻‍💻 What does this PR do? 
 

Fixes the leading 0 problem as described in [the issue](#1368). 

Also -- since @alainsussol was attempting to filter by digits, it would suggest he was trying to search for a code, so I've expanded the filter to match **code** as well as item **name**. This also makes it consistent with the item filter on the Catagloue -> Items page.

# 🧪 How has/should this change been tested? 

Create a new Internal Order as per issue steps. You should be able to filter added items by name or code, and starting the filter string with a `0` shouldn't make any difference.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts [hunk 1]
```diff
@@ -1,18 +1,27 @@
...
+  useUrlQuery,
+  ItemNode,
+} from '@openmsupply-client/common';
 import { useRequestColumns } from '../../../DetailView/columns';
 import { useHideOverStocked } from '../index';
 import { useRequestFields } from '../document/useRequestFields';
 
 const useItemFilter = () => {
-  const { urlQuery, updateQuery } = useUrlQuery();
+  const { urlQuery, updateQuery } = useUrlQuery({ skipParse: ['codeOrName'] });
```
Comment (CarlosNZ) [inline client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts:13]: This is the fix for the actual reported issue.

**Review by mark-prins — APPROVED** [review]
👍  LGTM!
