### PR TITLE
Fix desktop build

### LINKED ISSUE #2027: Desktop: build failure
## What went wrong? 😲
 
```
[FAILED] Compilation errors in the main process: assets by status 473 KiB [cached] 4 assets
[FAILED] orphan modules 9.77 MiB [orphan] 3321 modules
[FAILED] runtime modules 2.53 KiB 9 modules
[FAILED] built modules 748 KiB [built]
[FAILED]   modules by path ../../node_modules/ 715 KiB
[FAILED]     javascript modules 712 KiB 181 modules
[FAILED]     json modules 3.07 KiB
[FAILED]       ../../node_modules/ajv/dist/refs/json-schema-draft-07.json 2.72 KiB [built] [code generated]
[FAILED]       ../../node_modules/ajv/dist/refs/data.json 360 bytes [built] [code generated]
[FAILED]   modules by path ./ 32.4 KiB
[FAILED]     ./src/electron.ts + 7 modules 22.4 KiB [not cacheable] [built] [code generated]
[FAILED]     ./node_modules/ip/lib/ip.js 9.97 KiB [built] [code generated]
[FAILED]   + 13 modules
[FAILED]
[FAILED] WARNING in ../common/src/index.ts 4:0-161
[FAILED] export 'Location' (reexported as 'Location') was not found in 'react-router-dom' (possible exports: AbortedDeferredError, Await, BrowserRouter, Form, HashRouter, Link, MemoryRouter, NavLink, Navigate, NavigationType, Outlet, Route, Router, RouterProvider, Routes, ScrollRestoration, UNSAFE_DataRouterContext, UNSAFE_DataRouterStateContext, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, UNSAFE_useRouteId, UNSAFE_useScrollRestoration, createBrowserRouter, createHashRouter, createMemoryRouter, createPath, createRoutesFromChildren, createRoutesFromElements, createSearchParams, defer, generatePath, isRouteErrorResponse, json, matchPath, matchRoutes, parsePath, redirect, renderMatches, resolvePath, unstable_HistoryRouter, unstable_useBlocker, unstable_usePrompt, useActionData, useAsyncError, useAsyncValue, useBeforeUnload, useFetcher, useFetchers, useFormAction, useHref, useInRouterContext, useLinkClickHandler, useLoaderData, useLocation, useMatch, useMatches, useNavigate, useNavigation, useNavigationType, useOutlet, useOutletContext, useParams, useResolvedPath, useRevalidator, useRouteError, useRouteLoaderData, useRoutes, useSearchParams, useSubmit)
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/intl/index.ts 1:0-38
[FAILED] export 'LocaleKey' (reexported as 'LocaleKey') was not found in './locales' (module has no exports)
[FAILED]  @ ../common/src/index.ts 8:0-23 8:0-23
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/intl/strings/IntlStrings.ts 3:0-55
[FAILED] export 'UseTranslationResponse' (reexported as 'UseTranslationResponse') was not found in 'react-i18next' (possible exports: I18nContext, I18nextProvider, Trans, TransWithoutContext, Translation, composeInitialProps, date, getDefaults, getI18n, getInitialProps, initReactI18next, number, plural, select, selectOrdinal, setDefaults, setI18n, time, useSSR, useTranslation, withSSR, withTranslation)
[FAILED]  @ ../common/src/intl/strings/index.ts 1:0-30 1:0-30
[FAILED]  @ ../common/src/intl/index.ts 4:0-26 4:0-26
[FAILED]  @ ../common/src/index.ts 8:0-23 8:0-23
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/styles/index.ts 9:0-124
[FAILED] export 'Theme' (reexported as 'Theme') was not found in '@mui/material/styles' (possible exports: Experimental_CssVarsProvider, StyledEngineProvider, THEME_ID, ThemeProvider, adaptV4Theme, alpha, createMuiTheme, createStyles, createTheme, css, darken, decomposeColor, duration, easing, emphasize, experimentalStyled, experimental_extendTheme, experimental_sx, getContrastRatio, getInitColorSchemeScript, getLuminance, getOverlayAlpha, hexToRgb, hslToRgb, keyframes, lighten, makeStyles, private_createTypography, private_excludeVariablesFromRoot, recomposeColor, responsiveFontSizes, rgbToHex, shouldSkipGeneratingVar, styled, unstable_createMuiStrictModeTheme, unstable_getUnit, unstable_toUnitless, useColorScheme, useTheme, useThemeProps, withStyles, withTheme)
[FAILED]  @ ../common/src/index.ts 9:0-25 9:0-25
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/styles/index.ts 9:0-124
[FAILED] export 'SxProps' (reexported as 'SxProps') was not found in '@mui/material/styles' (possible exports: Experimental_CssVarsProvider, StyledEngineProvider, THEME_ID, ThemeProvider, adaptV4Theme, alpha, createMuiTheme, createStyles, createTheme, css, darken, decomposeColor, duration, easing, emphasize, experimentalStyled, experimental_extendTheme, experimental_sx, getContrastRatio, getInitColorSchemeScript, getLuminance, getOverlayAlpha, hexToRgb, hslToRgb, keyframes, lighten, makeStyles, private_createTypography, private_excludeVariablesFromRoot, recomposeColor, responsiveFontSizes, rgbToHex, shouldSkipGeneratingVar, styled, unstable_createMuiStrictModeTheme, unstable_getUnit, unstable_toUnitless, useColorScheme, useTheme, useThemeProps, withStyles, withTheme)
[FAILED]  @ ../common/src/index.ts 9:0-25 9:0-25
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/types/index.ts 4:0-83
[FAILED] export 'UserStoreNodeFragment' (reexported as 'UserStoreNodeFragment') was not found in '../authentication/api/operations.generated' (possible exports: AuthTokenDocument, MeDocument, PermissionsDocument, RefreshTokenDocument, StorePreferencesDocument, UserStoreNodeFragmentDoc, getSdk, mockAuthTokenQuery, mockMeQuery, mockPermissionsQuery, mockRefreshTokenQuery, mockStorePreferencesQuery)
[FAILED]  @ ../common/src/index.ts 11:0-24 11:0-24
[FAILED]  @ ../common/src/authentication/api/api.ts 10:0-48 75:16-36 75:52-73
[FAILED]  @ ../common/src/authentication/api/index.ts 1:0-22 1:0-22
[FAILED]  @ ../common/src/authentication/index.ts 2:0-22 2:0-22
[FAILED]  @ ../common/src/hooks/useNativeClient/useNativeClient.ts 19:0-54 24:22-36
[FAILED]  @ ../common/src/hooks/useNativeClient/index.ts 2:0-34 2:0-34
[FAILED]  @ ./src/electron.ts 14:0-100 130:32-47 146:34-49 201:13-23 249:24-39
[FAILED]
[FAILED] WARNING in ../common/src/ui/components/index.ts 44:0-423
[FAILED] export 'TextFieldProps' (reexported as 'TextFieldProps') was not found in '@mui/material/TextField' (possible exports: default, getTextFieldUtilityClass, textFieldClasses)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Expected behaviour 🤔

👍 

## How to Reproduce 🔨

`yarn electron:build`

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2027 

# 👩🏻‍💻 What does this PR do? 
 
The recent changes have resulted in additional aliased imports being required of `useNativeClient` and this has the effect of breaking the desktop build.

To resolve - I've implemented the `TsconfigPathsPlugin` which we have already used in the host build, which adds in all the alias values from tsconfig. Currently there is only one alias added to the webpack config and this is no longer sufficient.

Along the way I regenerated the graphql codegen, and then fixed the resulting output. As part of the generation, I noticed warnings with the server build, so have fixed those too.

# 🧪 How has/should this change been tested? 

Test that the electron build works. 

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts [hunk 1]
```diff
@@ -1,6 +1,10 @@
-import { uniqWith } from 'lodash';
 import { useState, useEffect } from 'react';
+import { useMutation } from 'react-query';
```
Comment (mark-prins) [inline client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:2]: the changes here are simply reordering - convention has it that 'react' imports are first, and I've also moved 'react-query' up a bit. 
The preferred order (for me, at least) is:
- react
- external packages
- internal packages
- local files

so that's what I've done. no functional changes.

File: client/packages/host/package.json [hunk 2]
```diff
@@ -37,7 +37,6 @@
     "history": "^5.1.0",
     "react": "^18.0.0",
     "react-dom": "^18.0.0",
-    "react-router-dom": "^6.0.2",
```
Comment (mark-prins) [inline client/packages/host/package.json:40]: this shouldn't be here! it's imported by common ( and a different version, at that ) and can be imported from `@common` if required

File: client/packages/host/src/components/AuthenticationAlert.tsx [hunk 3]
```diff
@@ -3,9 +3,9 @@ import { AppRoute } from '@openmsupply-client/config';
 import React, { useEffect } from 'react';
 import {
   AuthError,
-  matchPath,
   Location,
   RouteBuilder,
+  matchPath,
```
Comment (mark-prins) [inline client/packages/host/src/components/AuthenticationAlert.tsx:8]: alphabetical ordering. sorry, but not sorry.

File: client/packages/system/src/Sync/api/operations.generated.ts [hunk 4]
```diff
@@ -1,7 +1,7 @@
 import * as Types from '@openmsupply-client/common';
 
 import { GraphQLClient } from 'graphql-request';
-import * as Dom from 'graphql-request/src/types.dom';
+import * as Dom from 'graphql-request/dist/types.dom';
```
Comment (mark-prins) [inline client/packages/system/src/Sync/api/operations.generated.ts:4]: I regenerated, and this is the result.

File: server/graphql/batch_mutations/src/batch_prescription.rs [hunk 5]
```diff
@@ -17,23 +17,23 @@ use crate::{to_standard_error, VecOrNone};
 ))]
 #[graphql(concrete(
     name = "UpdatePrescriptionResponseWithId",
-    params(prescription::UpdateResponse)
+    params(prescription::update::UpdateResponse)
```
Comment (mark-prins) [inline server/graphql/batch_mutations/src/batch_prescription.rs:20]: to bring these into line with the current convention.

Comment (clemens-msupply) [reply server/graphql/batch_mutations/src/batch_prescription.rs:20]: thanks!

File: client/packages/system/src/Sync/api/operations.generated.ts (hunk 4 above)
Comment (clemens-msupply) [reply client/packages/system/src/Sync/api/operations.generated.ts:4]: Btw. this works for me but when I generate the api here I still get invalid code that doesn't compile...

**Review by clemens-msupply — APPROVED** [review]
Builds and starts fine! thank you!

File: client/packages/system/src/Sync/api/operations.generated.ts (hunk 4 above)
Comment (mark-prins) [reply client/packages/system/src/Sync/api/operations.generated.ts:4]: thanks! yes I was getting some errors introduced. now getting different ones - the fragment path in request requisitions and the extra bit at the bottom of the stocktakes. I thought to make an issue for those after this one.
