### PR TITLE
Delete unwanted placeholder rows

### LINKED ISSUE #1894: Have to allocate twice in outbound shipment created from requisition
## What went wrong? 😲
https://github.com/openmsupply/open-msupply/assets/61820074/36a8466d-70fe-4a8a-9f47-142d19506572

## Expected behaviour 🤔
User should only have to allocate once. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Store A send a requisition to the store
2. Store B receives requisition, issues some stock and creates outbound shipment
3. Allocate stock through modal. 
5. When you allocate again from action bar, you will be supplying twice as much as what you wanted to supply

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1894 

# 👩🏻‍💻 What does this PR do? 
 
The placeholder row `numberOfPacks` is set to `0` when creating [newDraftOutboundLines](https://github.com/openmsupply/open-msupply/blob/develop/client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts#L74) and then lines are allocated quantities. The issue arises because the previous placeholder line has a non-zero quantity, but the new placeholder row is not allocated, and therefore does not have `isUpdated` set.

This change is to check for the specific case and set the `isUpdated` flag if there is a previous placeholder quantity which is no longer required. There's a subsequent change to allow deleting of placeholder rows.

# 🧪 How has/should this change been tested? 

As per the issue - create an outbound with a placeholder row. Allocate in the modal - if all of the placeholder quantity is allocated, the placeholder row should be removed.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

**Review by roxy-dao — COMMENTED** [review]
LGTM, thanks Mark.

I noticed something else about the placeholder row... If you self-allocate a stocktake line instead of pressing `Allocate`, the placeholder line is kept and a new line is created with the stock line

https://github.com/openmsupply/open-msupply/assets/61820074/918648ab-a3eb-4786-80b9-0933ef2f8947

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts [hunk 1]
```diff
@@ -111,24 +111,34 @@ export const allocateQuantities =
...
 
-    if (status === InvoiceNodeStatus.New && toAllocate > 0) {
+    if (status === InvoiceNodeStatus.New) {
       const placeholderIdx = newDraftOutboundLines.findIndex(
         ({ type }) => type === InvoiceLineNodeType.UnallocatedStock
       );
       const placeholder = newDraftOutboundLines[placeholderIdx];
+      const oldPlaceholder = draftOutboundLines[placeholderIdx];
+      const placeholderRemoved =
+        (oldPlaceholder?.numberOfPacks ?? 0 > 0) &&
```
Comment (roxy-dao) [inline client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts:121]: is 0 > 0 needed? 🤔

**Comment by mark-prins** [comment]
> If you self-allocate a stocktake line instead of pressing Allocate, the placeholder line is kept and a new line is created with the stock line

the original expectation is that the user will have to change the placeholder quantity in this case. 
Now that we've changed the placeholder quantity to be non-editable, it's a bit of a problem. Do we assume that if the user has edited something then we remove any placeholder?

File: client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts (hunk 1 above)
Comment (mark-prins) [reply client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts:121]: No, it's not. I've changed to `oldPlaceholder?.numberOfPacks` but also added a comment, as I don't think it's immediately obvious

**Review by roxy-dao — APPROVED** [review]
Thanks Mark (:
