### PR TITLE
782 Specify unique key prop on option list components

### LINKED ISSUE #782: Fix duplicate search results in new shipment name search
Odd bugs from customers with identical names and/or codes when searching for a customer on a new shipment. Just needs specified keys to be unique in the frontend.

Reproduction steps:

1. Setup 3 customers which have the same name, make them visible to the store being used on omsupply
2. On a new outbound shipment, when searching for the customer name used in step 1, try various combinations and find that the filtering is very broken. (Or fixed with this PR.)

Just a note - while it is odd to setup multiple customers with the same `name.name`, it is possible. A case would be say if several hospitals each had their own separate customer "WARD1". 99.9% we do enforce unique `name.code`, but it can be achieved if you make new `store` with identical name/code as an existing `name` (there is a pref to block this. IDK why we even have a pref for this, it should surely be stopped).

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #782

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Looks good! so the problem was that if there are items with the same name or code the results where missing/ not correct? and adding the react key fixes it? How to test it?

File: client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx [hunk 1]
```diff
@@ -26,12 +26,12 @@ export const getNameOptionRenderer =
...
               }}
             >
-              {item.code}
+              {name.code}
             </Typography>
           </Box>
           <Typography>
-            {item.name}
-            {item.isOnHold ? ` (${onHoldLabel})` : ''}
+            {name.name}
```
Comment (mark-prins) [inline client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx:33]: part of the reason for using `item` as the variable name is to avoid having `name.name` 🤷

**Review by mark-prins — APPROVED** [review]
👍  LGTM!

There are a number of other uses of the AutocompleteOption list - I wonder if we have to manually add a key to all of those implemenations?

File: client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx (hunk 1 above)
Comment (Chris-Petty) [reply client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx:33]: Hmm fair. I did it because I found it weird reading for the first while because the `item` table exists and has many of the same fields, though it was similar to the [`Flatlist` props I'm used to](https://reactnative.dev/docs/flatlist#required-renderitem). I had considered staying true to MUI prop names by calling it `option`, but thought continuing the `name` table specific context was useful. `optionName` was unaesthetic, 4 char word pleases me haha.
