### PR TITLE
Handle back button in android app

### LINKED ISSUE #1871: Apk crashes when we quit oms clicking Back button in mobile tablet
## What went wrong? 😲
In mobile tablet, I've noticed this a lot: click back button in mobile tablet, until the app closes. Reopen and see that the app crashes and is unable to open on first load. Again opening it works though! 

## Expected behaviour 🤔
No sudden crashes

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure oms is open with an active user login session
2. Click back button in mobile, until the app closes.
3. Now, open it again
4. See error: it won't open again!

## Your environment 🌱
 - Version: v1.1.13 apk
 - Platform:
   - [x] android (tablet)
 
## Screenshots/Recordings
https://github.com/openmsupply/open-msupply/assets/59193490/1023b02a-167a-454d-b932-5f5dc62bc69c

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1871 

# 👩🏻‍💻 What does this PR do? 
 
Have added the `App` plugin so that we can handle back button events and navigate back using react router. For me, this is working nicely, navigating back and not crashing the app. As commented on the issue though, I was unable to get the app to crash originally - perhaps the android version?

# 🧪 How has/should this change been tested? 

I've copied the apk `open-msupply-1.2.00-debug.apk`  to [google drive](https://drive.google.com/open?id=1TtOnYhrcgqMYpThLZzSg0SZawF19jciP&usp=drive_fs)
you may find this easier than building yourself. If you do build - use rustc v1.65.0 as later versions will not compile.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts [hunk 1]
```diff
@@ -112,15 +115,15 @@ export const useNativeClient = ({
 
   const allowSleep = async () => {
     // Currently only supported on native platforms via capacitor
-    if (!Capacitor.isNativePlatform) return;
+    if (!Capacitor.isNativePlatform()) return;
```
Comment (clemens-msupply) [inline client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:118]: Was this a bug before? or did this change through the plugin?

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts [hunk 2]
```diff
@@ -172,6 +175,19 @@ export const useNativeClient = ({
     getPreference('previousServer', '').then(server => {
       if (!!server) setState(state => ({ ...state, previousServer: server }));
     });
+    if (Capacitor.isNativePlatform()) {
+      App.removeAllListeners();
+      App.addListener('backButton', ({ canGoBack }) => {
+        console.log('back!', canGoBack);
```
Comment (clemens-msupply) [inline client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:181]: Remove debug output?

File: client/packages/android/package.json [hunk 3]
```diff
@@ -4,6 +4,8 @@
   "private": true,
   "devDependencies": {
     "@capacitor-community/barcode-scanner": "^3.0.3",
+    "@capacitor-community/keep-awake": "^3.0.0",
+    "@capacitor/app": "^4.1.1",
```
Comment (clemens-msupply) [inline client/packages/android/package.json:8]: Is it correct that they are under devDependencies? if yes why?

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts (hunk 1 above)
Comment (mark-prins) [reply client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:118]: An existing bug that I'd spotted when editing the file

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts (hunk 2 above)
Comment (mark-prins) [reply client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:181]: Oops!

File: client/packages/android/package.json (hunk 3 above)
Comment (mark-prins) [reply client/packages/android/package.json:8]: It's a bit strange isn't it. They don't need to be dependencies because capacitor is including the java files (`npx cap sync` and then the build process) and that's all that is required at runtime.

I've included them in the android/package just so that `npx cap sync` will detect the plugins correctly. Apart from that, the packages are used only for typescript checking, so a dev dep is sufficient.

I'll move them to runtime dependencies in the android package and will keep them as dev dependencies in the other packages. I think that's clearer

Comment (clemens-msupply) [reply client/packages/android/package.json:8]: Ok thanks!

**Review by clemens-msupply — COMMENTED** [review]
I don't manage to crash the app but the back button also stopped working entirely (Lenovo tablet). Not sure, is this the desired behaviour?

**Comment by mark-prins** [comment]
> I don't manage to crash the app but the back button also stopped working entirely (Lenovo tablet). Not sure, is this the desired behaviour?

Not desired no! I've now installed on a lenovo and with the develop branch, have it crash; and with this branch the back button works, in that it navigates back and the app does not crash.

Unable to replicate the back button not working issue unfortunately. Nice to have the crash recreated though!

**Review by clemens-msupply — APPROVED** [review]
