### PR TITLE
Move "Group By Item" option to Toolbar in 3 places

### LINKED ISSUE #1760: [User Training Feedback] Stocktake (and possibly others) scrolling down the list is misleading / not working well
## What went wrong? 😲
 

Here's how it looks on windows:

https://github.com/openmsupply/open-msupply/assets/9192912/e9b00567-dbeb-4999-bc9f-546f13aeadc2

## Expected behaviour 🤔

Users thought the item they were looking for was missing because it was hard to scroll down. 

- [ ] Users are not used to using 2 fingers on the touchpad to scroll up and down or from right to left. Right now, you have to use the touchpad to make the scroll bars appear. 

- [ ] scrolling bar is sometime misleading and you think you're at the end of the list even if there are a lot of items hidden. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

add a lot of items to a stoctake and try to scroll down without the touchpad

## Your environment 🌱

 - Version: 1.1.12
 - Platform:
   - [ ] browser (chrome)
   - [ ] desktop (windows)

## Proposed solution 
Move the Group By toggle up into the first section so that the second scroll bar goes away

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #1760 (partial)

# 👩🏻‍💻 What does this PR do? 
 

As suggested as an interim solution, I've moved the "Group by item" toggle to the Toolbar. Was used in 2 other places, too, so have done the same there. Not 100% sold on the placement, but didn't want to take more vertical space in the Toolbar, but open to suggestions:

Screenshot 2023-05-15 at 3 15 42 PM

# 🧪 How has/should this change been tested? 

Check the "Group by item" toggle in Stocktake, Inbound Shipment, and Outbound Shipment. Make sure behaviour is the same as previous.

## 💌 Any notes for the reviewer?

I won't link this PR to the original issue for now, since there is a wider issue regarding the scroll bars that should probably be sorted separately at some point.

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx [hunk 1]
```diff
@@ -77,6 +87,15 @@ export const Toolbar: FC = () => {
             }}
             debounceTime={0}
           />
+          <Box sx={{ marginRight: 2 }}>
+            <Switch
+              label={t('label.group-by-item')}
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx:92]: side note: `"label.group-by-item": "Group by Item",` is in three files now, and could move to `common.json`

**Review by mark-prins — APPROVED** [review]
👍  LGTM! I'm also not certain about the placement, but have no better suggestions to offer!

File: client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx (hunk 1 above)
Comment (CarlosNZ) [reply client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx:92]: Cool - done e5491f58e
