### PR TITLE
1709 enforce is sync update being reset in requisition

### LINKED ISSUE #1709: Remote requisition records are not syncing after initialisation
## What went wrong? 😲

When requisitions records arrive during initialisation and then edited, they are not marked as needing to sync out (don't sync back to central after edit)

## Expected behaviour 🤔

They sync

## How to Reproduce 🔨

Create and sync site, create internal order with lines, sync. Re-initialise, sync (to make sure nothing is in sync queue) try editing this requisition and lines, then sync (see that nothing was pushed)

## Extra

This is due to is_sync_update not being set back to `false`. I noticed this while testing program remote authorisation (so this also applies to response requisitions (without re initialisation, actually, after approval)

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1709 

# 👩🏻‍💻 What does this PR do? 

Move is_sync_update out of Requisition/LineRow and to repository upsert methods, see commments in PR

# 🧪 How has/should this change been tested? 

Create and sync site, create internal order with lines, sync. Re-initialise, sync (to make sure nothing is in sync queue) try editing this requisition and lines, then sync (see that nothing was pushed)

# Extra

@clemens-msupply @roxy-dao, this strategy might be used in program for tables with is_sync_update field (leaving general service operations free of is_sync_update logic, and reducing the chance that is_sync_update is not set back to false).

### CODE REVIEW

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 1]
```diff
@@ -35,19 +35,35 @@ table! {
...
 joinable!(requisition -> name (name_id));
 joinable!(requisition -> store (store_id));
 joinable!(requisition -> user_account (user_id));
 joinable!(requisition -> period (period_id));
 joinable!(requisition -> program (program_id));
 
+#[derive(AsChangeset)]
+#[table_name = "requistion_is_sync_update"]
+#[cfg_attr(test, derive(Debug, PartialEq, Queryable))]
+struct RequisitionIsSyncUpdate {
```
Comment (andreievg) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:61]: Could have done without this struct, but it was easier to update and check is_sync_update with this

File: server/service/src/sync/test/mod.rs [hunk 2]
```diff
@@ -115,28 +115,6 @@ pub(crate) async fn insert_all_extra_data(
     }
 }
 
-macro_rules! check_record_by_id_ignore_is_sync_update {
```
Comment (andreievg) [inline server/service/src/sync/test/mod.rs:118]: Don't need this anymore sync row record is free from is_sync_update

File: server/service/src/sync/translation_and_integration.rs [hunk 3]
```diff
@@ -134,7 +134,11 @@ impl<'a> TranslationAndIntegration<'a> {
 }
 
 impl IntegrationRecords {
-    pub(crate) fn integrate(&self, connection: &StorageConnection) -> Result<(), RepositoryError> {
+    pub(crate) fn integrate(
+        &self,
+        connection: &StorageConnection,
+        is_sync: bool,
```
Comment (andreievg) [inline server/service/src/sync/translation_and_integration.rs:140]: this is needed now, since integration tests use integrate to insert/upsert records that will in the future need to sync, without this toggle, couldn't reuse integrate method in integration test

Comment (andreievg) [reply server/service/src/sync/translation_and_integration.rs]: this was removed in favour of updating is_sync_update status (keeps core code 'cleaner')

File: server/repository/src/db_diesel/requisition/requisition_row.rs (hunk 1 above)
Comment (andreievg) [reply server/repository/src/db_diesel/requisition/requisition_row.rs]: Did without this struct at the end, as it turns, AsChangeset doesn't actually add filter by id on the update query.

File: server/service/src/sync/test/integration/remote/program_requisition.rs
Comment (andreievg) [inline server/service/src/sync/test/integration/remote/program_requisition.rs:1]: Since i updated integration tests, wanted to make sure they work for pg and sqlite, noticed that postgres tests were failing in dev. They would pass if it's the first time the test is run on 4d data file but failed after. And were passing in sqlite but not postgres:

It turns out it's because name of the name tag was not unique, this is looked up during translation and in postgres it must be getting the first records in db and in sqlite it's getting the last record in db (which is correct). So changed to use uuid()

@roxy-dao i kind of remember you raising this and me saying i tried and it's fine (I didn't try twice though)

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 4]
```diff
@@ -156,13 +161,27 @@ impl<'a> RequisitionRowRepository<'a> {
     }
 
     #[cfg(not(feature = "postgres"))]
-    pub fn upsert_one(&self, row: &RequisitionRow) -> Result<(), RepositoryError> {
+    fn upsert_one_etc(&self, row: &RequisitionRow) -> Result<(), RepositoryError> {
```
Comment (mark-prins) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:164]: I'm not sure what the 'etc' is for - the fn is still just an upsert on the requisition row.

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 5]
```diff
@@ -156,13 +161,27 @@ impl<'a> RequisitionRowRepository<'a> {
...
 
+    fn toggle_is_sync_update(&self, id: &str, is_sync_update: bool) -> Result<(), RepositoryError> {
+        diesel::update(requistion_is_sync_update::table.find(id))
+            .set(requistion_is_sync_update::dsl::is_sync_update.eq(is_sync_update))
+            .execute(&self.connection.connection)?;
+
+        Ok(())
+    }
+
+    pub fn upsert_one(&self, row: &RequisitionRow) -> Result<(), RepositoryError> {
```
Comment (mark-prins) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:179]: ah right. surely this fn should be called the `_etc` version?

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 6]
```diff
@@ -35,13 +35,20 @@ table! {
...
         approval_status -> Nullable<crate::db_diesel::requisition::requisition_row::RequisitionRowApprovalStatusMapping>,
         linked_requisition_id -> Nullable<Text>,
-        is_sync_update -> Bool,
         program_id -> Nullable<Text>,
         period_id -> Nullable<Text>,
         order_type -> Nullable<Text>,
     }
 }
 
+table! {
```
Comment (mark-prins) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:44]: this like a view on the requisition table is it? It's very neat!

**Review by mark-prins — APPROVED** [review]
🎉  that's fantastic. the separation is very neat, and I like the approach. all tested and working well.
All I have is a minor quibble about fn names.. that's not a show stopper

File: server/repository/src/db_diesel/requisition/requisition_row.rs (hunk 4 above)
Comment (andreievg) [reply server/repository/src/db_diesel/requisition/requisition_row.rs]: tbh, i don't know what `_etc` stands for here, I saw it when Clemens used it in StorageConnection and liked it, my AI friend said it's to do with extra parameters (so it's incorrect):

Screenshot 2023-05-11 at 3 11 08 PM

https://github.com/openmsupply/open-msupply/blob/c48435ae02d23d86ed19781570876004e17ab3bb/server/repository/src/db_diesel/storage_connection.rs#L79-L91

I think another convention is to use `_`, hope this is better: 26c6d8ac4ad09d2940f0ae3078fe9ce509aa34eb

File: server/repository/src/db_diesel/requisition/requisition_row.rs (hunk 5 above)
Comment (andreievg) [reply server/repository/src/db_diesel/requisition/requisition_row.rs:179]: oops, as per pervious answer

File: server/repository/src/db_diesel/requisition/requisition_row.rs (hunk 6 above)
Comment (andreievg) [reply server/repository/src/db_diesel/requisition/requisition_row.rs:44]: I guess it's like a view, except you can edit it, it's treating requisition table as only having id and is_sync_update

**Comment by andreievg** [comment]
> the separation is very neat, and I like the approach

Thanks, and thanks for review

File: server/repository/src/db_diesel/requisition/requisition_row.rs (hunk 4 above)
Comment (clemens-msupply) [reply server/repository/src/db_diesel/requisition/requisition_row.rs]: I also just used it because I saw it somewhere else before. The _etc function takes the full set of parameters and the other function is the more common version with a smaller number of params (to make the more common use case simpler).

File: server/repository/src/db_diesel/requisition/requisition_row.rs [hunk 7]
```diff
@@ -35,13 +35,20 @@ table! {
...
+    #[sql_name = "requisition"]
+    requistion_is_sync_update (id) {
```
Comment (mark-prins) [inline server/repository/src/db_diesel/requisition/requisition_row.rs:46]: @andreievg oh. just notice the spelling on this. The requisition is missing an 👁️
