### PR TITLE
Requisition fixes

### LINKED ISSUE #319: Customer requisition fixes
Created from #225 

**2. OHC Store: receiving and processing a requisition from KHC**
- [x] Requisition line comment: req line comment have disappeared. Is it only meant for the supplying store ? I thought it could be useful to communicate with the supplier. 
- [x] Requisition comment: same as above. 
- [x] Requisition line window: elements are not in the order as the internal order line window (comment should be on the right)
- [ ] Requisition line window: no charts (could be a priority choice)
- [ ] Create Shipment Button (1/2): opens the shipment in another window (why ?) + sometimes it takes very long time to load the Outbound Shipment or it simply fails. 
- [ ] Create Shipment Button (2/2): does not happen all the time but on multiple occasions it created an O/S for another customer and with different products  and Status = Verified (see screenshots below) - Similar to [issue 208 ?](https://github.com/openmsupply/open-msupply/issues/219#issue-1288164631):
Screen Shot 2022-06-29 at 6 09 32 PM
Screen Shot 2022-06-29 at 6 09 54 PM

- [x] Outbound Shipment: I try to confirm Allocation while line is unallocated. I get the error message (OK) and then I'm logged out (that being the issue here). See video below:

https://user-images.githubusercontent.com/74992958/176487552-57123a98-ccad-4577-a341-75d0b0787df3.mp4

- [ ] Outbound Shipment > Manual Allocation > list of batch numbers: we should no longer see batch with 0 stock (see screenshot below - last batch number of the list): 
Screen Shot 2022-06-29 at 6 28 15 PM

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #319 

- [ ] Requisition line comment is copied from the internal order line
- [ ] Requisition comment uses the same format as mSupply: `From request requisition [req #] ([internal order comment])`
- [ ] Requisition line window has the comments on the right, as per internal order

### CODE REVIEW

**Review by CarlosNZ — APPROVED** [review]
Front-end looks good. Cheers

File: server/service/src/sync_processor/requisition/common.rs [hunk 1]
```diff
@@ -71,6 +71,11 @@ pub fn generate_linked_requisition(
 
     let name_id = record_for_processing.source_name.id.clone();
 
+    let source_comment = match source_requisition.comment.clone() {
```
Comment (clemens-msupply) [inline server/service/src/sync_processor/requisition/common.rs:74]:
```suggestion
    let source_comment = match &source_requisition.comment {
```

**Review by clemens-msupply — APPROVED** [review]
BE looks good as well

File: server/service/src/sync_processor/requisition/common.rs (hunk 1 above)
Comment (mark-prins) [reply server/service/src/sync_processor/requisition/common.rs:74]: thanks Clemens - have made the change
