### PR TITLE
#1285 Fix for unable to create new patient

### LINKED ISSUE #1285: When creating a patient, you cannot click create
## What went wrong? 😲
 
After entering patient details, and searching, I'm presented with a patient entry form. I want to create the patient, but the button is disabled:

Screenshot 2023-03-07 at 9 18 19 AM

## Expected behaviour 🤔
A message explaining which fields need to be filled in, if there are any, or
the button should be enabled if there isn't anything to be entered

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary > Patients
2. Click on `New Patient`
3. Enter some details
4. Click `OK & Next`
5. Click `Create`
6. Note the state of the button. Entering anything in the fields will trigger the `isDirty` check and enable the button

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #1285 

# 👩🏻‍💻 What does this PR do? 
 

I think this should fix the immediately reported problem from #1285, but it was only happening intermittently for me, so not 100% sure. However, it does fix the other two problems I noted on that thread and so I think it takes care of the main problem too. 

I think it was all due to the infinite re-render caused by the `setPatient` method causing a change in `patient` even though no actual data had changed, which in turn caused `setPatient` to re-run when the component re-rendered, etc. 

This is a problem I've encountered before -- when a state object changes its instance (due to a new object being created with ` {...originalState, ...newState }`) but not actually having any new data. It can be fixed by doing a deep equality check (in this case with `lodash`), but I feel like there should be a nicer way to prevent this kind of thing, so suggestions welcome!

# 🧪 How has/should this change been tested? 

Follow the steps reported in the original issue and check that the problem has gone away. Also, you can add `console.log("patient", patient)` in `CreatePatientModal.ts` to note that the infinite re-render has been fixed (compare it with base branch).

### CODE REVIEW

File: client/packages/system/src/Patient/PatientView/PatientView.tsx [hunk 1]
```diff
@@ -78,9 +78,11 @@ const PatientDetailView: FC = () => {
   const handleSave = useUpsertPatient();
   const { JsonForm, saveData, isSaving, isDirty, validationError } =
     useJsonForms(patient ? undefined : documentName, { handleSave }, createDoc);
+
   useEffect(() => {
     return () => setNewPatient(undefined);
   }, []);
+
```
Comment (CarlosNZ) [inline client/packages/system/src/Patient/PatientView/PatientView.tsx:85]: Purely cosmetic :)

File: client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx [hunk 2]
```diff
@@ -8,6 +8,7 @@ import {
 } from '@openmsupply-client/programs';
 import { PatientPanel } from './PatientPanel';
 import { createPatient, createPatientUI } from './DefaultCreatePatientJsonForm';
+import { isEqual } from 'lodash';
```
Comment (mark-prins) [inline client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx:11]: as per #1271, lodash isn't tree shaking.
Also, as a general rule, we've been trying to not import from external packages in any package except common - in order to isolate / limit external packages & dependencies. It also means that we don't have duplicate imports in multiple packages - only into common, which then re-exports.

So.. could you add `isEqual` to `common/src/utils/index.ts` ( after the bundle size PR is merged! ) and import from 

`import { isEqual } from '@common/utils'`;

**Review by mark-prins — COMMENTED** [review]
just dropping in a quick comment.. haven't tested the change yet!

File: client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx]: Yup, looks like it was already there in `ObjUtils`, so have imported from there: b16aeb6d1

Comment (CarlosNZ) [reply client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx]: I see the`useJsonForms` module imports the whole lodash `_` default. Should we fix that up too?

**Review by clemens-msupply — APPROVED** [review]
Looks good! This one was just an issue in the initial patient creation dialog, right?

File: client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx [hunk 3]
```diff
@@ -128,7 +128,7 @@ export const CreatePatientModal: FC<CreatePatientModal> = ({ onClose }) => {
       okButton={
         currentTab === Tabs.SearchResults ? (
           <DialogButton
-            variant="create"
+            variant="next"
```
Comment (mark-prins) [inline client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx:131]: Quick roll of the eyes 🙄 
#728 was when it was changed from `ok` to `create` because the ok text didn't indicate clearly enough that you will be creating a patient. I suppose that `ok & next` is more of an indication that something is going to happen, and that you won't be creating the patient yet.

**Review by mark-prins — APPROVED** [review]
👍  Have been unable to replicate.. so it's hard to say if this fixes it!
Changes look ok though, thanks. Would be nice to fix the `lodash` imports in `useJsonForms` though.. only a few functions are used from it

File: client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx (hunk 3 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx:131]: ups :) I found it confusing that create didn't save the patient directly.

We could save the patient directly though. The reason why its not done is that you would have two document versions when creating a patient, one with the base information and one with the full information from the full form. Probably not an issue to have two version immediately though...
