### PR TITLE
1693 For locations, limit of records per page doesn't seem to be respected

### LINKED ISSUE #1693: For locations, limit of records per page doesn't seem to be respected
## What went wrong? 😲
 
If I have 21 total records it seems to show all the 21 records even though the limit is 20.
page1
image

page2
image

## Expected behaviour 🤔

Should respect the limit is supposed unless there is unwritten rule that says you can 10 over the limit :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Set the limit of records per page to 20 
2. Create 21 locations
3. Click on page 1
5. Click on Page 2
6. See error

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [e.g. windows desktop]

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1693 

# 👩🏻‍💻 What does this PR do? 
Add offset and first to locations hook to get the ListView to paginate properly.

# 🧪 How has/should this change been tested? 
- [ ] Have more than 20 locations
- [ ] Go to Location page
- [ ] Should only have the first 20 locations on first page 
- [ ] Swap to 2nd page and the rest of the locations should load

### CODE REVIEW

File: client/packages/system/src/Location/ListView/ListView.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ const LocationListComponent: FC = () => {
       <AppBarButtons onCreate={() => onOpen()} />
       <DataTable
         id="location-list"
-        pagination={{ ...pagination, total: data?.totalCount }}
+        pagination={{ ...pagination, total: data?.totalCount ?? 0 }}
```
Comment (mark-prins) [inline client/packages/system/src/Location/ListView/ListView.tsx:53]: 🤔  there are 14 instances of the pagination being used like this, and this is the third which has the `?? 0`
Should we change the others?

**Review by mark-prins — APPROVED** [review]
👍  Who would've thought that there'd be more than 20 locations?
