### PR TITLE
726 invoice issues #1

### LINKED ISSUE #726: Invoice Issues #1
Adding more...

- [ ] Service button doesn't work anymore for Outbound Shipments
- [ ] Tax input in service line modal doesn't allow for decimal inputs, but tax input in side bar for service does

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #726 

- Fix service button in Outbound Shipments
-  Decimal inputs for tax
-  Fix message when outbound is created from requisition
-  Outbound shipment now shows item batch
-  Total calculated for inbound shipment

Total on service charges doesn't update immediately after putting amount and tax in on modal <- will transfer to another issue

Note: Need clarification on how prices should be transferred from Outbound to Inbound Shipments (tax, totals, etc)

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx [hunk 1]
```diff
@@ -19,26 +19,24 @@ const RelatedDocumentsSectionComponent = () => {
...
   const { requisition } = useOutbound.document.fields('requisition');
 
-  let tooltip = '';
-  if (requisition) {
-    const { user, createdDatetime } = requisition;
-    tooltip = t('messages.customer-requisition-created-on', {
-      date: d(new Date(createdDatetime)),
+  const getTooltip = (createdDatetime: string, username?: string) => {
+    let tooltip = t('messages.customer-requisition-created-on', {
+      date: d(createdDatetime),
```
Comment (mark-prins) [inline client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx:24]: if `requisition` is undefined (which it can't be due to the conditional) then so is the `createdDatetime` and then DateUtils throws an error. We will also have a problem if the date format is problematic and can't be parsed.

I wonder about updating `DateUtils` like this: https://github.com/openmsupply/open-msupply/compare/726-invoice-issues-%231...726-invoice-issues-%231-dates

Since I've had this problem already elsewhere 😉

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx [hunk 2]
```diff
@@ -19,26 +19,24 @@ const RelatedDocumentsSectionComponent = () => {
...
+  };
 
   return (
     <DetailPanelSection title={t('heading.related-documents')}>
       <Grid item flexDirection="column" container gap={0.5}>
         {!requisition ? (
           <PanelLabel>{t('messages.no-related-documents')}</PanelLabel>
         ) : (
-          <Tooltip title={tooltip}>
+          <Tooltip title={getTooltip(requisition?.createdDatetime, requisition.user?.username)}>
```
Comment (mark-prins) [inline client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx:39]:
```suggestion
          <Tooltip title={getTooltip(requisition.createdDatetime, requisition.user?.username)}>
```

because requisition can't be undefined at this point

File: client/packages/system/src/Item/api/hooks/useItems/useItems.ts [hunk 3]
```diff
@@ -9,7 +9,7 @@ export const useItems = () => {
 
   return {
     ...useQuery(api.keys.paramList(queryParams), () =>
-      api.get.list(queryParams)
+      api.get.stockItems(queryParams)
```
Comment (mark-prins) [inline client/packages/system/src/Item/api/hooks/useItems/useItems.ts:12]: :nit I have a small problem with the hook being `useItems` but it returning only `stockItems` because I'm concerned that later someone will use the hook and be sad that they only get stock items.

A small digression - which I just put in because I'm thinking about it. I'll write up an issue for these ideas..

Since the hook is only used once, we could rename to `useStockItems` though now i'm wondering if the item list shouldn't just show all items and have a `type` column. Probably though, something like mSupply, where we default to showing stock items and have the option to show 'hidden items' 

or.. implement the fancy filter concept which Manu had created, and default the filter to 'stock' items.

**Review by mark-prins — APPROVED** [review]
🎉  Thanks Roxy!!

Related thought: I'm thinking that we should display currency at 2dp to avoid messiness like this:

image

What do you think about updating the currency formatter and setting the default lower than the current 10 dp?
