### PR TITLE
Form submit

### LINKED ISSUE #371: JSON Forms: safe button sometimes need double click
The JSON form seems only get updated/validated one a control change focus.
This also block the safe button, i.e. it requires two clicks.

To reproduce: edit a field but stay in the input field and click the safe button. Button is clicked and animated but nothing happen...

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #371 

To make the form submission nicer to use, I've swapped out the `onBlur` for a debounced update. I like it better 🤷 
To make the PR much harder to read, I've refactored the hook - that file was too large for my taste and was doing too many things. I've lifted out the majority of the JSX into a new component.

Also disabled the save button when there's nothing to save, as it was, you clicked `Save` and it closed the form without saving. Minor thing, but that means the button doesn't say what it does.

Another minor tweak - have changed the cancel method; that was navigating back one, which was odd when you were on a page and then updated the URL to navigate to a patient. I've changed to an explicit navigate back to the list, as that is the expectation, I think.

When I first hit the patient page, I got this:
Screen Shot 2022-07-26 at 5 06 21 PM

which is because I was in a store which had no documents.. thus:

Screen Shot 2022-07-26 at 5 10 32 PM

The layout wasn't pretty enough for me, so I've changed it to this:

Screen Shot 2022-07-26 at 5 25 12 PM

and in doing so have also changed the behaviour slightly of when the buttons show - and have them disabled when loading, and put them at the bottom of the screen, below the loader.

## Tests

- [x] edit text in a Text input and click `Save`: should prompt on first click
- [x] observe that the `Save` button is disabled initially and is enabled once a change is made
- [x] edit text in a Text input with the `Save` button in view: observe that without leaving the field the button is enabled
- [x] change a date field: observe that `Save` is enabled
- [x] change a checkbox field: observe that `Save` is enabled
- [x] change a select field: observe that `Save` is enabled
- [ ] Navigate to a patient when in the wrong store ( you'll have to figure that one out! ): should get a nicely formatted error
- [ ] From the dashboard, enter the URL of a patient, click `Cancel`: should get to the patient list view

### CODE REVIEW

File: client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+  data,
+  documentRegistry,
+  isError,
+  isLoading,
+  setError,
+  updateData,
+}) => {
+  const t = useTranslation('common');
+
+  if (isError)
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx:113]: most of the file is just content moved from the hook. This error handler is the new part

File: client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+        <FormComponent
+          data={data}
+          jsonSchema={documentRegistry.jsonSchema}
+          uiSchema={documentRegistry.uiSchema}
+          setData={updateData}
+          setError={setError}
+          renderers={renderers}
+        />
+      )}
+      {children}
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx:152]: I have the buttons as children because I like that pattern - though they could instead be a specific `<Buttons/>` prop to make it more explicit

File: client/packages/common/src/ui/forms/JsonForms/components/Text.tsx [hunk 3]
```diff
@@ -1,13 +1,20 @@
...
+  DetailInputWithLabelRow,
+  useDebounceCallback,
+} from '@openmsupply-client/common';
 
 export const stringTester = rankWith(3, schemaTypeIs('string'));
 
 const UIComponent = (props: ControlProps) => {
   const { data, handleChange, label, path } = props;
   const [localData, setLocalData] = useState<string>(data);
+  const onChange = useDebounceCallback(
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/components/Text.tsx:14]: the default debounce time of 0.5s works nicely for me, open so suggestions.

File: client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx [hunk 4]
```diff
@@ -219,16 +116,10 @@ export const useJsonForms = (
...
-    // We should be able to remove materialRenderers once we are sure we have custom components to cover all cases.
-    ...materialRenderers,
-    { tester: stringTester, renderer: TextField },
-    { tester: selectTester, renderer: Selector },
-    { tester: groupTester, renderer: Group },
-    { tester: labelTester, renderer: Label },
-    { tester: dateTester, renderer: Date },
-    { tester: arrayTester, renderer: Array },
-  ];
+  const updateData = (newData: JsonData) => {
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx:119]: no, I didn't mean to move this method 🤷

File: client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx [hunk 5]
```diff
@@ -265,33 +154,49 @@ export const useJsonForms = (
     </Box>
   );
 
+  useEffect(() => {
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx:157]: I prefer to have the `useEffect` calls last, just above any `return` - just find it useful when reviewing the JSX to know what is going to change. let's call it my little quirk..

File: client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx [hunk 6]
```diff
@@ -265,33 +154,49 @@ export const useJsonForms = (
...
-            jsonSchema={documentRegistry.jsonSchema}
-            uiSchema={documentRegistry.uiSchema}
-            setData={updateData}
-            setError={setError}
-            renderers={renderers}
-          />
-        )}
-        {showButtonPanel && !isLoading && <ButtonPanel />}
-      </Box>
+        {showButtonPanel && <ButtonPanel />}
```
Comment (mark-prins) [inline client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx:198]: the change with the `ButtonPanel` was to display when loading to avoid a bit of jank, and have them disabled instead.
