### PR TITLE
868 Calendar select color

### LINKED ISSUE #868: Calendar select colour
Image

The dot for the selected day seem to have the wrong colour

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #868 

Change calendar highlight to blue instead of orange. Did this in develop, so will need to update programs with develop again soon~

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Looks nice! hook make it clear to me that its from the theme and you can also search now where the useAppTheme is used...

File: client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx [hunk 1]
```diff
@@ -2,13 +2,45 @@ import React, { FC } from 'react';
...
 > = props => {
+  const theme = useAppTheme();
+  
   return (
     <DatePicker
       disabled={props.disabled}
+      PopperProps={{
+        sx: {
+          '& .MuiTypography-root.Mui-selected': {
+            backgroundColor: `${theme.palette.secondary.main}`,
```
Comment (mark-prins) [inline client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx:18]: oh! just after I asked to merge!
there's no need to import theme and do it this way - if you are in the `sx` prop then the palette can be accessed directly. This works for me:

```
<DatePicker
      disabled={props.disabled}
      PopperProps={{
        sx: {
          '& .MuiTypography-root.Mui-selected': {
            backgroundColor: 'secondary.main',
          },
          '& .MuiTypography-root.Mui-selected:hover': {
            backgroundColor: 'secondary.main',
          },
          '& .Mui-selected:focus': {
            backgroundColor: 'secondary.main',
          },
          '& .MuiPickersDay-root.Mui-selected': {
            backgroundColor: 'secondary.main',
          },
        },
      }}
      PaperProps={{
        sx: {
          '& .Mui-selected': {
            backgroundColor: 'secondary.main',
          },
          '& button.Mui-selected:focus': {
            backgroundColor: 'secondary.main',
          },
          '& .Mui-selected:hover': {
            backgroundColor: 'secondary.main',
          },
        },
      }}
```

Comment (roxy-dao) [reply client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx:18]: I can create a quick PR to merge it like that (didn't realise you could do it that way 🙇🏻
