### PR TITLE
1620 program requisitions not pre populated with program items

### LINKED ISSUE #1620: Program Requisitions not pre-populated with program items
## What went wrong? 😲
Requisition lines are not created when creating a program requisition
Screenshot 2023-04-27 at 11 06 46 AM
Screenshot 2023-04-27 at 11 03 24 AM

## Expected behaviour 🤔
Items from the program should be automatically added to the requisition

## How to Reproduce 🔨
Create a program requisition and no lines.

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1620

# 👩🏻‍💻 What does this PR do? 
Auto generate requisition lines if created from a program.

# 🧪 How has/should this change been tested? 
Create a program requisition and see auto generated lines for items in the program's master list.

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

File: server/graphql/types/src/types/barcode.rs [hunk 1]
```diff
@@ -107,19 +107,16 @@ mod test {
...
-                                "barcode": "0123456789",
-                                "itemID": "AA460A207402434A89B1F6EEAC08DA43",
-                                "packSize": 1,
-                                "manufacturerID": "",
-                                "parentID": ""
-                            }"#
-                            .to_string();
-                        });
-                    }),
+                    barcode: Barcode {
```
Comment (roxy-dao) [inline server/graphql/types/src/types/barcode.rs:110]: Stole from #1601 👀

**Review by mark-prins — APPROVED** [review]
🎉  working nicely!
