### PR TITLE
Fix stock filter

### LINKED ISSUE #94: Bug: View Stock search fails when using item code
Navigate to:
https://demo-open.msupply.org/inventory/stock
image
Type in or copy and paste the code '030063'
image
This shouldn't cause a 'Oops something has gone wrong' Error...

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #94 

The issue is due to the query params change - converting number-like values to numbers means that they aren't strings.. which in turn means that they don't have a `.replace` method 😁 

There's a side issue: converting to a number changes the filter value of '0300' to 300 => '300' which then does not find the item, because the filter is a 'startsWith'. I've changed the behaviour for the filter parameter to allow numeric filtering.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1 +1,2 @@
 .DS_Store
+.vscode/launch.json
```
Comment (mark-prins) [inline .gitignore:2]: offroad: I added a launch config to debug rust and was told not to check it in, even though I thought it might be helpful to others.

File: client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts [hunk 2]
```diff
@@ -4,6 +4,17 @@ interface UrlQueryObject {
...
+// an example is the filter, which must allow filtering by numeric codes
+// if this is parsed as numeric, the query param changes filter=0300 to filter=300
+// which then does not match against codes, as the filter is usually a 'startsWith'
+const DefaultParsers: Record<
+  string,
+  (value: string) => string | boolean | number
+> = {
+  filter: (value: string) => value,
+};
+
```
Comment (CarlosNZ) [inline client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts:17]: Ah right, yes -- we can't assume that a number string should be a number. I guess this is the downside of relying on url query as primary source of truth since everything is a string in the query.

Just wondering -- do you think it's reasonable to assume that anything we don't want converted to `Number` or `Boolean` should just remain a string?

If so, then could we simplify this further just by passing the hook a list of keys that should be ignored by the `parseSearchParams` function.

```ts
export const useUrlQuery = ( ignoreList: string[]  = []) => { 
...
```

Then `parseSearchParams` would just have one additional line:

```ts
if (ignoreList.includes(key)) return [key, value]
```

And then in `useUrlQueryParams` we'd pass the ignore list:
```ts
  const { urlQuery, updateQuery } = useUrlQuery( ["filter"] );
```

I kind of like the idea of keeping `useUrlQuery` as a purely generic wrapper for `useSearchParams` and all of the app-specific requirements being at a higher level, but that's probably just me.

Let me know what you think?

**Review by CarlosNZ — COMMENTED** [review]
Thanks Mark, good spotting. Just made a suggested simplification -- see what you think.

File: client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts:17]: Or the parameter could be an object so it's clearer what you're passing in `useUrlQueryParams`:
```
  const { urlQuery, updateQuery } = useUrlQuery( { ignore: ["filter"] } );
```

File: .gitignore (hunk 1 above)
Comment (jmbrunskill) [reply .gitignore:2]: I think this should be kind what we did for example.yaml, where we provide examples but don't check in the one people use in case they want different settings. Adding .vscode/launch.example would be good I think.

File: client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts (hunk 2 above)
Comment (mark-prins) [reply client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts:17]: that's good - thanks Carl. Quite right about keeping app specific details out of `useUrlQuery`.
Was going to use an object to make it clearer, so good thing you popped that in! 😉

File: .gitignore (hunk 1 above)
Comment (mark-prins) [reply .gitignore:2]: good idea! I've put my current launch in - feel free to amend / improve / fix the preLaunchTask ( that wasn't working due to `server` being in a subdir )

File: client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts [hunk 3]
```diff
@@ -4,24 +4,19 @@ interface UrlQueryObject {
...
-};
-
-export const useUrlQuery = () => {
+interface useUrlQueryProps {
+  // an array of keys - the values of which should not be parsed before returning
+  // by default the value of parameters will be coerced to a number if !isNaN
+  // and to boolean if 'true' or 'false'. Specify keys here if you wish to opt out of this
+  skipParse?: string[];
+}
+export const useUrlQuery = ({ skipParse = [] }: useUrlQueryProps) => {
```
Comment (CarlosNZ) [inline client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts:13]:
```suggestion
export const useUrlQuery = ({ skipParse = [] }: useUrlQueryProps = {}) => {
```

Then you can get rid of those yucky empty object arguments you've used elsewhere ;)

**Review by CarlosNZ — APPROVED** [review]
Great, thanks Mark. 

Just one tiny suggestion to use a default empty object and you won't need the ugly empty object args.

File: client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts (hunk 3 above)
Comment (mark-prins) [reply client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts:13]: sure - though I don't mind the `({})` myself 🤷
