### PR TITLE
Fix infinity bug for bmi

### LINKED ISSUE #865: BMI control shows 'infinity'
Image

- [ ] fix division by zero

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #865

### CODE REVIEW

File: client/packages/system/src/Patient/JsonForms/components/BMI.tsx [hunk 1]
```diff
@@ -28,7 +28,10 @@ const UIComponent = (props: ControlProps) => {
 
     if (!handleChange || !w) return;
 
-    const bmi = round(w / (h * h));
+    let bmi = round(w / (h * h));
+    if (!isFinite(bmi)) {
+      bmi = 0
```
Comment (clemens-msupply) [inline client/packages/system/src/Patient/JsonForms/components/BMI.tsx:33]: Nit: could you please set to undefined?

**Review by clemens-msupply — APPROVED** [review]
Great thanks, see comment

File: client/packages/system/src/Patient/JsonForms/components/BMI.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/system/src/Patient/JsonForms/components/BMI.tsx]: [d04c85c](https://github.com/openmsupply/open-msupply/pull/869/commits/d04c85c2d5b78c232334b2ebd4ffd6f03c369c21)
