### PR TITLE
1310 The cross icon doesn't match the other icons in style (and is uncentred) 

### LINKED ISSUE #1310: The cross icon doesn't match the other icons in style (and is uncentred)
## What went wrong? 😲
 
The cross icon doesn't match the other icons in style. More importantly, it isn't horizontally centred!

Screenshot 2023-03-09 at 3 25 56 PM

## Expected behaviour 🤔
The icon should fit, and look pretty.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1310

# 👩🏻‍💻 What does this PR do? 
Make left margin 0... if margin is 0 then some icons move too left....

# 🧪 How has/should this change been tested? 
Go to dispensary, encounters and click on any to see the icons

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx [hunk 1]
```diff
@@ -246,6 +246,7 @@ const UIComponent: FC<LayoutProps & AjvProps> = ({
               textTransform: 'none',
               '& .MuiButton-startIcon': {
                 paddingBottom: '8px',
+                marginLeft: 0,
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx:249]: I think it needs `marginRight: 0` as well to override this:
Screenshot 2023-03-15 at 2 50 35 PM

The "Visit Type" icon looks correct after this. However some of the others don't, but that's because the icons themselves are mis-aligned within their own box:

Screenshot 2023-03-15 at 2 51 49 PM

But we should fix these icons themselves rather than try and mis-align them in the other direction. :) 

We can add a manual `transform` to them to shift the path over within the viewBox, so it looks like this:
Screenshot 2023-03-15 at 3 07 27 PM

That's adding `transform='translate(-75, 0)'` to the CSS data to give:
```
.test-tube {
  mask-image: url("data:image/svg+xml,%3Csvg version='1.1' viewBox='0 0 550 550' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m420 52.5c0-9.625-7.875-17.5-17.5-17.5h-105c-9.625 0-17.5 7.875-17.5 17.5 0 6.4766 3.5 12.074 8.75 15.051v404.95c0 33.773 27.477 61.25 61.25 61.25s61.25-27.477 61.25-61.25v-404.95c5.25-3.0625 8.75-8.5742 8.75-15.051zm-26.25 210h-87.5v-43.75h17.5c4.8125 0 8.75-3.9375 8.75-8.75s-3.9375-8.75-8.75-8.75h-17.5v-17.5h8.75c4.8125 0 8.75-3.9375 8.75-8.75s-3.9375-8.75-8.75-8.75h-8.75v-17.5h17.5c4.8125 0 8.75-3.9375 8.75-8.75s-3.9375-8.75-8.75-8.75h-17.5v-17.5h8.75c4.8125 0 8.75-3.9375 8.75-8.75s-3.9375-8.75-8.75-8.75h-8.75v-26.25h87.5z' transform='translate(-75, 0)'/%3E%3C/svg%3E%0A");
}
```

Looks like several of them could do with a little sliding over ;)

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
See comment :)

**Comment by CarlosNZ** [comment]
Also -- in `medical-icons.css`, I don't know that we need the `-webkit-mask-image` version of each of these. The `mask-image` property seems pretty well-supported now (https://caniuse.com/?search=mask-image), and that'll save a little bit on bundle size ;) 

Is that correct @mark-prins ?

File: client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx]: [9d6abb4](https://github.com/openmsupply/open-msupply/pull/1358/commits/9d6abb411cec26215ab2b3b2809e6609b012b90b) half the GBV's face disappears when I try to translate it...

Comment (CarlosNZ) [reply client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx]: > [9d6abb4](https://github.com/openmsupply/open-msupply/pull/1358/commits/9d6abb411cec26215ab2b3b2809e6609b012b90b) half the GBV's face disappears when I try to translate it... and the body doesn't move at all

I think the quote nesting is not quite right in that -- `transform='translate(-75, 0)'`should be inside the main `url("... ")` string but outside the path (single-quote).

**Comment by mark-prins** [comment]
> Also -- in `medical-icons.css`, I don't know that we need the `-webkit-mask-image` version of each of these. The `mask-image` property seems pretty well-supported now (https://caniuse.com/?search=mask-image), and that'll save a little bit on bundle size ;)
> 
> Is that correct @mark-prins ?

I'm on 111 of chrome and it is still required:

Screenshot 2023-03-15 at 5 42 15 PM

If the `-webkit-mask-image` is removed then I just get red boxes!

**Comment by CarlosNZ** [comment]
> I'm on 111 of chrome and it is still required:
> 
> If the `-webkit-mask-image` is removed then I just get red boxes!

😢 👍 @roxy-dao

**Review by CarlosNZ — APPROVED** [review]
Cool -- looks very nice :)
