### PR TITLE
1465 allow inventory adjsutment reason when counted quantity is 0

### LINKED ISSUE #1465: Stocktake adjustment reason not available when counted packs is set to 0
## What went wrong? 😲
When carrying out a stocktake the SAMES team have reported that they cannot add an adjustment reason when they set the counted stock to 0, for a line that has existing stock. This also then blocks the stocktake item from being saved.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to create new blank stock take
2. Add an item that has some stock on hand
3. Set the counted stock to 0
4. Observe that reason cannot be chosen and therefore item cannot be saved for stocktake

## Your environment 🌱
 - Version 1.1.8 Android

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1465

# 👩🏻‍💻 What does this PR do? 

Allows adjustment reason when counted quantity is zero (fixing `rowData.countedNumberOfPacks || rowData.snapshotNumberOfPacks` when countedNumberOfPacks is zero)
Using Adjustment enum type to handle adjustment, to simplify adjustment representation

Bonus: Fixes countedNumberOfPacks being wiped when it's set to 0

# 🧪 How has/should this change been tested? 

For adjustment reason not available when counted quantity is zero:
* Datafile with positive and negative inventory adjustment reasons set up
* Try setting number of packs to zero (in stocktake) when snapshot number of packs is not zero, should be able to set correct reason

For counted number of packs wiped when set to zero:
* Set number of packs to non zero value in stocktake
* Focus out of the input
* Focus back in the input and set number of packs to 0, it should not disappear

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const NonNegativeDecimalCell = <T extends RecordWithId>({
   max,
 }: CellProps<T> & { max?: number }): React.ReactElement<CellProps<T>> => {
   const [buffer, setBuffer] = useBufferState(
-    column.accessor({ rowData }) || ''
+    column.accessor({ rowData }) ?? ''
```
Comment (andreievg) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx:16]: Fixes 0 being set to '' see test in description

File: client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx [hunk 2]
```diff
@@ -13,34 +13,33 @@ import {
...
-  stockReduction,
-  isError,
-}) => {
+> = ({ value, width, onChange, autoFocus = false, adjustment, isError }) => {
   const { data, isLoading } =
     useInventoryAdjustmentReason.document.listAllActive();
-  const disabled = data?.totalCount === 0 || stockReduction === 0;
-  const isRequired = !disabled && stockReduction !== 0;
+  const isRequired = data?.totalCount !== 0;
+  const isDisable = adjustment === Adjustment.None || !isRequired;
```
Comment (andreievg) [inline client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:39]: I reshuffled this, using enum actually identified a problem, typescript complained since, i.e. [example](https://www.typescriptlang.org/play?#code/KYOwrgtgBAggzgUXNA3gKCpqAtYAnAewBoMsYAjAgN2F0JKygCFgAbAgdzoLQF800AYwIg4AFyiCAFsEEBrKAF4oACmEgAJgEsxWkQC4olAq2ABDEEShUzrMMEPJy+AJRKAfFHRZ14qADMtPD9ldW1dESgAHyjrW3slRWUABgBuUkkRPzhZEQ0lKABCQOCJADIyuLtgIqSoNIEsPGAxMDwQLxLxKxyw-n4hLIlpWTkAdR0pJEgCtTydPRBDY1MLKxtqw3hpiDdFT29MXwkuiVD5iI6YqoSk5W3kADpudJ8hqF68guKgvwqbmqFOoPSDPfAEdIZZqtdqdX5iHq5TT9AS+EzAR7sADmahk8hUYjw9isyRcLkGonRmIIOJG+MJxKgAEYyQIgA)

Comment (roxy-dao) [reply client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:39]: isDisabled

**Review by mark-prins — APPROVED** [review]
working nicely thanks.
I'd like to see `isDisable` changed - that's not a blocker though

**Comment by andreievg** [comment]
Thanks for review
