### PR TITLE
#1353 use numbers for measurements, update number inputs

### LINKED ISSUE #1353: Programs: something's wrong with data validation (encounter form)
## What went wrong? 😲
 

I entered a value in the `MUAC` field and delete it (I made a mistake, was meant to enter a value for the weight instead). 

I deleted it and now it's telling me something wrong: 

Screen Shot 2023-03-15 at 12 07 04 PM

closing and re-opening the modal does not seem to work

## Expected behaviour 🤔

- [ ] should not tell that there is an incorrect format if field is empty

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Dispensary > Patients > Encounters tab > HIV Care Encounter > Physical Exam section

Enter a value and delete it. 

## Your environment 🌱
 - Version 1.1.4
 - [Platform](https://demo-open.msupply.org:88/dispensary/patients?sort=code)

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #1353

# 👩🏻‍💻 What does this PR do? 
 

The actual change as per the issue is just a small tweak to the HIV Care Encounter schema. 

However, I noticed in the process of doing this that number inputs weren't clearable -- i.e. if you select the value and push "delete", it gets set to `0`, not an empty input. For non-required inputs, you should always be able to clear them, just like text inputs, and we don't want users putting `0` if the value is not actually zero. So I've updated the number inputs to reset their value back to `undefined` when cleared.

The side-effect of this is that there are a lot of places these number inputs are used, and they all required some kind of tweak -- I've either set them to allow `undefined` values, or adjusted their functionality to only update the value if the input is not `undefined`, on a case-by-case basis.

# 🧪 How has/should this change been tested? 

Checked all the instances where the changed inputs are used and checked the UI functionality still makes sense.

## 💌 Any notes for the reviewer?

Maybe check if there's any cases where we *shouldn't* let the input be clearable?

### CODE REVIEW

File: client/packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx [hunk 1]
```diff
@@ -20,7 +20,8 @@ export const getEditableQuantityColumn = <
     const [value, setValue] = useState(quantity);
     const [error, setError] = useState(false);
 
-    const tryUpdateValue = (value: number) => {
+    const tryUpdateValue = (value: number | undefined) => {
+      if (value === undefined) return;
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx:24]: Don't change the value at all if the user tries to clear it -- seems appropriate for a table input (though this one is not actually used anywhere)

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx [hunk 2]
```diff
@@ -27,6 +27,7 @@ export const PositiveNumberInputCell = <T extends RecordWithId>({
       error={isError}
       value={buffer}
       onChange={newValue => {
+        if (newValue === undefined) return;
```
Comment (CarlosNZ) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx:30]: Again, seems appropriate to prevent clearing the value, as it's used in a table, and it starts with a value from the database (and could be 0).

File: client/packages/host/src/Admin/SyncSettings.tsx [hunk 3]
```diff
@@ -97,16 +97,18 @@ const SyncSettingsForm = ({
...
+                setSettings(
+                  'intervalSeconds',
+                  NumUtils.constrain(
+                    Math.round(seconds),
+                    1,
+                    Number.MAX_SAFE_INTEGER
+                  )
+                );
+              }
+            }}
```
Comment (CarlosNZ) [inline client/packages/host/src/Admin/SyncSettings.tsx:111]: This page doesn't seem to be in use. But again, based on context, it doesn't seem like an empty value should be allowed.

**Comment by clemens-msupply** [comment]
Just noticed that you can't set a value to 0 any more, e.g. for "Pill Count (at visit start)", it has a minimum of 0 but this should include 0 according to the JSON schema (https://json-schema.org/understanding-json-schema/reference/numeric.html)...

File: client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx [hunk 4]
```diff
@@ -31,7 +31,11 @@ export const PositiveNumberInput = React.forwardRef(
           sx: { ...sx, '& .MuiInput-input': { textAlign: 'right' } },
         }}
         onChange={value =>
-          onChange(NumUtils.constrain(value, Math.max(0, min), max))
+          onChange(
+            value !== undefined
+              ? NumUtils.constrain(value, Math.max(1, min), max)
```
Comment (clemens-msupply) [inline client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx:36]: this should be `max(0, min)`?

btw. there is the idea around to remove this PostitiveNumberInput and just have a normal NumberInput where you can set the correct range... For example, to have a range [-5,5]

Comment (CarlosNZ) [reply client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx:36]: The existing comment for PositiveNumberInput is `// where Positive is n >=1` but the behaviour wasn't consistent with this, so I fixed it. See storybook for the variety of number components and the ranges allowed:

Screenshot 2023-03-29 at 11 29 55 AM

> there is the idea around to remove this PostitiveNumberInput and just have a normal NumberInput where you can set the correct range... For example, to have a range [-5,5]

I agree that this would be better, I did think there was way too many number components with only slight differences ("Non-negative" vs "Positive"? 😳)

Yes, a single component combining these four with just a range prop seems much nicer.
Screenshot 2023-03-29 at 11 33 29 AM

Shall I make an issue for that?

**Comment by CarlosNZ** [comment]
> Just noticed that you can't set a value to 0 any more, e.g. for "Pill Count (at visit start)", it has a minimum of 0 but this should include 0 according to the JSON schema (https://json-schema.org/understanding-json-schema/reference/numeric.html)...

Yup, that's because the JSONForms Number component is using `<PositiveNumberInput>`, which is supposed to have a minimum of 1 (as per above comment). If I change it to allow `0`, then it'll be the same as the "NonNegativeNumberInput".

Probably best if I just change it to the general Numeric component and let the min/max do its thing (until we refactor them all into a single component, as your last comment)

File: client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx (hunk 4 above)
Comment (CarlosNZ) [reply client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx:36]: > but the behaviour wasn't consistent with this, so I fixed it

> Just noticed that you can't set a value to 0 any more, e.g. for "Pill Count (at visit start)", it has a minimum of 0 but this should include 0 according to the JSON schema (https://json-schema.org/understanding-json-schema/reference/numeric.html)...

Oh, I see, even though the component said it is supposed to be`where Positive is n >=1`, the `min` property was allowing you to set it to `0`, which my change removed. It essentially makes it the same as the "NonNegativeNumberInput" when you have `min=0`,  hence my confusion.

I'll revert it now, but yes, we really should tidy these number components up, it's a bit of a shambles.

Comment (CarlosNZ) [reply client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx]: b58c00dd1

Comment (CarlosNZ) [reply client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx]: > Shall I make an issue for that?

Done: #1440

**Comment by CarlosNZ** [comment]
> Probably best if I just change it to the general Numeric component and let the min/max do its thing (until we refactor them all into a single component, as your last comment)

Actually, I just reverted my tweak to the PositiveNumberInput as per [this comment](https://github.com/openmsupply/open-msupply/pull/1433#issuecomment-1487699408)

**Comment by mark-prins** [comment]
I haven't run feature branch for a while.. doing so with postgres will give you this:

Screenshot 2023-03-29 at 2 24 04 PM

Not part of this issue, still, will need looking at.. as far as I can tell the sorting by `context` is the issue (server/src/db_diesel/document_registry.rs:85) Changing to `apply_sort` instead of `apply_sort_no_case` will fix.

File: server/service/src/sync/program_schemas/hiv_care_encounter.json [hunk 5]
```diff
@@ -398,17 +402,15 @@
...
+              "type": "number"
             },
             "midUpperArmCircumference": {
               "description": "284473002\tMid upper arm circumference (MUAC) [cm]",
-              "examples": ["23.0", "21.4"],
-              "pattern": "^\\d+\\.\\d+$",
-              "title": "MUAC in cm",
-              "type": "string"
+              "minimum": 0,
+              "title": "MUAC in cm]",
```
Comment (mark-prins) [inline server/service/src/sync/program_schemas/hiv_care_encounter.json:412]: image

We've gained a `]`

**Review by mark-prins — APPROVED** [review]
Fine by me!
It does mean a lot more checking for the consumer - and I wonder when the NumericInput is refactored / consolidated - it might make sense to have a prop which allows the undefined value. In which case the `onChange` event becomes easier to use as it will always return a valid number

File: client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx [hunk 6]
```diff
@@ -206,8 +208,10 @@ const UIComponent = (props: ControlProps) => {
               sx: { '& .MuiInput-input': { textAlign: 'right' } },
             }}
             onChange={value => {
-              setLocalData(value);
-              onChange(value);
+              if (value !== undefined) {
+                setLocalData(value);
+                onChange(value);
+              }
```
[the remark this answers is not in the document]
Comment (clemens-msupply) [reply client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx:214]: I committed a change for handling the undefined case, works fine as far as I have tested it!

**Review by clemens-msupply — APPROVED** [review]
Nice change thank you! works very well

File: client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx (hunk 4 above)
Comment (clemens-msupply) [reply client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx]: thanks!

**Comment by clemens-msupply** [comment]
> `apply_sort_no_case`

I will look into it now if @CarlosNZ wasn't quicker

File: server/service/src/sync/program_schemas/hiv_care_encounter.json (hunk 5 above)
Comment (CarlosNZ) [reply server/service/src/sync/program_schemas/hiv_care_encounter.json]: Eek :) f104bc5df

**Comment by CarlosNZ** [comment]
> it might make sense to have a prop which allows the undefined value. In which case the `onChange` event becomes easier to use as it will always return a valid number

Yes, was thinking something along those lines. 👍
