### PR TITLE
Fix requested quantity display in Firefox

### LINKED ISSUE #2145: Browser-specific bug: Requested quantity bar chart not showing up only in Firefox
## What went wrong? 😲
 

May be other places too, but I noticed in Requisitions -> Detail View -> Item Modal

The "Requested quantity" bar chart is not showing up in Firefox but is fine in Chrome (and Safari). This is on Mac, haven't tried other OSes.

### Firefox view:

Screenshot 2023-08-29 at 3 56 22 PM

### Chrome view (of the exact same item)

Screenshot 2023-08-29 at 3 56 28 PM

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #2145

# 👩🏻‍💻 What does this PR do? 
 

Quick fix -- seems to work fine after removing the `height: "100%"` props from ModalTabs. Not sure if this might cause problems somewhere else -- can you think of why it might have been necessary @mark-prins 

# 🧪 How has/should this change been tested? 

Tested on Firefox and Chrome, in Requisitions -> requisition -> item line modal.

## 💌 Any notes for the reviewer?

Please see if you can think of any potential regressions.

### CODE REVIEW

File: client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx [hunk 1]
```diff
@@ -44,33 +44,31 @@ export const ResponseStoreStats: React.FC<ResponseStoreStatsProps> = ({
           paddingBottom: 2,
         }}
       >
-        <>
```
Comment (CarlosNZ) [inline client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx:47]: Not directly related to issue, but there was some unnecessary fragment blocks in here.

**Review by mark-prins — APPROVED** [review]
👍  the change came in with [this commit](https://github.com/openmsupply/open-msupply/commit/5be940c681d53a0a82a8b7b2468ae7b0fd073d3d) - it's not clear from the commit why the height prop was required.

is working fine for me in ff & chrome.

Checked the ResponseLineEdit, StockLineEditModal, Patient enrolment and Create program requisition modal - the last one of which I'm not happy with, as modal contents isn't full height and the action button is in a strange place; all other modal buttons are at the bottom. For this one, I don't think the modal should be 80% of window height and the button should be at the bottom.

image

**Comment by CarlosNZ** [comment]
> For this one, I don't think the modal should be 80% of window height and the button should be at the bottom.

Sorry, I'm not quite clear -- are you suggesting we change this modal layout? As far as I can tell, it hasn't changed in this PR.

**Comment by mark-prins** [comment]
no, sorry. just an offroad grumble. I hadn't noticed that modal being non-standard before.. ignore me!
