### PR TITLE
Incorrect number in stocktake creation display

### LINKED ISSUE #1300: When creating a stocktake from a masterlist, it shows the wrong number of items by the masterlist name
## What went wrong? 😲
 

The text showing the number of items in a masterlist (when you are first creating a stocktake) seem wrong. This one, for example, says 0 - it has 4 items on the central server, and adds 4 lines. 

image

We had other masterlists that had ~140 items, and showed as 43 items. It also had that same error that when you go to delete all lines, it said "Deleting 100 lines" each time. 

## Expected behaviour 🤔
* It should show the correct number items in the masterlist 
* When you select all lines, and try to delete, the alert should show the correct number of items which will be deleted 
* Nice to have: it would be useful if the stocktake comment had details on the type of stocktake it is (eg. Stocktake A, for Masterlist B) 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Click to create a stocktake
2. Click on the mastelist ddl 
3. Compare number of items to those in the central server 

## Your environment 🌱
 - Version [1.1.4]
 - Platform [tablet]

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1300 

# 👩🏻‍💻 What does this PR do? 
 
The default pagination limit causes issues again.
Have removed the pagination from the method fetching master list lines, and checked all usages of this method. the `query_by_filter` fn is only used when adding items from master lists, so this change will fix a few issues.

Have also added the comment generation, done in the f/e so that it is translatable.

Checked the delete, which now shows the correct count.
**Counts**
Screenshot 2023-03-09 at 12 53 06 PM

Screenshot 2023-03-09 at 12 53 54 PM

**Delete**
Screenshot 2023-03-09 at 12 54 59 PM

**Comments**
Screenshot 2023-03-09 at 1 10 30 PM

Screenshot 2023-03-09 at 1 06 58 PM

Bonus!
Noticed that if there are no locations, you see this:

Screenshot 2023-03-09 at 12 55 58 PM

Which I've upgraded to this:

Screenshot 2023-03-09 at 12 59 51 PM

# 🧪 How has/should this change been tested? 

As per the issue:
- create a stocktake, noting the numbers next to the master list names.
- Try to create from master list, and from location - check the comments.
- Delete lines from a list, when there are more than 100 lines

## 💌 Any notes for the reviewer?

I never use this section. Does anyone?

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

**Comment by andreievg** [comment]
> The default pagination limit causes issues again.

Example in the issue had `0` but 4 was added..

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx [hunk 1]
```diff
@@ -49,6 +49,27 @@ export const CreateStocktakeButton: React.FC<{
   const [createStocktakeArgs, setCreateStocktakeArgs] =
     useState<CreateStocktakeArgs>(DEFAULT_ARGS);
 
+  const generateComment = () => {
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:52]: Kind of feel like this is back end task (master list name or location name is straight away available). Also you can add items after stocktake was created, would this confuse people (having comment that it was created form certain master list or location and but having items that are not in the master list or location) ?

Sorry not asking for a change, but since it's a new addition, wanted to review it

**Review by andreievg — APPROVED** [review]
> Example in the issue had 0 but 4 was added..

I can see now, the graphql loader is restricted to 100 items, if there are multiple master list, it would only grab first 100 items. Setting very high default pagination wouldn't work.

**Comment by andreievg** [comment]
🙏 for changes

**Comment by mark-prins** [comment]
> > Example in the issue had 0 but 4 was added..
> 
> I can see now, the graphql loader is restricted to 100 items, if there are multiple master list, it would only grab first 100 items. Setting very high default pagination wouldn't work.

yeah, it was a pretty neat bug. the number of lines added up to 100 and were just shared out among the available master lists

File: client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx:52]: I'm on the fence - was thinking it should be a b/e task and now rather like having the comment template in the f/e because we can translate it.

and I think its ok that the comment says 'created from master list x'  and then you have some items added later. Ideally the log would show that items have been added.. but that can come later! ( it doesn't currently add log entries for changes like that )
