### PR TITLE
453 fix enrolment query

### LINKED ISSUE #453: Filter program enrolment by patient id

### PR DESCRIPTION
**Pull request by clemens-msupply**
Closes #453

### CODE REVIEW

File: client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx [hunk 1]
```diff
@@ -73,7 +74,11 @@ const ProgramListComponent: FC = () => {
         setDocumentName(row.document.name);
         setCurrent(PatientModal.Program);
       }}
-      noDataElement={<NothingHere />}
+      noDataElement={
+        <Box width={'100%'} paddingTop="100">
+          <NothingHere />
+        </Box>
+      }
```
Comment (clemens-msupply) [inline client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx:81]: Is there a better way to do this? The Noting Here box was sticking to the top and under the drop shadow of the tab panel...

Comment (mark-prins) [reply client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx:81]: yes - adding `height: '100%',` to the `StyledTabContainer` in the `PatientTab` will allow the grandparent to be full height, which allows the flex element (NothingHere) to be vertically positioned correctly.

File: client/packages/system/src/Patient/DetailView/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts [hunk 2]
```diff
@@ -1,14 +1,21 @@
...
+  useUrlQueryParams,
+} from '@openmsupply-client/common';
 import { useProgramEnrolmentApi } from '../utils/useProgramEnrolmentApi';
 
 export const useProgramEnrolments = () => {
   const api = useProgramEnrolmentApi();
   const { queryParams } = useUrlQueryParams({
     initialSort: { key: 'type', dir: 'asc' },
   });
+  const { patientId } = useParams();
```
Comment (mark-prins) [inline client/packages/system/src/Patient/DetailView/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts:13]: Since there is already a hook defined to do this:
```suggestion
  const patientId = usePatient.utils.id();
```

after adding in 

```
import { usePatient } from '../../../../../api';
```

**Review by mark-prins — APPROVED** [review]
👍  query change looks good ( though I'd suggest using the `usePatient` hook )

have a suggestion for the `NothingHere` layout too

File: client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx (hunk 1 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx]: Thanks that works better!

File: client/packages/system/src/Patient/DetailView/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts (hunk 2 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/DetailView/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts]: thanks done
