### PR TITLE
179 document deletion

### LINKED ISSUE #179: Document deletion
User must be able to mark document as (soft) deleted, e.g. when accidentally adding a document for the wrong patient.

Option 1.
- Add a status field like `"Active" | "Deleted" | ...` to the document to mark a document as deleted.
- The deleted document only points to its parent but doesn't need to contain data
- To un-delete a document just add a new document with status "Active" having the deleted document as parent.

~~Option 2: manage deletion in a separate table. Sync would need an extra mechanism to sync this table to multiple sites though.~~

Question: Also add a comment field for why a doc has been deleted?

- [x] add `status` field to the document table (`repository/src/db_diesel/document.rs`) possible values are "Active" | "Deleted"
- [x] add status to related structs, e.g. Document and RawDocument
- [x] fix existing code using status = "Active"
- [x] add service method to delete a Document: a deleted document doesn't has data and status is "Deleted" (parents are still set)
- [x] add service method to undelete a document: fetch the parent of the deleted document and us its data to create new version which has status "Active" and the parent is the deleted document
- [x] service tests
- [x] add graphql endpoint to delete a document

2022-08-09_document_deletetion drawio

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #179 

Generic deletion and undelete of docs

### CODE REVIEW

File: server/service/src/document/document_service.rs [hunk 1]
```diff
@@ -30,6 +31,45 @@ impl From<RepositoryError> for DocumentHistoryError {
...
+
+#[derive(Clone, Debug, Default, PartialEq)]
+pub struct DocumentUndelete {
+    pub id: String,
+    pub parent: String,
+}
+
+#[derive(Debug, PartialEq)]
+pub enum DocumentUndeleteError {
+    CannotUndeleteDocument,
```
Comment (roxy-dao) [inline server/service/src/document/document_service.rs:62]: Could pass in a String saying document hasn't been deleted? 🤔

File: server/service/src/document/document_service.rs [hunk 2]
```diff
@@ -362,8 +560,57 @@ mod document_service_test {
...
+                DocumentDelete {
+                    id: document_a().id,
+                    patient_id: "patient1".to_string(),
+                    parent: "document_a".to_string(),
+                    comment: Some("Testing deletion".to_string()),
+                },
+            )
+            .unwrap();
+        let document = service
+            .get_document(&context, "patients/patient1/deleted")
```
Comment (clemens-msupply) [inline server/service/src/document/document_service.rs:593]: Use the &document_a().name here as well

File: server/service/src/document/document_service.rs [hunk 3]
```diff
@@ -362,8 +560,57 @@ mod document_service_test {
...
+                    parent: document_a().id,
+                },
+            )
+            .unwrap();
+        let undeleted_document = service
+            .get_document(&context, &document_a().name)
+            .unwrap()
+            .unwrap();
+        assert_eq!(undeleted_document.status, DocumentStatus::Active);
+        assert_eq!(undeleted_document.data, document_a().data);
```
Comment (clemens-msupply) [inline server/service/src/document/document_service.rs:614]: You could test for the failure cases as well

File: server/service/src/document/document_service.rs [hunk 4]
```diff
@@ -147,12 +306,37 @@ fn insert_document(
...
+}
+
+fn undelete_document(
+    connection: &StorageConnection,
+    doc: RawDocument,
+) -> Result<Document, DocumentUndeleteError> {
+    let doc = doc
+        .finalise()
+        .map_err(|err| DocumentUndeleteError::InternalError(err))?;
+    let repo = DocumentRepository::new(connection);
```
Comment (clemens-msupply) [inline server/service/src/document/document_service.rs:328]: You could move the finalise into the generate method and inline the rest, think this would be more in line with how we do it elsewhere

**Review by clemens-msupply — COMMENTED** [review]
When updating a document, please add check that status is active(?)

File: server/service/src/document/document_service.rs (hunk 1 above)
Comment (roxy-dao) [reply server/service/src/document/document_service.rs:62]: Are there any more errors you want to include for DocumentDelete or DocumentUndelete?

Comment (clemens-msupply) [reply server/service/src/document/document_service.rs:62]: Maybe DocumentDoesNotExists if the specified id is invalid

File: server/service/src/document/document_service.rs [hunk 5]
```diff
@@ -134,6 +209,90 @@ fn validate_parents(
...
+    Ok(doc)
+}
+
+fn generate_deleted_document(
+    input: DocumentDelete,
+    current_document: Document,
+    user_id: &str,
+) -> Result<RawDocument, DocumentDeleteError> {
+    Ok(RawDocument {
+        name: patient_deleted_doc_name(&input.patient_id),
```
[the remark this answers is not in the document]
Comment (clemens-msupply) [reply server/service/src/document/document_service.rs:254]: Yes name stays the same and the parent of the deleted doc is input.id

File: server/service/src/document/document_service.rs [hunk 6]
```diff
@@ -134,6 +216,100 @@ fn validate_parents(
...
+        Some(parent) => parent,
+        None => "",
+    };
+
+    let deleted_document_parent =
+        match DocumentRepository::new(connection).find_one_by_id(&parent.clone()) {
+            Ok(Some(doc)) => doc,
+            Ok(None) => return Err(DocumentUndeleteError::ParentDoesNotExist),
+            Err(err) => return Err(DocumentUndeleteError::DatabaseError(err)),
+        };
```
Comment (clemens-msupply) [inline server/service/src/document/document_service.rs:294]: I think elsewhere we would put this into the validate method, i.e. verify that the parent exists and then return the current_document and the original_document from validate()...

File: server/service/src/document/document_service.rs [hunk 7]
```diff
@@ -362,8 +553,77 @@ mod document_service_test {
...
+                    comment: Some("Testing deletion".to_string()),
+                },
+            )
+            .unwrap();
+        let document = service
+            .get_document(&context, &document_a().name)
+            .unwrap()
+            .unwrap();
+        assert_eq!(document.status, DocumentStatus::Deleted);
+        assert_eq!(document.data, serde_json::Value::Null);
```
Comment (clemens-msupply) [inline server/service/src/document/document_service.rs:603]: try to delete the document again and expect the "already deleted" error...

**Review by clemens-msupply — APPROVED** [review]
Thanks looks great! just one test case missing...

File: server/service/src/document/document_service.rs (hunk 6 above)
Comment (roxy-dao) [reply server/service/src/document/document_service.rs]: I don't think it needs to return current document since validation is already used on the deleted document and only the id from the deleted document is needed for generating undeleted document 
[f2750ed](https://github.com/openmsupply/open-msupply/pull/521/commits/f2750edacd6b02fecba686114219adced5a86239)
