### PR TITLE
1819 [Deployment Feedback] Dashboard page (welcome screen) doesn't update 

### LINKED ISSUE #1819: [Deployment Feedback] Dashboard page (welcome screen) doesn't update
## What went wrong? 😲

During training, a user noticed that they had 3 expired batches in their dashboard. They removed the expired stock with a stocktake, checked that no late expiry date appears in but when they went to check their dashboards, 3 expired batches were still showing instead of 0. 
Facility : POLYCLINIQUE YONIS TOUSSAINT - LABO (live Djibouti server)

## Expected behaviour 🤔

If expired batches are removed and no longer appear in 'View stock'. The dashboard should show 0 expired items in stock. 

## How to Reproduce 🔨

1. Add expired items in stock with a stocktake
2. Have a look at the dashboard : it should show the number of expired batches
3. Remove expired items with a stocktake (choose reason _produits périmés_)
4. Have a look at the dashboard : See error

## Your environment 🌱

 - Version: Open mSupply v1.1.13 (Before May 22nd release)
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [X] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

@richardmoizeau

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1819 

# 👩🏻‍💻 What does this PR do? 
Count expired stocks also counted stock lines with 0 number of packs. Have added check to filter out stock lines with 0 available number of packs, and also added a test.

# 🧪 How has/should this change been tested? 
- Run tests
OR
- Use stocktake to create some expired stock.
- Go to dashboard and see expired count. 
- Go back to stocktake and put expired stock line's counted packs to 0.
- Go back to dashboard and see new expired count.

### CODE REVIEW

File: server/service/src/dashboard/stock_expiry_count.rs [hunk 1]
```diff
@@ -35,9 +35,92 @@ impl StockExpiryCountServiceTrait for StockExpiryServiceCount {
                         before_or_equal_to: Some(date_time),
                         after_or_equal_to: None,
                     })
-                    .store_id(EqualFilter::equal_to(&store_id)),
+                    .store_id(EqualFilter::equal_to(&store_id))
+                    .is_available(true),
```
Comment (roxy-dao) [inline server/service/src/dashboard/stock_expiry_count.rs:39]: Assume we only want to see if the available packs is expired since other packs would have been allocated already?

Comment (mark-prins) [reply server/service/src/dashboard/stock_expiry_count.rs:39]: the name mislead me - I was going to say that we don't want `is_available` but instead we want to check if there is some stock, i.e. `available_number_of_packs` > 0

turns out, that's what `is_available` does. so, thanks. that's all good.

**Review by mark-prins — APPROVED** [review]
👍  thanks - that's working nicely
