### PR TITLE
#1382 location modal window improvement

### LINKED ISSUE #1382: Location modal looks a bit weird
## What went wrong? 😲

Screen Shot 2023-03-20 at 11 31 54 AM

## Expected behaviour 🤔

Screen Shot 2023-03-20 at 11 34 41 AM

### PR DESCRIPTION
**Pull request by bijaySussol**
Fixes #1382 

# 👩🏻‍💻 What does this PR do? 

Location modal feel

Screen Shot 2023-04-19 at 12 28 55 PM

### CODE REVIEW

File: client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx [hunk 1]
```diff
@@ -123,15 +123,20 @@ export const LocationEditModal: FC<LocationEditModalProps> = ({
...
       {!isLoading ? (
-        <Grid flexDirection="column" display="flex" gap={2}>
-          <BasicTextInput
+        <Grid
+          flexDirection="column"
+          display="flex"
+          gap={2}
+          alignItems="flex-start"
+        >
+          <BasicTextInput sx={{width: 450}}
```
Comment (mark-prins) [inline client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx:132]: I'd prefer to avoid having a fixed number value for the width - though it requires a bit of fixing of the `BasicTextInput` to make that work 🙄 

Would you mind changing to `fullWidth` instead of the style - and then you can remove the `alignItems` from the `Grid` too.

```suggestion
        <Grid flexDirection="column" display="flex" gap={2}>
          <BasicTextInput
            fullWidth
```

You just have to add this to `BasicTextInput`

```
export const BasicTextInput: FC<BasicTextInputProps> = React.forwardRef(
  ({ sx, InputProps, error, required, ...props }, ref) => (
    <Box
      display="flex"
      justifyContent="flex-end"
      alignItems="center"
      width={props.fullWidth ? '100%' : undefined}
    >
```

that `width` prop needs to be added 😉

**Review by mark-prins — CHANGES_REQUESTED** [review]
I have a request to change please 🙏

File: client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx (hunk 1 above)
Comment (bijaySussol) [reply client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx]: Thank you @mark-prins , Great tips !
Done by this: [a7449b0](https://github.com/openmsupply/open-msupply/pull/1574/commits/a7449b00ccbeda59ae11e0e7408979e695aa44f7)

**Review by mark-prins — APPROVED** [review]
👍  thanks Bijay! looking good
