### PR TITLE
Fix regex utils ( new stocktake :: item search input )

### LINKED ISSUE #773: Stocktake filter regex
- Create a stocktake
- Past in some text with brackets in it
- delete the second bracket

There's an issue with the escaping of text entered into the filter which causes problems with the regular expression parsing.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #773 
 
A nice easy one to review 😉

### CODE REVIEW

File: client/packages/common/src/utils/regex/RegexUtils.tsx [hunk 1]
```diff
@@ -41,7 +41,10 @@ export const RegexUtils = {
     keys?: Array<keyof T>
   ) {
     return (keys ?? (Object.keys(object) as Array<keyof T>)).some(key =>
-      RegexUtils.includes(substring, String(object[key]))
+      RegexUtils.includes(
+        this.escapeChars(substring) ?? '',
```
Comment (clemens-msupply) [inline client/packages/common/src/utils/regex/RegexUtils.tsx:45]: The `?? ''` is just because `escapeChars` returns `string | undefined` right? Would it make sense and define it like:

`escapeChars: (regexString: string): string => {...}`

And then handle the undefined cases on the caller site of `escapeChars`. This avoids this problem here where you have a defined substring and `escapeChars` unnecessarily converts it to undefined.

**Review by clemens-msupply — APPROVED** [review]
Looks good! see comment about escapeChars signature...

File: client/packages/common/src/utils/regex/RegexUtils.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/common/src/utils/regex/RegexUtils.tsx:45]: have popped that in 😉
