### PR TITLE
Remove pagination from invoice and requisition lines

### LINKED ISSUE #1369: Not all Master list items seems to be included or visible/reachable on internal order or in the catalogue of that master list
## What went wrong? 😲
 
When adding items using the "Add from master list" button  on a internal order. Not all the items seems to be included or visible/reachable.

The master list I have been using is shared by both the Requesting and Supplier stores. I was looking for 06_4956 Acetylcysteine powder 200mg sachet. I can see this item in the Item list in omsupply

When I do the filtering in the internal order
image

I can see it when adding a new item
image

Master list on omSupply
The are in alphabetical order so should be the first one on top

image

Same Master list in mSupply
image

## Expected behaviour 🤔
I think all items of the master list should be displayed or accessible in some way

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Install omSupply 1.1.5 and linked it to the Alain Abode site of the Timer demo cloud server (available in teamviewer) .
1. After initalisation
2. Click on 'Replenishment > Internal orders'
3. Create a new internal order and press the Add from master list button. Select the SAMES MASTER LIST
4. Try to find 06_4956 Acetylcysteine powder 200mg sachet. See error, it is not there.

## Your environment 🌱
 - Version [e.g. 1.1.5]
 - Platform [e.g. tablet]

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1369 

# 👩🏻‍💻 What does this PR do? 
 
The title is a plot-spoiler for this one.
In the issue raised, the problem is that the requisition has > 100 lines on it.
The query `requisition_by_number` is using the requisition_line loader which, when querying, uses the default pagination limit of 100 items. End result is that the requisition is returned, with only 100 lines on it. When checking the database, the requisition has > 100 lines associated.

The requisition fix applies to both internal orders and customer requisitions.

Bonus! the invoices have the same issue - so have fixed also for inbound & outbound shipments.
Bonus! noticed that outbound shipment detail view had a double y-axis scrollbar. Have removed

# 🧪 How has/should this change been tested? 

As per the issue. 
You can replicate by creating a masterlist with > 100 items. Create an internal order using said list and check the result.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx [hunk 1]
```diff
@@ -112,22 +112,24 @@ export const ContentAreaComponent: FC<ContentAreaProps> = ({
...
-        noDataElement={
-          <NothingHere
-            body={t('error.no-outbound-items')}
-            onCreate={isDisabled ? undefined : () => onAddItem()}
-            buttonText={t('button.add-item')}
-          />
-        }
-        isRowAnimated={true}
-      />
+      <Box flex={1} style={{ overflowY: 'auto' }}>
```
Comment (mark-prins) [inline client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx:115]: using flex to get the container to expand to fill the vertical space, adding `overflowY` to get the windowing working on the datatable and adding this extra container so that the `100%` height on the datatable is of this container not the one which also contains the group by row.

File: client/packages/common/src/authentication/AuthContext.tsx [hunk 2]
```diff
@@ -80,7 +81,19 @@ export const setAuthCookie = (cookie: AuthCookie) => {
   Cookies.set('auth', JSON.stringify(authCookie), { expires });
 };
 
-const AuthContext = createContext<AuthControl>({} as any);
+const userHasPermission = (_permission: UserPermission) => false;
```
Comment (andreievg) [inline client/packages/common/src/authentication/AuthContext.tsx:84]: Is this meant to be in this PR ?

File: server/service/src/requisition_line/query.rs [hunk 3]
```diff
@@ -1,24 +1,20 @@
...
     RepositoryError, RequisitionLine, RequisitionLineFilter, RequisitionLineRepository,
 };
 
-use crate::{
-    get_default_pagination, i64_to_u32, service_provider::ServiceContext, ListError, ListResult,
-};
+use crate::{i64_to_u32, service_provider::ServiceContext, ListError, ListResult};
 
 pub const MAX_LIMIT: u32 = 2000;
 pub const MIN_LIMIT: u32 = 1;
```
Comment (andreievg) [inline server/service/src/requisition_line/query.rs:9]: doesn't look like max_limit is needed

Comment (mark-prins) [reply server/service/src/requisition_line/query.rs:9]: thanks - have taken out.

File: client/packages/common/src/authentication/AuthContext.tsx (hunk 2 above)
Comment (mark-prins) [reply client/packages/common/src/authentication/AuthContext.tsx:84]: I had to add the dummy `authControl` for the f/e tests to run.  
I've changed to an inline constructor to make the dummy more consistent.

**Comment by mark-prins** [comment]
🙏  thanks for review! I have made a couple of minor changes.

> How do I test ... outbound shipment detail view had a double y-axis scrollbar:

just create an outbound shipment and add more lines than the screen can show. that should be enough. I can see it on the demo server:

image

( you do need to scroll all the way to the right though )

> And AuthContext changes ?

that was running tests : `yarn test` - one of them the AuthContext is used  to check permissions in the AppDrawer

> Do we need to also do this for stocktake_lines ?

Good point!
have checked the stocktake_lines and that one is using `Pagination::all()` rather than `::new()` so I guess we've hit that one already?

**Review by andreievg — APPROVED** [review]
Thanks for explanations.

Extra scroll bar definitely gone 👍, there is still a little glitch, maybe we can do that later (I had the column selector disappear on me with this one):

table glitch
