### PR TITLE
Focus the batch input of the first row in a stocktake

### LINKED ISSUE #1498: Focus stays on "OK & Next" in stocktake item input modal
## What went wrong? 😲

When I press OK & Next while editing items in a stock take, the focus remains on OK & Next. I have to tab a whole lot to get back to 
image

## Expected behaviour 🤔

The focus should move to the top left most editable field of the list of lines. I expect this affects many input modals, if the fix needs too much work to get them all, make more issues/PRs I think.

THAT SAID, maybe someone likes this way. Makes it easier when just checking through many items. I'd argue that you can do that using the mouse. When doing data entry, it's nice to not have to leave the keyboard and that's the workflow that should be optimised in my opinion.

## How to Reproduce 🔨

1. Create stocktake with master list
2. Click on first row
3. Enter values pressing tab to cycle through cells
4. tab to OK & Next
5. Press enter
6. Focus stays on OK & Next

## Your environment 🌱
 - Version develop 1.1.10
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### Tangent

image

I tried cmd+K to see if there were any handy shortcuts for OK & Next, but it's behind the dialog. Way out of scope of this bug report though. I'd like there to be a short cut for each of the dialog buttons and to be able to cmd+K.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1498

# 👩🏻‍💻 What does this PR do? 
 
The default behaviour of the `TextInputCell` is to auto focus if this is the first cell in the first row.
However.. the stocktake input modal has a checkbox in the first column!

Have added an option for the cell to specify whether it is auto focussed or not, and in the case of the stocktake modal, have set this for the first row, second column.

# 🧪 How has/should this change been tested? 

Add a stocktake which has multiple lines:

- On clicking on the first line, the batch input of the first row should have focus.
- On clicking OK & Next, the batch input of the first row should have focus.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 1]
```diff
@@ -60,7 +72,7 @@ const getBatchColumn = (
       width: 150,
       maxWidth: 150,
       maxLength: 50,
-      Cell: TextInputCell,
+      Cell: StocktakeTextInputCell,
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:75]: Did we need to create StocktakeTextInputCell ? Don't we just set isAutoFocus in column definition here ? (if batch column is moved, it won't be auto focused anymore, ¯\_(ツ)_/¯ I am not sure what the expected behaviour should be for this, still keep it on batch or always on the first editable column)

**Review by andreievg — APPROVED** [review]
Thanks @mark-prins, changes look good and it seem to be working

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:75]: I created the component because it's neater than trying to do it inline here..
Setting `isAutoFocus` to true for all batch input cells would mean the last row has focus and not the first, what you say about the column was helpful though! I've changed it so that this is a batch input cell only, and is only autoFocus on the first row

**Comment by mark-prins** [comment]
Fix in 412cc34ee
