### PR TITLE
1298 android url handling

### LINKED ISSUE #1298: Some actions open a browser window when they should not
## What went wrong? 😲
 

We noticed this in two particular circumstances: 
* In the admin window, when you change language to Tetum, it opens up a browser window
* When you try and create a customer shipment from a requisition, it opens a browser window: 

https://user-images.githubusercontent.com/29744386/223608581-181bb79c-6d33-4602-9a0c-bf22821922cd.mp4

## Expected behaviour 🤔
It should stay on the app 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Admin 
2. Change language to Tetum 
3. See error

## Your environment 🌱
 - Version [1.1.4]
 - Platform [tablet]

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1298 

# 👩🏻‍💻 What does this PR do? 
 
The issue is a strange behaviour in the webView - refreshing a page ( either with `window.location.reload()` or `navigate(0)` ) will reload *and* open the URL in a browser.

The change here is to overload the URL handling in the webView and if the URL is local, do not open in a browser.

# 🧪 How has/should this change been tested? 

You'll need an android build.
Try the two actions in the issue, as well as a baseline external URL handling one:

- Change language (either the footer, or the admin > language selection)
- Create an outbound shipment from a customer requisition
- Open the docs: this should open in a browser

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/common/src/ui/icons/MSupplyGuy.tsx [hunk 1]
```diff
@@ -73,9 +73,7 @@ export const AnimatedMSupplyGuy = styled(SvgGuy)(({ theme, size }) => {
     }),
     '&:hover': {
       animation:
-        size === 'large'
-          ? `${spin} 1s infinite ease`
-          : `${otherSpin} 1s infinite ease`,
+        size === 'large' ? `${spin} 1s  ease` : `${otherSpin} 1s 1 ease`,
```
Comment (mark-prins) [inline client/packages/common/src/ui/icons/MSupplyGuy.tsx:76]: offroad: the infinite spin on android was annoying me!
I couldn't see an easy way to prevent that, so have just made it a single iteration animation for all clients.

infinite-spin

File: server/android/src/android.rs [hunk 2]
```diff
@@ -33,6 +33,7 @@ pub mod android {
                     &Record::builder()
                         .args(format_args!("{}", record.args))
                         .target("omSupply")
+                        .module_path(Some("omSupply"))
```
Comment (mark-prins) [inline server/android/src/android.rs:36]: this will set the `tag` to be `omSupply` in the logcat. Makes for easier filtering of events.

File: server/android/src/android.rs [hunk 3]
```diff
@@ -84,11 +83,12 @@ pub mod android {
             ),
         };
 
-        // logging_init_with_appender(settings.logging.clone(), &AndroidLogger {});
         logging_init(
             settings.logging.clone(),
             Some(Box::new(|config| config.custom(AndroidLogger {}))),
         );
+        log_panics::init();
+        log::info!("omSupply server starting...");
```
Comment (clemens-msupply) [inline server/android/src/android.rs:91]: that was just to keep them together, right?

**Review by clemens-msupply — APPROVED** [review]
Haven't tested but otherwise looks find, let me know if I should do some extra testing!

File: server/android/src/android.rs (hunk 3 above)
Comment (mark-prins) [reply server/android/src/android.rs:91]: yes - and the documentation said to have `log_panics` after the logging was initialised 🤷
