### PR TITLE
Windows event logging

### LINKED ISSUE #1284: Windows server: incorrect configuration will panic with no log
## What went wrong? 😲
 
As noted in #1136. An invalid configuration in the settings file will cause the server to panic. When running as a windows service, this will happen prior to logging being configured, so the user is unaware why the server panicked.

Cryptic message:

```
Faulting application name: omsupply_service.exe, version: 0.1.0.0, time stamp: 0x643f6548
Faulting module name: ucrtbase.dll, version: 10.0.17763.1490, time stamp: 0x48ac8393
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x530
Faulting application start time: 0x01d97273b490b0ce
Faulting application path: C:\github\open-msupply\server\target\debug\omsupply_service.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 97d51266-805f-46f5-ba0d-a973ee339085
Faulting package full name: 
Faulting package-relative application ID: 
```

## Expected behaviour 🤔
I would expect the server to log an error to the windows Application event log, telling me that the configuration is invalid.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a `local.yaml`, and add a `sync` section but do not specify the `invterval_seconds` property
2. Start the windows service
3. The service stops. An unhelpful message is logged in the event log

## Your environment 🌱
 - Version 1.x
 - Platform windows server

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1284

# 👩🏻‍💻 What does this PR do? 
 
Changed the `expect` to a match and within the error check, instantiate the `eventlog` crate and log the error to the Application event log.

# 🧪 How has/should this change been tested? 

You'd need to build on windows, create a service using the `omsupply_service.exe`, add a configuration which is invalid and try to start the service.

You'll get and entry in the event log, like so:

Screenshot 2023-04-19 at 4 15 30 PM

Note: I used `sc` to create a service:

```
sc create oms-test --binpath= "[insert path here]\omsupply_service.exe"
```

and to delete after:

```
sc delete oms-test
```

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: server/windows/src/windows.rs [hunk 1]
```diff
@@ -56,8 +57,14 @@ mod omsupply_service {
         let executable_path = current_exe().unwrap();
         let executable_directory = executable_path.parent().unwrap();
         set_current_dir(&executable_directory).unwrap();
-        let settings: Settings =
-            configuration::get_configuration().expect("Failed to parse configuration settings");
+        let settings: Settings = match configuration::get_configuration() {
+            Ok(settings) => settings,
+            Err(e) => {
+                eventlog::init("Application", log::Level::Error).unwrap();
```
Comment (andreievg) [inline server/windows/src/windows.rs:63]: does this have to be instantiated here, can it be instantiated a the top of `omsupply_service_main` ?

File: server/windows/src/windows.rs [hunk 2]
```diff
@@ -56,8 +57,14 @@ mod omsupply_service {
...
+                error!("Failed to parse configuration settings: {:?}", e);
```
Comment (andreievg) [inline server/windows/src/windows.rs:64]: if we also use log_panics::init(); at the top of omsupply_service_main, we wouldn't need to explicitly use error! here and `expect` should still work, and also it would log other unwraps and expects

**Review by andreievg — COMMENTED** [review]
Looks good, but I think it can be extended to be more generic, and apply across the whole app (rather then just configuration problems) as per comments below

File: server/windows/src/windows.rs (hunk 2 above)
Comment (mark-prins) [reply server/windows/src/windows.rs:64]: the docs for log_panics said to init after the logging was initiated, so I moved it down here. For the panic handler to run as you say, we'd need to be able to init both loggers, or un-init the event log handler. Couldn't see how to do either of those.

**Review by andreievg — APPROVED** [review]
Thanks for clarification, looks good afaik, haven't tested though.
