### PR TITLE
516 control options validation

### LINKED ISSUE #516: Control options type validation
Some custom JSONFroms control options are getting quite complex if the control is configured incorrectly the FE most likely just crashes...

Use zod or json schema, or similar to validate the option object and show error to the user (no translation needed, since the user is the UI schema designer in this case)

https://www.npmjs.com/package/zod

### PR DESCRIPTION
**Pull request by clemens-msupply**
Validates options from the ui schema. Previously the app just crashed if you had a mistake in the ui schema no it shows a descriptive error message to the ui schema designer.

Closes #516

### CODE REVIEW

**Comment by clemens-msupply** [comment]
I merged develop in, so the GH action in the PR should work (reason it fails is that it also builds the base branch which doesn't has the changes yet...)

File: client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx [hunk 1]
```diff
@@ -16,6 +16,8 @@ import {
   DateUtils,
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx:16]: Side note: the filename should be `DispensedDuration.tsx`

File: client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx [hunk 2]
```diff
@@ -119,6 +142,11 @@ const UIComponent = (props: ControlProps) => {
   );
   const error = !!errors;
 
+  useEffect(() => {
+    if (options) {
+      setLocalData(extractProperty(data, options.targetField) ?? 0);
+    }
+  }, [options]);
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx:149]:
```suggestion
  }, [data, options]);
```

doesn't the effect also depend on data? ( and `setLocalData` and `extractProperty` but I am not too concerned about including the functions )

in which case it could be included in the following effect?

which could also be checking for a valid `options` object now?

File: client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+      return `${issue.expected} ${issue.message}`;
+    }
+    case 'invalid_union': {
+      const messages = issue.unionErrors.map(it => {
+        const issue = it.issues[0];
+        if (!issue) {
+          return '';
+        } else {
+          return formatMessage(issue);
+        }
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts:16]:
```suggestion
        return !issue ? '' : formatMessage(issue);
```

File: client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts [hunk 4]
```diff
@@ -0,0 +1,64 @@
+import { useEffect, useState } from 'react';
+import { z, ZodError, ZodIssue } from 'zod';
+
+const formatMessage = (issue: ZodIssue): string => {
+  switch (issue.code) {
+    case 'invalid_type': {
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts:6]: better to use the enum I think:
```suggestion
    case ZodIssueCode.invalid_type: {
```

File: client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+      return `${issue.expected} ${issue.message}`;
+    }
+    case 'invalid_union': {
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts:9]:
```suggestion
    case ZodIssueCode.invalid_union: {
```

File: client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+};
+
+const formatError = (objectVarName: string, error: ZodError): string => {
+  return `${error.issues.map(it => formatIssue(objectVarName, it)).join(', ')}`;
+};
+
+export const useZodOptionsValidation = <T>(
+  TypeDef: z.ZodType<T, z.ZodTypeDef, T>,
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  options?: Record<string, any>
```
Comment (mark-prins) [inline client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts:45]:
```suggestion
    options?: Record<string, unknown>
```

**Review by mark-prins — APPROVED** [review]
👍  that's super useful!

Like the error message formatting too.. that is very helpful.
One small gripe, is that having test cases in the PR would make it much easier to test! I've played with my database to get errors to show, which I think is the intention?

I think that the error display could be more helpful to users. Showing this

image

is useful to developers and form designers but not for normal people!

Perhaps just an alert icon:

image

with text to say `There is an error in the form configuration` : that way, we can have user-friendly, translatable text shown. The error could be logged to console ( or raised to bugsnag? ) for developers to view

**Comment by clemens-msupply** [comment]
It was really meant for devs as a better option to crashing... I added a test as well

File: client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx (hunk 2 above)
Comment (clemens-msupply) [reply client/packages/system/src/Patient/JsonForms/components/DispendedDuration.tsx:149]: Ok done thanks!
