### PR TITLE
Remove path from the server url

### LINKED ISSUE #1704: Why does apk version opt to open browser to create Outbound Shipment from the requisition?
## What went wrong? 😲
Why does apk version opt to open browser to create Outbound Shipment from the requisition? 

## Expected behaviour 🤔
Don't throw unnecessary alerts like such when the action is easily being carried away anyways

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get a customer requistion in oms store (idk, create IO from remote desktop to oms? I did that!)
2. Fill in some Supply quantities.
3. Click `Create Shipment` button
4. See error: it'll opt you to complete the action in browser. But if you check the Outbound Shipment, the action (of creating shipment) is already complete! Why bother send that alert everytime on apk?

## Your environment 🌱
 - Version: v1.1.13
 
## Screenshots/Recordings
https://drive.google.com/file/d/116nGjtkHYWlYcADtoRBIwxQ2sPHUUEz_/view?usp=share_link

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1704

Remove the path that was introduced in:

https://github.com/openmsupply/open-msupply/pull/1452

@mark-prins I couldn't figure out why it was added, and it doesn't seem to be used anywhere (?)

In `packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java` there is the code:

```java
@Override
    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
        // reloading a page ( javascript: navigate(0) or window.location.reload() )
        // will not only reload, but will open the URL in a browser tab
        // for local URLs we don't want this to happen!
        Uri url = request.getUrl();
        if(url.toString().startsWith(this.nativeApi.getServerUrl())) {
            return false;
        }

        return bridge.launchIntent(url);
    }
```
and `this.nativeApi.getServerUrl()` returned `https://127.0.0.1:8000/login` for me.

Note, if there is a debugUrl the url is done like `localUrl = isDebug ? debugUrl : "https://localhost:" + discoveryConstants.PORT;` This potentially wouldn't work in the comparison... Can fix/investigate after the initial review, i.e. if there wasn't a reason to have the path on the url...

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
The path was added to allow the f/e app to direct the user to the `/login` screen. There's an issue where the user opens the app - the token has expired, they should be logged out, but they are shown the dashboard. It's a state they shouldn't be in.

The `useNativeClient` uses it [here](https://github.com/openmsupply/open-msupply/blob/c3534807853415ea66321fc006b7ffd69b395514/client/packages/common/src/hooks/useNativeClient/types.ts#L46) with comment

and [these lines](https://github.com/openmsupply/open-msupply/blob/c3534807853415ea66321fc006b7ffd69b395514/client/packages/host/src/components/Android.tsx#L137-L138) are where the client checks the token and redirects

Please don't take the functionality out - currently the f/e is still trying to use it!

**Review by mark-prins — CHANGES_REQUESTED** [review]
requesting changes, because this will cause another issue

**Comment by clemens-msupply** [comment]
@mark-prins thanks, I knew there was a reason behind it. I made the following changes:

- Add a getConnectionUrl() helper for got to the initial page. `getUrl()` is still used for a check in `onReceivedSslError` (it was working before because the onReceivedSslError was caught on the login page, but I found this not obvious and I had to go through the debugger to understand why it worked before. Checking against the base url is IMHO easier to understand)
- Check for local requests in `shouldOverrideUrlLoading`. This avoid issues when developing with a debug server on a local maschine where the request ip != the server ip...
- Rename the omSupplyServer class to FrontEndHost (as on the JS side)

File: client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java [hunk 1]
```diff
@@ -200,7 +199,8 @@ public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request
         // will not only reload, but will open the URL in a browser tab
         // for local URLs we don't want this to happen!
         Uri url = request.getUrl();
-        if(url.toString().startsWith(this.nativeApi.getServerUrl())) {
+        if(url.toString().startsWith("https://127.0.0.1:" + nativeApi.DEFAULT_PORT)
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java:202]: What if the server is not local, if app is in client mode and connecting to another server ?

Comment (clemens-msupply) [reply client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java:202]: Oh yes right, I guess this wouldn't work then. The case this change was covering, was that I had a debugUrl on my local machine and the `request.getUrl()` was `https://127.0.0.1`. Could ignore this case for now or add some debugUrl check...

Comment (clemens-msupply) [reply client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java]: I reverted this change in [f3bce62](https://github.com/openmsupply/open-msupply/pull/1739/commits/f3bce6257e549d40c485a6ebf25b466ba031a654)

**Review by mark-prins — APPROVED** [review]
🙏  thanks! that looks good to me.
