### PR TITLE
1096 fix test

### LINKED ISSUE #5: Sync intergrations tests for invoice lines are failing
For some reason updating an invoice line and syncing it again fails (line is not updated).

To reproduce enable the test `test_remote_syncing()` (server/src/sync/integration_tests/remote_sync_integration_test.rs) and run it (comment out unrelated sync sub tests to speed up the test).

### LINKED ISSUE #11: Improved name sync
- [x] Sync more name table field
- [x] Remove legacy blob
- [x] Push name changes as remote data (possible in programs branch)

### PR DESCRIPTION
**Pull request by clemens-msupply**
Closes #11
Closes #5

### CODE REVIEW

File: server/repository/migrations/postgres/2021-08-15T10-00_create_name_table/up.sql [hunk 1]
```diff
@@ -32,7 +32,7 @@ CREATE TABLE name (
     is_customer BOOLEAN NOT NULL,
     is_supplier BOOLEAN NOT NULL,
    
-    supplying_store_id Text REFERENCES store(id),
+    supplying_store_id Text,
```
Comment (clemens-msupply) [inline server/repository/migrations/postgres/2021-08-15T10-00_create_name_table/up.sql:35]: Avoid circular dependencies store -> name -> store

**Review by andreievg — APPROVED** [review]
