### PR TITLE
Add useDeviceDetect hook. Fix wrong navigation

### LINKED ISSUE #2243: (Android) Collapsed navigation menu directs to the wrong place
## What went wrong? 😲

Under certain circumstances clicking on an item in the side navigation menu does not take the user to the correct destination. 

E.g. If the user is in the Inbound Shipments screen and clicks on the Inventory icon, it takes them to the Suppliers list instead. 

https://github.com/openmsupply/open-msupply/assets/19318937/e1ff2a2e-6033-44d7-890d-0f4295183e02

## Expected behaviour 🤔

Menu should always take user to the correct destination.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Inbound Shipments
2. Click on the Inventory icon in the nav bar
3. Note that you are taken to the Suppliers List

## Your environment 🌱
 - Version: 1.3.00
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #2243 

# 👩🏻‍💻 What does this PR do? 
Adds a custom hook to detect if the user device is mobile. Maybe there is something like this already in the app? I couldn't see it though. 

# 🧪 How has/should this change been tested? 
You can test this by going to dashboard, opening dev tools, and selecting a mobile (ipad) dimensions.
Try interacting with the appbar as outlined in the video of #2243 
You can then compare develop branch to this branch, and see the functionality difference.

## 💌 Any notes for the reviewer?
There is a risk that the mobile checking isn't an exhaustive list, so might need to be updated.

Alternatively, we could use a package like https://www.npmjs.com/package/react-device-detect

I also wondered if there were other mouse specific interactions which wouldn't be appropriate for mobile which could also benefit from this hook, but can't see anything at a glance.

### CODE REVIEW

File: client/packages/host/src/utils.ts [hunk 1]
```diff
@@ -1,7 +1,24 @@
...
+    const mobile = Boolean(
+      userAgent.match(
+        /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
+      )
+    );
+    setMobile(mobile);
+  }, []);
+
+  return { isMobile };
+};
```
Comment (CarlosNZ) [inline client/packages/host/src/utils.ts:24]: Since `window.navigator.userAgent` is just a static value that is always available, I'm not sure this needs to be a hook (i.e. no need to hold any of its own state). Just a simple expression will do, I think:

```ts
export const isMobile = Boolean(
  navigator.userAgent.match(
    /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
  )
);
```

Also, a better location for this might be `client/packages/config/src/config.ts`, though perhaps @mark-prins might have another suggestion?

File: client/packages/host/src/components/AppDrawer/AppDrawer.tsx [hunk 2]
```diff
@@ -151,13 +153,15 @@ export const AppDrawer: React.FC = () => {
   }, [isMediumScreen]);
 
   const onHoverOut = () => {
+    if (isMobile) return;
```
Comment (CarlosNZ) [inline client/packages/host/src/components/AppDrawer/AppDrawer.tsx:156]: It actually took me a little while to understand why this was necessary, but it's because "hover" events aren't registered properly on mobile, right? (They fire onClick).

So maybe just add a comment here before this line:
```ts
// Hover events not applicable on mobile devices
```

File: client/packages/host/src/utils.ts [hunk 3]
```diff
@@ -1,7 +1,24 @@
...
+
+export const useDeviceDetect = () => {
+  const [isMobile, setMobile] = useState(false);
+
+  useEffect(() => {
+    const userAgent =
+      typeof window.navigator === 'undefined' ? '' : navigator.userAgent;
+    const mobile = Boolean(
+      userAgent.match(
+        /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
```
Comment (CarlosNZ) [inline client/packages/host/src/utils.ts:17]: I guess this list is probably fine for our purposes, but if you wanted to, you could try one of the more foolproof ways of detecting mobile that are listed here: https://stackdiary.com/detect-mobile-browser-javascript/

(In particular, I'm looking at "TouchEvent" and "Window.matchMedia")

Probably not super important for now, but maybe add a comment with a link to that page for future reference.

**Review by CarlosNZ — CHANGES_REQUESTED** [review]
Thanks, @fergie-nz -- well done for figuring out what was causing this problem, it's not particularly obvious.

Couple of suggestions -- main one being I don't think it needs to be a hook.

File: client/packages/host/src/utils.ts [hunk 4]
```diff
@@ -1,7 +1,24 @@
-import { ReactNode } from 'react';
+import { ReactNode, useState, useEffect } from 'react';
 
 export const getBadgeProps = (value?: number) => ({
   badgeContent: (value ?? 0) as ReactNode,
   max: 99,
   color: 'primary' as 'primary' | 'default',
 });
+
+export const useDeviceDetect = () => {
```
Comment (mark-prins) [inline client/packages/host/src/utils.ts:9]: rather than a new hook, just use `Capacitor.isNativePlatform()`
I'm nervous about the userAgent matching.. even though it would be totally fine

**Review by mark-prins — CHANGES_REQUESTED** [review]
Good catch! thanks for picking that up 😁 

I have a suggestion - can you change to use the existing method from `Capacitor` please?
Ordinarily I'd request importing that only into `common` and re-exporting.. but I've already broken that rule by importing into `AndroidSettings`.. so just import and use in the `AppDrawer`

File: client/packages/host/src/utils.ts (hunk 4 above)
Comment (mark-prins) [reply client/packages/host/src/utils.ts:9]: Ok - good point @CarlosNZ the `isNativePlatform()` won't detect as intended if you are running a browser on a tablet.
In that case, could you please use

```
    if(EnvUtils.platform === Platform.Android) return;
```

I've tested this on a browser on android and it works as expected.
Perhaps also build out the user agent check in EnvUtils and add in `iOS` too?

Comment (CarlosNZ) [reply client/packages/host/src/utils.ts:9]: > rather than a new hook, just use `Capacitor.isNativePlatform()` I'm nervous about the userAgent matching.. even though it would be totally fine

Yeah, ideally it would work for any touch screen environment, regardless of OS/browser/build. Perhaps we should add a specific `isTouchScreen` property to `EnvUtils`?

Comment (mark-prins) [reply client/packages/host/src/utils.ts:9]: true - that's what we're looking to detect here. I liked the use of 'ontouchstart' that you linked to.
This seems to work..

```
const isTouchScreen = 'ontouchstart' in document.documentElement;

export const EnvUtils = {
  // Using isProduction rather than isDevelopment, as we also use a testing
  // environment while running jest, so easier to check !isProduction, generally.
  isProduction: (): boolean => process.env['NODE_ENV'] === 'production',
  isTouchScreen,
  mapRoute,
  platform,
  printFormat: PrintFormat.Html, // platform === Platform.Android ? PrintFormat.Html : PrintFormat.Pdf,
};
```

```
    if (EnvUtils.isTouchScreen) return;
```

File: client/packages/host/src/components/AppDrawer/AppDrawer.tsx [hunk 5]
```diff
@@ -151,13 +151,19 @@ export const AppDrawer: React.FC = () => {
...
 
     drawer.close();
     drawer.setHoverOpen(false);
   };
 
   const onHoverOver = () => {
+    // Hover events not applicable on mobile devices
+    if (EnvUtils.isTouchScreen) return;
+
+    if (EnvUtils.isTouchScreen) return;
```
Comment (mark-prins) [inline client/packages/host/src/components/AppDrawer/AppDrawer.tsx:166]: once is probably enough 😉 
```suggestion
    if (EnvUtils.isTouchScreen) return;
```

**Review by mark-prins — APPROVED** [review]
👍 very nice thanks.
One small extra suggestion, as noted.

**Comment by mark-prins** [comment]
@CarlosNZ - is this ok to merge now?

**Review by CarlosNZ — APPROVED** [review]
LGTM! Thanks, @fergie-nz
