### PR TITLE
2278 Location function in stocktake

### LINKED ISSUE #2278: Location function in stocktake
## What went wrong? 😲
Cannot see locations when doing a stocktake

Screenshot 2023-09-25 at 3 26 06 PM

## Expected behaviour 🤔
Need to see locations otherwise users will not know where to go to find the stock to count

## How to Reproduce 🔨
No

## Your environment 🌱
v 1.3 desktop

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #2278

# 👩🏻‍💻 What does this PR do? 
Adds a location column to the stocktake detail view, fixed [multiple] showing up for empty reasons, added [multiple] to translation and show [multiple] for invoice lines that have batches in different locations in inbound, outbound and prescriptions
Screenshot 2023-09-29 at 2 46 35 PM

# 🧪 How has/should this change been tested? 
- [ ] Have an item with multiple stock lines in different locations 
- [ ] Do a stocktake with that line, see location column and grouping.

## 💌 Any notes for the reviewer?
Louisa suggested that the locations column for stocktake be moved to the left of `code`, but that would be inconsistent with our other views, so unsure if we should move or not... Locations still seem viewable when I view on a tablet screen size, so might be alright?

### CODE REVIEW

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 1]
```diff
@@ -29,18 +33,24 @@ const expandColumn = getRowExpandColumn<
...
       .map(({ inventoryAdjustmentReason }) => inventoryAdjustmentReason)
       .filter(Boolean) as InventoryAdjustmentReasonRowFragment[];
-    return (
-      ArrayUtils.ifTheSameElseDefault(
-        inventoryAdjustmentReasons,
-        'reason',
-        '[multiple]'
-      ) ?? ''
-    );
+    if (inventoryAdjustmentReasons.length !== 0) {
```
Comment (roxy-dao) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:43]: Sidetracked: Whole reasons column was showing [multiple] kek

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 2]
```diff
@@ -96,8 +107,11 @@ export const useStocktakeColumns = ({
             if ('lines' in row) {
               const { lines } = row;
               return (
-                ArrayUtils.ifTheSameElseDefault(lines, 'batch', '[multiple]') ??
-                ''
+                ArrayUtils.ifTheSameElseDefault(
+                  lines,
+                  'batch',
+                  `${t('multiple')}`
```
Comment (roxy-dao) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:113]: Sidetracked: translating all `[multiple]`s

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 3]
```diff
@@ -151,6 +165,46 @@ export const useStocktakeColumns = ({
           },
         },
       ],
+      [
+        'locationName',
+        {
+          getSortValue: row => {
+            if ('lines' in row) {
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:172]: Can we just remove sort if it's in 'item' view ? or maybe use helper ?

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 4]
```diff
@@ -151,6 +165,46 @@ export const useStocktakeColumns = ({
...
+              }
+            } else {
+              return row.location?.name ?? '';
+            }
+          },
+          accessor: ({ rowData }) => {
+            if ('lines' in rowData) {
+              const locations = rowData.lines
+                .map(({ location }) => location)
+                .filter(Boolean) as LocationRowFragment[];
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:193]: "as" is big red flag for me for type safety, it might be ok now but things could break if say something new is added to LocationRowFragment but not to this [query](https://github.com/openmsupply/open-msupply/blob/508b6e5a9ac46f08b7bac9a5f9276d1f052faa39/client/packages/system/src/Item/api/operations.graphql#L16-L21), etc..

You can use flatMap here:

const locations = rowData.lines.flatMap(({location}) => !!location ? [location] : []);

**Review by andreievg — CHANGES_REQUESTED** [review]
Look good, but I one request, and that's to not cast with 'as'

**Review by andreievg — CHANGES_REQUESTED** [review]
Look good, but I one request, and that's to not cast with 'as'

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 2 above)
Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:113]: No, it can't tell apart from function/variable from non

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 3 above)
Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:172]: Hmm, we still need to sort if it's in 'item' view though? 🤔

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 4 above)
Comment (roxy-dao) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts]: [0a8687a](https://github.com/openmsupply/open-msupply/pull/2302/commits/0a8687a545df503a9218a2536e6e789c69e9ed2e)

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 2 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:110]: But this compiles for me ¯\_(ツ)_/¯  https://github.com/openmsupply/open-msupply/compare/2278-Location-function-in-stocktake...2278-Location-function-in-stocktake(Suggestion)

**Review by andreievg — APPROVED** [review]
Looks good thanks, I still think it's ok to use t('multiple') please see suggestion

**Comment by roxy-dao** [comment]
> Looks good thanks, I still think it's ok to use t('multiple') please see suggestion

Thanks Andrei~ Have implemented the change (:
