### PR TITLE
Ask user about fingerprint change

### LINKED ISSUE #1783: Desktop - certificate fingerprint error
## What went wrong? 😲
 
telegram-cloud-photo-size-4-5985296734298946951-y

Somehow, the server certificate has changed. This is a blocker for the desktop app, which shows the above error and cannot be easily cleared.

## Expected behaviour 🤔
Display an alert to the user

`The security certificate on the server has changed. This can happen when the server is reinstalled - please check with your IT department if you are unsure. Would you like to accept the new certificate? `

and allow the user to click `OK` or `Cancel`. If clicking `OK` then accept the new fingerprint value and continue.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Guessing at this stage. There's more investigation to come in #1782 

1. Start the server
2. Connect using the desktop
3. Stop the server. Recreate certificates and restart.
4. Reconnect with the desktop

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1783 

# 👩🏻‍💻 What does this PR do? 
 
Prompts the user if there is a fingerprint change and asks them to accept it. This is how it looks in development mode on a mac:

Screenshot 2023-05-16 at 3 26 00 PM

Windows version is being built.

For reference - the [message box options](https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options)

# 🧪 How has/should this change been tested? 

Just tested on mac, with a windows server. 
Connected, then stopped the server, changed the cert and started the server again.

## 📃 Documentation

- [ ] Should mention this somewhere. not public docs but.

### CODE REVIEW

File: client/packages/electron/src/electron.ts [hunk 1]
```diff
@@ -259,11 +259,22 @@ app.addListener(
...
+      if (returnValue.response === 0) {
+        ipcMain.emit(IPC_MESSAGES.GO_BACK_TO_DISCOVERY);
+        return callback(false);
+      }
+
+      // Update stored fingerprint
+      storedFingerprint = certificate.fingerprint;
+      store.set(identifier, storedFingerprint);
 
       return callback(false);
```
Comment (andreievg) [inline client/packages/electron/src/electron.ts:279]: i think this return needs to be removed

**Review by andreievg — APPROVED** [review]
Looks good, but only with this commit: https://github.com/openmsupply/open-msupply/compare/1783-accept-fingerprint...1783-example

Otherwise would default to normal behaviour (ssl error)

**Comment by mark-prins** [comment]
🙏  @andreievg I had just realised that one.. a little late to the party. Working nicely now.
Fixed in 285cfd849
