### PR TITLE
#1666 Master lists in outbound shipment doesn't update when changing supplier

### LINKED ISSUE #1666: Master lists in outbound shipment doesn't update when changing supplier
## What went wrong? 😲

When adding master list in outbound shipment, master list don't update when changing supplier

## Expected behaviour 🤔

They update

## How to Reproduce 🔨

Have two different customers with two different master list, create outbound shipment for one customer, try adding from master list and note master lists that are shown, change customer, note master list didn't change. Master list will change if page is refreshed.

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1666

# 👩🏻‍💻 What does this PR do? 
Refetch MasterList every time the modal is opened.

# 🧪 How has/should this change been tested? 
- [ ] Have two customers with different MasterLists
- [ ] Create an Outbound Invoice
- [ ] Change customer
- [ ] MasterList list should update accordingly

### CODE REVIEW

File: client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx [hunk 1]
```diff
@@ -24,12 +24,11 @@ export const MasterListSearchModal: FC<MasterListSearchProps> = ({
...
     filterBy
   );
-  const t = useTranslation(['app', 'common']);
+  const t = useTranslation('app');
 
-  // Only query for data once the modal has been opened
   useEffect(() => {
-    if (open && !data && !isLoading) mutate();
-  }, [open, data, isLoading]);
+    if (open) mutate();
```
Comment (roxy-dao) [inline client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx:30]: Data is cached, so previous check will always return false after first fetch... couldn't get it to clear in the hook, so have just changed the condition to re-fetch every time the modal opens...

**Review by CarlosNZ — APPROVED** [review]
Great, seems like a good fix :)

File: client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx (hunk 1 above)
Comment (mark-prins) [inline client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx:30]: I think the comment is still valid - the effect is deliberately only fetching when the modal is opened

**Review by mark-prins — APPROVED** [review]
👍  nice - thanks Roxy. I was wondering if it would be better to cache the query based on the `filterBy` prop and reduce the number of api calls.. but I think that's overdoing it! what you have is better.

File: client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx (hunk 1 above)
Comment (clemens-msupply) [reply client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx:30]: We should really have a query version of listAll. In `useQuery` there is the option to enable or disable the query, i.e. you can pass `enabled: open` as a parameter. react/tan query should do the rest for you. @mark-prins or am I missing something here?

Example to enable the query: `packages/common/src/authentication/api/hooks/useUserDetails.ts`

Comment (roxy-dao) [reply client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx:30]: The useMasterListAll is using a mutation to get the query... I mean, I could change it to useQuery if there wasn't a reason for it to be useMutation

Comment (mark-prins) [reply client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx:30]: yeah, thanks @clemens-msupply, was wondering about doing that. 

The usage in `CreateStocktakeButton` is using `useEffect` to do what a `useQuery` would give you anyway - ie that would be better as a `useQuery`.

I was reluctant to change to a query because, like you say Roxy, all the `useAll` functions are using mutations. and I'm also reluctant to duplicate the methods ( but I'll get over that ). Can't just use `useMasterList.document.list` as that is using url query params. 

I think there's no perfect option - what you've done with the `open` var is my top pick which is why I approved. If you want to change, my preference is the option of changing `listAll` to use `useQuery` and then updating the three usages. But any of the options would be fine.
