### PR TITLE
1225 exhaustive structured error check for stocktake

### LINKED ISSUE #1225: Use exhaustive structured error check for stocktake
## What went wrong? 😲

Seeing all `reasons` being selected when one has error, also not seeing indication of what line has reduction below zero error, and wrong reason (using negative reason for positive adjustment) should be structured error ?

## Expected behaviour 🤔

User should see what line is erroneous and what errors exist.

Should be using structured errors and exhaustive matching when possible, hoping that this PR would showcase how this can be done and the benefits

## How to Reproduce 🔨

Try multiple lines with errors

## Your environment 🌱

This is on the latest negative adjustment PR

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1225 

# 👩🏻‍💻 What does this PR do? 

Adds exhaustive check for structure errors for stocktake update and stock line edits, displays these errors as notifications and as red borders around related cells.

**Brief description**:

Added stock line error context, which is updated during stocktake update and stocktake lines edits, this context is used in stocktake table and stocktake batch table to render related cells in error state. In stocktake update and stocktake line edits do exhaustive check on resulting structured errors. 

See self review for detailed explanation.

# 🧪 How has/should this change been tested? 

**Snapshot != total error** 
This happens if total number of packs on stock line does not match snapshot on stocktake line.
- [ ] Create stocktake with existing stock line
- [ ] Create outbound shipment for that line and `ship` it
- [ ] Try to finalise stocktake, should see an error notification with explanation and every snapshot cell where total does not match snapshot should have a red border
- [ ] Clicking on the line to see batch edit, should see error on that line
- [ ] Should see error in snapshot cell when toggling by item grouping and in the expansion
- [ ] Re-making the line through batch edit, should remove red border when looking in main stocktake window

**Reducing below zero**
This happens if it's possible to reduce available number of packs below zero while doing stocktake
- [ ] Create stocktake with existing stock line, with counted below half of snapshot
- [ ] Create outbound shipment for that line, issuing at least half of it (don't ship it)
- [ ] Try to finalise stocktake, should see an error notification with explanation and every counted cell where available could be reduced below zero
- [ ] Clicking on the line to see batch edit, should see error on that line
- [ ] Should see error in counted cell when toggling by item grouping and in the expansion
- [ ] Changing to higher stocktake quantity (where adjustment would be below available quantity) in batch edit, should remove red border when looking in main stocktake window

**Reason not provided**
This is for stocktake batch edit window, when reason was not provided but there is adjustment, should see red border on reason drop down, will disappear when changed and OK is pressed. OK and OK next should stay on current batch edit window and updates shouldn't have happened.

Reasons can be configured in mSupply `options` (positive/negative inventory adjustments)

**Reason not valid**
This is very similar to `Reason not provided` but it's when adjustment was changed from negative to positive but reason is still set as negative or positive

Try multiple errors, in batch edit window, should see them on different lines/cells and multiple notifications should appear

Back end checks erros sequentially (wont' see multiple error types on the same line and wouldn't see multiple error types in main stocktake page, but would see multiple lines for error of the same type if they exist)

## 💌 Any notes for the reviewer?

Hidden whitespace changes diff would be easier to review

Even though there is limited indication of errors on each line, all of the data is available (there is stock line on error variant etc..), we may wish to show more info to help the user (or do auto fixes using current state of stock line or stocktake line in the error result). Also exhaustive check means if new error variant is added, we would know exactly where to add in in f/e

I think it's a good idea to see the behaviour of different errors prior to this PR to see why some of the changes have been made

## 📃 Documentation

Not sure how much to document, I think there should be some internal and external documentation:

`internal` -> example and explanation about exhaustive matching, structured errors, why have extra thing in errors results, `__typename` being important in the mutation/query result etc..

`external` -> what each of the errors actually mean and how to fix them ?

### CODE REVIEW

File: client/packages/common/src/types/schema.ts [hunk 1]
```diff
@@ -2858,7 +2863,7 @@ export type StockLineSortInput = {
 export type StockLinesReducedBelowZero = UpdateStocktakeErrorInterface & {
   __typename: 'StockLinesReducedBelowZero';
   description: Scalars['String'];
-  stockLines: StockLineConnector;
+  errors: Array<StockLineReducedBelowZero>;
```
Comment (andreievg) [inline client/packages/common/src/types/schema.ts:2866]: `StockLinesReducedBelowZero` to return array of `StockLineReducedBelowZero`. If error occurs during finalisation, it is displayed in main table and when we look at batch table, error should also be displayed (just by opening it, if error was already know when we tried to finalise stocktake), since batch table needs to display errors based on StockLine (since it shows draft lines, and they may not be inserted yet), it's good to use one common error for each stocktake line, thus collection of `StockLineReducedBelowZero` errors that can be mapped to each stocktake line.

File: client/packages/common/src/ui/layout/tables/columns/types.ts [hunk 2]
```diff
@@ -75,6 +76,9 @@ export interface Column<T extends RecordWithId> {
   sortInverted: boolean;
   getSortValue?: (row: T) => string | number;
 
+  isError?: (row: T) => boolean;
+  isDisabled?: (row: T) => boolean;
```
Comment (andreievg) [inline client/packages/common/src/ui/layout/tables/columns/types.ts:80]: Added is disabled because I saw this previously: 

https://github.com/openmsupply/open-msupply/blob/9c0c17388ef89fdafcc91b0ecf50d6d19cbf9158/client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx#L131-L136

Which was changed now to just be:

https://github.com/openmsupply/open-msupply/blob/de6113720ff71895d85bab5e585c7a0b1733bede/client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx#L152-L156

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx [hunk 3]
```diff
@@ -1,26 +1,36 @@
...
-      style={{
-        overflow: 'hidden',
-        textOverflow: 'ellipsis',
-        textAlign: 'right',
-        fontSize: 'inherit',
+    <Box
+      sx={{
+        border: theme =>
+          isError ? `2px solid ${theme.palette.error.main}` : 'none',
+        borderRadius: '8px',
```
Comment (andreievg) [inline client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx:20]: I copied styles here from: 

https://github.com/openmsupply/open-msupply/blob/de6113720ff71895d85bab5e585c7a0b1733bede/client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx#L32-L40

Maybe a special style is better for this or ErroBox (as a wrapper component) ¯\_(ツ)_/¯

File: client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx [hunk 4]
```diff
@@ -125,9 +125,10 @@ const DataRowComponent = <T extends RecordWithId>({
                 >
                   {
                     <column.Cell
-                      isDisabled={isDisabled}
+                      isDisabled={isDisabled || column.isDisabled?.(rowData)}
```
Comment (andreievg) [inline client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx:128]: As per earlier comment seems like it was needed to be by cell (not just by row)

File: client/packages/common/src/utils/types/TypeUtils.ts [hunk 5]
```diff
@@ -4,3 +4,7 @@ export const TypeUtils = {
     field: string
   ): variableToCheck is T => field in (variableToCheck as T),
 };
+
+export const noOtherVariants = (variant: never): never => {
```
Comment (andreievg) [inline client/packages/common/src/utils/types/TypeUtils.ts:8]: Method used in switch case to do exhaustive match

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 6]
```diff
@@ -173,6 +176,12 @@ export const useStocktakeColumns = ({
         description: 'description.snapshot-num-of-packs',
         align: ColumnAlign.Right,
         Cell: PositiveNumberCell,
+        isError: row => {
+          let rows = 'lines' in row ? row.lines : [row];
+          return rows.some(
+            r => getError(r)?.__typename === 'SnapshotCountCurrentCountMismatch'
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:182]: This is how the context is used to get an error for a row (recordWithId), in this case if the group by item has a line with an error or if line is erroneous, mark this cell as error

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 7]
```diff
@@ -49,8 +50,10 @@ export const useStocktakeColumns = ({
   onChangeSortBy,
 }: UseStocktakeColumnOptions): Column<
   StocktakeLineFragment | StocktakeSummaryItem
->[] =>
-  useColumns<StocktakeLineFragment | StocktakeSummaryItem>(
+>[] => {
+  const { getError } = useStocktakeLineErrorContext();
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:54]: I didn't want to use context at first, but realised it's much more convenient

Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts:54]: See comment in context about the reasoning behind context vs extra field on stocktake line or draft stocktake line

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx [hunk 8]
```diff
@@ -72,16 +80,61 @@ const useStatusChangeButton = () => {
...
+    }
+
     if (result.__typename === 'StocktakeNode') {
       return success(t('messages.saved'))();
     }
 
-    switch (result.error.__typename) {
+    const { error } = result;
+
+    // General errors
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx:98]: Below is the exhaustive match for stuctured error

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx [hunk 9]
```diff
@@ -72,16 +80,61 @@ const useStatusChangeButton = () => {
...
+    let stocktakeLineIdsWithErrors: {
+      [id: string]: StocktakeLineError;
+    } = {};
+    // By line errors
+    switch (error.__typename) {
       case 'StockLinesReducedBelowZero':
-        return error(t('error.stocktake-has-stock-reduced-below-zero'))();
+        // StockLinesReducedBelowZero.errors contains an array of StockLineReducedBelowZero which have StockLines
+        // we want to match StocktakeLine ids for those errors
+        stocktakeLineIdsWithErrors = error.errors.reduce((acc, innerError) => {
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx:115]: this might be easier if `StockLinesReducedBelowZero` had stocktake lines, but it wouldn't be consistent with `StockLineReducedBelowZero` and we wouldn't have current stockline info when navigating to batch edit (I think we want to show more info about this error eventually and would need latest stockline info for that)

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx [hunk 10]
```diff
@@ -64,48 +65,17 @@ export const StocktakeLineEdit: FC<StocktakeLineEditProps> = ({
...
-      if (
-        response?.response?.__typename === 'UpdateStocktakeLineError' &&
-        response?.response?.error?.__typename === 'AdjustmentReasonNotProvided'
-      ) {
-        return error(t('error.provide-reason'))();
-      }
-    });
+    let { errorMessages } = await save();
+    if (errorMessages)
+      return errorMessages.forEach(errorMessage => error(errorMessage)());
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx:70]: It looks like previously we might have still. navigated to next item even on error

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 11]
```diff
@@ -104,14 +106,19 @@ const getInventoryAdjustmentReasonInputColumn = (
         rowData.snapshotNumberOfPacks -
         (rowData.countedNumberOfPacks || rowData.snapshotNumberOfPacks);
 
+      const errorType = getError(rowData)?.__typename;
+      const isAdjustmentReasonError =
+        errorType === 'AdjustmentReasonNotProvided' ||
+        errorType === 'AdjustmentReasonNotValid';
+
       return (
         <InventoryAdjustmentReasonSearchInput
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:115]: While looking at this PR i was tempted to refactor this, I didn't see a reason why `InventoryAdjustmentReasonSearchInput` need to be a common component, and why we would need the wrapper `getInventoryAdjustmentReasonInputColumn` for it, rather then using `Cell` property and   `InventoryAdjustmentReasonSearchInput` defined in inventory package, and `InventoryAdjustmentReasonSearchInput` can have all of the logic.

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 12]
```diff
@@ -35,6 +44,58 @@ export const useStocktakeLineEdit = (
...
+    const insertResults = result.batchStocktake?.insertStocktakeLines || [];
+    const updateResults = result.batchStocktake?.updateStocktakeLines || [];
+
+    let errorMessagesMap: { [key: string]: string } = {};
+
+    for (const { response, id } of [...insertResults, ...updateResults]) {
+      // First unset error
+      errors.unsetError(id);
+      // No error
+      if (response.__typename === 'StocktakeLineNode') continue;
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:64]: Another simpler use case of exhaustive matching

File: client/packages/inventory/src/Stocktake/api/operations.graphql [hunk 13]
```diff
@@ -116,6 +116,26 @@ query stocktakeByNumber($stocktakeNumber: Int!, $storeId: String!) {
   }
 }
 
+fragment StockLineReducedBelowZeroError on StockLineReducedBelowZero {
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/api/operations.graphql:119]: In this file I've added fragments, since errors would need to be extracted into error type it was easier to do it through framents:

https://github.com/openmsupply/open-msupply/blob/09a82f823dfddaf7f6537f49e8fccdf81280e88d/client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx#L10-L14

Otherwise typescript looks pretty complex (but can be done by looking at `UpsertStocktakeLinesMutation` type, but yeah it's very messy.

File: client/packages/inventory/src/Stocktake/api/operations.graphql [hunk 14]
```diff
@@ -159,21 +179,12 @@ mutation upsertStocktakeLines(
         response {
           __typename
           ... on InsertStocktakeLineError {
-            __typename
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/api/operations.graphql:162]: This was change to have `__typename` in the type that has unions. It's quite important, since graphql generator adds all variants with __typename to the type, but if __typename is missing, or the type is not matched, it's possible for graphql to return `{}` but f/e would expect `{__typename: SomeType}`, causing runtime errors, I can try and show an example

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx [hunk 15]
```diff
@@ -0,0 +1,63 @@
+import { PropsWithChildrenOnly, RecordWithId } from '@common/types';
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:1]: The context with errors seemed like the easier way to do it, at first I thought to just add a field to DraftStocktakeLine, but these errors would also need to be shown in main stocktake view and would need to update when they are fixed in batch view, so common context with errors seemed like the way to go

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx [hunk 16]
```diff
@@ -0,0 +1,63 @@
...
+    setErrors(errors => ({ ...errors, [id]: undefined }));
+  };
+
+  const unsetAll = () => {
+    setErrors({});
+  };
+
+  return { errors, setError, setErrors, getError, unsetError, unsetAll };
+};
+export type UseStocktakeLineErrors = ReturnType<typeof useStocktakeLineErrors>;
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:39]: rather then defining the type of each individual method, can use return type of the main state hook

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx [hunk 17]
```diff
@@ -0,0 +1,63 @@
...
+
+const StocktakeLineErrorContext = createContext<UseStocktakeLineErrors | null>(
+  null
+);
+
+export const useStocktakeLineErrorContext = () => {
+  const context = useContext(StocktakeLineErrorContext);
+
+  if (!context) throw new Error('Context does not exist');
```
Comment (andreievg) [inline client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:48]: This is safe right ? rather then defining defaults for each of the methods

File: client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx [hunk 18]
```diff
@@ -39,7 +39,7 @@ export const InventoryAdjustmentReasonSearchInput: FC<
   const disabled = data?.totalCount === 0;
   const isRequired = !disabled && stockReduction !== 0;
   const reasonFilter = (reason: InventoryAdjustmentReasonRowFragment) => {
-    if (stockReduction === 0 || !stockReduction) return true;
+    if (stockReduction === 0) return false;
```
Comment (andreievg) [inline client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:42]: previously would show all options if there is no adjustment

File: client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx [hunk 19]
```diff
@@ -75,7 +75,7 @@ export const InventoryAdjustmentReasonSearchInput: FC<
               ...props.InputProps,
             }}
             sx={{ width }}
-            error={isError && isRequired}
```
Comment (andreievg) [inline client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:78]: if back end returned an error this should be shown either way

File: server/graphql/stocktake/src/mutations/update.rs [hunk 20]
```diff
@@ -28,28 +29,32 @@ pub enum UpdateStocktakeStatusInput {
...
 #[Object]
 impl SnapshotCountCurrentCountMismatch {
     pub async fn description(&self) -> &'static str {
         "Snapshot count doesn't match the current stock count"
     }
 
-    pub async fn lines(&self) -> StocktakeLineConnector {
-        StocktakeLineConnector::from_domain_vec(self.0.clone())
+    pub async fn lines(&self) -> &StocktakeLineConnector {
+        &self.0
```
Comment (andreievg) [inline server/graphql/stocktake/src/mutations/update.rs:40]: For consistency sake (and also to avoid clone())

File: server/graphql/stocktake_line/src/mutations/update.rs [hunk 21]
```diff
@@ -13,7 +14,9 @@ use service::{
     },
 };
 
-use super::{AdjustmentReasonNotProvided, StockLineReducedBelowZero};
+use crate::mutations::AdjustmentReasonNotValid;
```
Comment (andreievg) [inline server/graphql/stocktake_line/src/mutations/update.rs:17]: This was previously standard error, with no way to point to an erroneous line, change to structured.

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx (hunk 11 above)
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:115]: yes, could do. Another issue though please! this PR is already a long one to review 😉

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 22]
```diff
@@ -142,22 +143,41 @@ export const BatchTable: FC<StocktakeLineEditTableProps> = ({
       key: 'snapshotNumberOfPacks',
       label: 'label.num-packs',
       width: 100,
+      isError: rowData =>
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:146]: utility method again? and below

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx [hunk 23]
```diff
@@ -142,22 +143,41 @@ export const BatchTable: FC<StocktakeLineEditTableProps> = ({
...
+        // If counted number of packs was changed to result in no adjustment
+        // we should remove inventoryAdjustmentReason, otherwise could have a reason
+        // on a line with no adjustments
+        let inventoryAdjustmentReason = patch.inventoryAdjustmentReason;
+        if (
+          !patch.countedNumberOfPacks ||
+          patch.snapshotNumberOfPacks == patch.countedNumberOfPacks
+        ) {
+          inventoryAdjustmentReason = null;
+        }
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:177]: or 
```
const inventoryAdjustmentReason =
          !patch.countedNumberOfPacks ||
          patch.snapshotNumberOfPacks == patch.countedNumberOfPacks
            ? null
            : patch.inventoryAdjustmentReason;
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 24]
```diff
@@ -1,31 +1,40 @@
...
+export const errorMessage = (error: unknown): string => {
+  // Bugsnag it ?
+  if (error instanceof Error) return error.message;
+  return String(error);
+};
+
 export const useStocktakeLineEdit = (
   item: ItemRowFragment | null
 ): useStocktakeLineEditController => {
+  const t = useTranslation(['inventory']);
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:32]: no need for the array when using a single namespace
```suggestion
  const t = useTranslation('inventory');
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 25]
```diff
@@ -1,31 +1,40 @@
...
   const { id } = useStocktake.document.fields('id');
   const nextItem = useNextItem(item?.id);
   const [draftLines, setDraftLines] = useDraftStocktakeLines(item);
-  const { mutateAsync: save, isLoading, isError } = useStocktake.line.save();
+  const { mutateAsync, isLoading } = useStocktake.line.save();
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:36]: side note: I still prefer the renaming of `mutateAsync` - it's such a vague fn name 🙄

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 26]
```diff
@@ -35,6 +44,58 @@ export const useStocktakeLineEdit = (
...
+    try {
+      result = await mutateAsync(draftLines);
+    } catch (e) {
+      return { errors: errorMessage(e) };
+    }
+
+    const insertResults = result.batchStocktake?.insertStocktakeLines || [];
+    const updateResults = result.batchStocktake?.updateStocktakeLines || [];
+
+    let errorMessagesMap: { [key: string]: string } = {};
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:58]: :nit not reassigned
```suggestion
    const errorMessagesMap: { [key: string]: string } = {};
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 27]
```diff
@@ -35,6 +44,58 @@ export const useStocktakeLineEdit = (
...
+
+    for (const { response, id } of [...insertResults, ...updateResults]) {
+      // First unset error
+      errors.unsetError(id);
+      // No error
+      if (response.__typename === 'StocktakeLineNode') continue;
+
+      let { error } = response;
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:66]: :nit not reassigned. Also, when destructuring - good to indicate the immutability of props taken
```suggestion
      const { error } = response;
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 28]
```diff
@@ -1,31 +1,40 @@
...
 export const useStocktakeLineEdit = (
   item: ItemRowFragment | null
 ): useStocktakeLineEditController => {
+  const t = useTranslation(['inventory']);
   const { id } = useStocktake.document.fields('id');
   const nextItem = useNextItem(item?.id);
   const [draftLines, setDraftLines] = useDraftStocktakeLines(item);
-  const { mutateAsync: save, isLoading, isError } = useStocktake.line.save();
+  const { mutateAsync, isLoading } = useStocktake.line.save();
+  const errors = useStocktakeLineErrorContext();
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:37]: bit of a :nit but the naming of the variable threw me.
`errors` would normally indicate an array of errors.. or some kind of collection at least.
This is some kind of errorContext or error Object, and there's functions on it which are called later on.

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 29]
```diff
@@ -35,6 +44,58 @@ export const useStocktakeLineEdit = (
       })
     );
 
+  const save = async () => {
+    let result;
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts:48]: I like early returns. 
All the same - this syntax we haven't used elsewhere, and we've tried to avoid mutable variables, so I would put the whole `save` function body inside the `try` block and have `const result = await mutateAsync(draftLines);`

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx [hunk 30]
```diff
@@ -0,0 +1,63 @@
...
+} from '../api';
+
+export type StocktakeLineError =
+  | AdjustmentReasonNotProvidedErrorFragment
+  | StockLineReducedBelowZeroErrorFragment
+  | AdjustmentReasonNotValidErrorFragment
+  | SnapshotCountCurrentCountMismatchErrorFragment;
+
+const useStocktakeLineErrors = () => {
+  const [errors, setErrors] = useState<{
```
Comment (mark-prins) [inline client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:17]: if this approach is used in another area, much of the context would be repeated.. I could see a lot of it being made generic - just passing in the `StocktakeLineError` type and using that throughout. I think not now.. we can do that as needed

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx (hunk 17 above)
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:48]: I'm not sure why the context wouldn't be valid 🤷  
throwing an error here would just give the fallback 'Oops! something's gone wrong' screen.. so is ok

File: client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx (hunk 18 above)
Comment (mark-prins) [reply client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:42]: yes, that was the intention. bit weird having the select enabled but empty - could you disable it?

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx [hunk 31]
```diff
@@ -57,8 +63,10 @@ const useStatusChangeButton = () => {
     'lines',
   ]);
   const { mutateAsync } = useStocktake.document.update();
-  const { success, error } = useNotification();
-  const t = useTranslation('replenishment');
+  const { success, error: errorNotification } = useNotification();
+  const t = useTranslation(['replenishment', 'inventory']);
```
[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx:67]: and the multiple namespace array isn't working for me (bug in the package, the usage is in the documentation but has never worked). 
I don't see the correct error

File: client/packages/common/src/intl/locales/en/inventory.json [hunk 32]
```diff
@@ -7,7 +7,11 @@
   "error.no-stocktakes": "There are no Stocktakes to display.",
   "error.no-stocktake-items": "No items have been added to this stocktake.",
   "error.stocktake-not-found": "Stocktake not found",
+  "error.not-editable": "Stocktake is not editable.",
+  "error.is-locked": "Stocktake is locked.",
+  "error.snapshot-total-mismatch": "Snapshot quantity does not match total quantity.",
   "error.provide-reason": "A reason must be provided for any rows which have a difference in the counted number of packs.",
+  "error.provide-valid-reason": "Adjustment reason does not match adjustment direction",
   "error.reduced-below-zero": "Stock line exist in new outbound shipments. The quantity cannot be reduced below zero.",
   "error.stocktake-has-stock-reduced-below-zero": "Stock take cannot be finalised because there are stock lines which exist in new outbound shipments.",
```
Comment (mark-prins) [inline client/packages/common/src/intl/locales/en/inventory.json:16]:
```suggestion
  "error.stocktake-has-stock-reduced-below-zero": "Stock take cannot be finalised because some of the stock has been used in new outbound shipments.",
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
🎉  wooo! thanks, that's a comprehensive implementation. As a user, it's very nice to use with good feedback and specific indications

I have a few minor concerns which are mainly stylistic and matters of consistency.

File: client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx (hunk 4 above)
Comment (andreievg) [reply client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx]: 821eca6e54de0fc016291143e10c47acf5547f5a

File: client/packages/common/src/ui/layout/tables/columns/types.ts [hunk 33]
```diff
@@ -75,6 +76,9 @@ export interface Column<T extends RecordWithId> {
   sortInverted: boolean;
   getSortValue?: (row: T) => string | number;
 
+  isError?: (row: T) => boolean;
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/common/src/ui/layout/tables/columns/types.ts]: I agree (and found it bad naming, but forgot to change), thanks for suggestion: 821eca6e54de0fc016291143e10c47acf5547f5a

File: client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx (hunk 3 above)
Comment (andreievg) [reply client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx:20]: new issue created: https://github.com/openmsupply/open-msupply/issues/1256

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx (hunk 9 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: I was playing around with existing common utility methods (lodash), and it's very nice. It would mean we would need to be familiar with generic utility functionality vs repo specific utility functions. Slightly more code at invocation end when using lodash but less code in general (since helper method would need to deal with generic types).
9e79f407c2f86cf022f4aa56209f5c07a697b670

And the diff between consuming lodash and generics method would be:
```diff
-        // ids = { stockLineId: stocktakeLineId }
-        const ids = mapValues(
-          mapKeys(lines.nodes, line => line.stockLine?.id),
-          'id'
-        );
-        // mappedErrors = { stockLineId: StockLineReducedBelowZero }
-        const mappedErrors = mapKeys(
+        const mappedErrors = mapErrorsForObject(
+          lines.nodes,
           error.errors,
-          line => ids[line.stockLine.id]
+          (error, stocktakeLine) =>
+            error.stockLine.id === stocktakeLine.stockLine.id
         );
 
         errors.setErrors(mappedErrors);
```

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx (hunk 11 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx:118]: Can we leave it for now and maybe do the change if we touching the area ? At least we are of a similar opinion on this front, I've left a comment:

94e3ae2b1d270cc21f62dc293e8e3845481ab03f

File: client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx (hunk 18 above)
Comment (andreievg) [reply client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx:42]: that would work nicely, especially now that the reason would be adjusted to `null` when adjustment changes from negative/positive to nothing: 163176cec3c2200547534f26e3321f2a96e355a8

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 34]
```diff
@@ -173,6 +176,12 @@ export const useStocktakeColumns = ({
         description: 'description.snapshot-num-of-packs',
         align: ColumnAlign.Right,
         Cell: PositiveNumberCell,
+        isError: row => {
+          let rows = 'lines' in row ? row.lines : [row];
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts]: Although I think it's pretty simple atm, it looks like it's the pattern we went with here and in `OutboundShipment`:

```
if ('lines' in row)
   const { lines } = row;
// ...
else
// ...
```

Generic helper looks a little bit simpler type wise: 5df04bfb4f52c1d8e467c3cf953260a5cbbde490, although I am not sure if it's worth it

The `hasTypename` method isn't quite right (`row` doesn't actually have __typename), it's in the error, also we want to preserve union type on the error (rather then it just being an object with `string` __typename).

Screenshot 2023-03-01 at 4 25 14 PM

And auto complete in current logic: 

Autocomplete

File: client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx (hunk 30 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/context/stocktakeLineError.tsx:17]: Yeah I agree ! We could have generic methods that we use to construct typed context (otherwise we loose the typing)

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts [hunk 35]
```diff
@@ -326,13 +343,17 @@ export const useExpansionColumns = (): Column<StocktakeLineFragment>[] =>
       width: 150,
       label: 'label.snapshot-num-of-packs',
       align: ColumnAlign.Right,
+      isError: rowData =>
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts]: https://github.com/openmsupply/open-msupply/commit/5df04bfb4f52c1d8e467c3cf953260a5cbbde490

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx (hunk 31 above)
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: > I don't see the correct error

Moved `message.saved`: a5f43fd39baf631a9c9869f0ff81ad26b61f1fd8
Moved `messages.confirm-status-as` (looks like it had duplicates in another namespace): 8ee35c711a3f0b349b579d9fa7678a858ad8b3d8
Make sure `inventory` is alway single namespace in `useTranslation`: fecb5b16add6368efa2e31957b9c4178d65b17ac

I've also noted that we have other places where `useTranslation` takes an array, see below, are there any problematic ones ?
Screenshot 2023-03-01 at 5 30 40 PM

I am still can't see practical benefits of splitting translations if the server does gzipping, and the package we use only requests translations for current language. Single file would be much easier to administer and use. (looks like we already getting repeats and we are not protected by type system so have to check everything manually or risk runtime logic errors, see diff below it compiles, we would be protected from this by single file)

```diff
 export const useGetPageTitle = () => {
-  const t = useTranslation('app');
+  const t = useTranslation('inventory');
   const getPageTitle = (route: string) => {
     const mappedRoute = EnvUtils.mapRoute(route);
     return mappedRoute.title
       ? `${t(mappedRoute.title)} | ${t('app')} `
-      : t('app');
+      : // From replenishment
+        t('heading.stock-charges');
   };
 
   return getPageTitle;
```

File: client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts (hunk 34 above)
[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts]: yeah, probably not worth the change. There's not a lot of logic being repeated

**Comment by mark-prins** [comment]
thanks for changes - looking pretty sweet!

**Review by mark-prins — APPROVED** [review]

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts [hunk 36]
```diff
@@ -1,31 +1,40 @@
...
   update: (patch: RecordPatch<StocktakeLineFragment>) => void;
   addLine: () => void;
-  save: (lines: DraftStocktakeLine[]) => Promise<UpsertStocktakeLinesMutation>;
+  save: () => Promise<{ errorMessages?: string[] }>;
   isLoading: boolean;
   nextItem: ItemRowFragment | null;
-  isError: boolean;
 }
 
+export const errorMessage = (error: unknown): string => {
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: Yeah for sure should be in common area, moved and renamed: 9e759ab117ff5794944ba8853499c9db3edf4c6f

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx [hunk 37]
```diff
@@ -72,16 +80,61 @@ const useStatusChangeButton = () => {
...
+    errors.unsetAll();
+    let result;
+    try {
+      result = await mutateAsync({ id, status: selectedOption.value });
+    } catch (e) {
+      return errorNotification(errorMessage(e))();
+    }
+
     if (result.__typename === 'StocktakeNode') {
       return success(t('messages.saved'))();
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: I added method/s `mapStructuredError/s` now they are more consistent (both return errorMessage), I think this helps: e58e8dc9cf3f2b8e680a0954fd6e90165ae51729

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx [hunk 38]
```diff
@@ -48,14 +47,16 @@ export const StocktakeLineEdit: FC<StocktakeLineEditProps> = ({
...
-  const { setRowStyle } = useRowStyle();
+  const { setRowStyles } = useRowStyle();
   const { error } = useNotification();
-  const t = useTranslation(['inventory']);
 
   const onNext = async () => {
-    await save(draftLines);
+    let { errorMessages } = await save();
+    if (errorMessages)
+      return errorMessages.forEach(errorMessage => error(errorMessage)());
```
[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx]: Ok, i'll avoid this in the future, I've been doing this quite a bit but I can see it can be confusing:
1bf5a6081320fbd5d97a9e53daf8d8c082d778cb

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx (hunk 23 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx]: 🙏 7799f65a5f7bef3faa0f539a9be0209c46d9fc82

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 24 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: https://github.com/openmsupply/open-msupply/pull/1252#discussion_r1121131462

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 25 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: 🙏 it was renamed here: e58e8dc9cf3f2b8e680a0954fd6e90165ae51729

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 26 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: cfe481f9f56dabfd7dcef924b1bc70caf8a818b6

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 27 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: cfe481f9f56dabfd7dcef924b1bc70caf8a818b6, I think I am used to typescript complaining about this, do we have this switched of ? or is my TS misconfigured ?

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 28 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: `errorsContext` is much better thanks: 590d2924b5052b147580df86e7dc3c650a1ceb21

File: client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts (hunk 29 above)
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts]: Changed it here: e58e8dc9cf3f2b8e680a0954fd6e90165ae51729

File: client/packages/common/src/intl/locales/en/inventory.json (hunk 32 above)
Comment (andreievg) [reply client/packages/common/src/intl/locales/en/inventory.json:16]: 🙏 much better

**Comment by andreievg** [comment]
@mark-prins thanks for review, I've made changes to most of what you've requested, still would like a response on this one: https://github.com/openmsupply/open-msupply/pull/1252#discussion_r1121131462

Will merge tomorrow,

I also played around with some `result` types, I kind of like it, but it would add another way to handle errors, so not convinced it's worth adding, benefits: consistent and prescribed error handling, reduces ambiguity in result (if error), can do try catch and early return without mutating result. Anyways here is an example, :

```diff
+
+type Ok<T> = { isOk: true; isErr: false; value: T; error?: unknown };
+type Error<E> = { isOk: false; isErr: true; error: E; value?: unknown };
+export type Result<T = void, E = unknown> = Ok<T> | Error<E>;
+
+export const ok = <T = void>(value: T): Ok<T> => ({
+  isOk: true,
+  isErr: false,
+  value,
+});
+
+export const emptyOk = (): Ok<void> => ({
+  isOk: true,
+  isErr: false,
+  value: undefined,
+});
+
+export const err = <E>(error: E): Error<E> => ({
+  isOk: false,
+  isErr: true,
+  error,
+});
+
+export const catchResult = async <T = void, E = unknown>(
+  fn: () => Promise<T>,
+  errorMapper: (error: unknown) => E
+): Promise<Result<T, E>> => {
+  try {
+    return ok(await fn());
+  } catch (e) {
+    return err(errorMapper(e));
+  }
+};
diff --git a/client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx b/client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
index 99a2a0562..7dc75e7cc 100644
--- a/client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
+++ b/client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
@@ -10,6 +10,10 @@ import {
   StocktakeNodeStatus,
   noOtherVariants,
   getErrorMessage,
+  catchResult,
+  Result,
+  emptyOk,
+  err,
 } from '@openmsupply-client/common';
 import { getNextStocktakeStatus, getStatusTranslation } from '../../../utils';
 import { useStocktake } from '../../api';
@@ -61,10 +65,10 @@ const useStatusChangeButton = () => {
     'lines',
   ]);
   const { mutateAsync: save } = useStocktake.document.update();
-  const { success, error } = useNotification();
+  const notification = useNotification();
   const t = useTranslation('inventory');
 
-  const errorsContext = useStocktakeLineErrorContext();
+  const errors = useStocktakeLineErrorContext();
 
   const options = useMemo(
     () => getStatusOptions(getButtonLabel(t)),
@@ -78,18 +82,22 @@ const useStatusChangeButton = () => {
 
   const mapStructuredErrors = (
     result: Awaited<ReturnType<typeof save>>
-  ): /*error*/ string | /*OK*/ undefined => {
+  ): Result<void, string> => {
+    errors.unsetAll();
     if (result.__typename === 'StocktakeNode') {
-      return /*OK*/ undefined;
+      return emptyOk();
     }
 
     const { error } = result;
 
     // General errors
-    if (error.__typename === 'CannotEditStocktake')
-      return t('error.not-editable');
+    if (error.__typename === 'CannotEditStocktake') {
+      return err(t('error.not-editable'));
+    }
 
-    if (error.__typename === 'StocktakeIsLocked') return t('error.is-locked');
+    if (error.__typename === 'StocktakeIsLocked') {
+      return err(t('error.is-locked'));
+    }
 
     // By line errors
     switch (error.__typename) {
@@ -108,37 +116,46 @@ const useStatusChangeButton = () => {
           line => ids[line.stockLine.id]
         );
 
-        errorsContext.setErrors(mappedErrors);
-        return t('error.stocktake-has-stock-reduced-below-zero');
+        errors.setErrors(mappedErrors);
+        return err(t('error.stocktake-has-stock-reduced-below-zero'));
 
       case 'SnapshotCountCurrentCountMismatch':
-        errorsContext.setErrors(
+        errors.setErrors(
           mapValues(keyBy(error.lines.nodes, 'id'), () => error)
         );
 
-        return t('error.snapshot-total-mismatch');
+        return err(t('error.snapshot-total-mismatch'));
 
       default:
         noOtherVariants(error);
     }
+
+    return emptyOk();
   };
 
   const onConfirmStatusChange = async () => {
     if (!selectedOption) return null;
 
-    errorsContext.unsetAll();
-    try {
-      const result = await save({ id, status: selectedOption.value });
+    const {
+      isOk,
+      error: errorMessage,
+      value,
+    } = await catchResult(
+      () => save({ id, status: selectedOption.value }),
+      getErrorMessage
+    );
 
-      let errorMessage = mapStructuredErrors(result);
+    if (!isOk) {
+      notification.error(errorMessage)();
+      return;
+    }
+
+    const { isErr, error } = mapStructuredErrors(value);
 
-      if (errorMessage) {
-        error(errorMessage)();
-      } else {
-        success(t('messages.saved'))();
-      }
-    } catch (e) {
-      error(getErrorMessage(e))();
+    if (isErr) {
+      notification.error(error)();
+    } else {
+      notification.success(t('messages.saved'))();
     }
   };
```

File: client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx (hunk 31 above)
[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: Two practical benefits:
- download size; you only download the translation bundle which relates to the area of the site that you're working in
- developer contention; we add translations in nearly every f/e PR and if all developers are using the same file then there is more chance of conflicting

the download size aspect is unlikely to be a huge practical benefit - can't see it likely that someone would work only in 'inventory' areas and not need the other namespaces. And we cache the files, so once you've downloaded you don't need to fetch again.

My main reason for keeping separate files is the size. A single file would be huge, which is clumsy to work with, and leads to more developer conflicts. We have conflicts due to whitespace and formatting differences ( we already have this with weblate ), and to the personal preferences of alphabetical ordering and if all translations are in a single file then the conflicts increase.

Yes, we can work around with linting, and if I can figure out the formatter that weblate is using etc.
Even so, not entirely sold on a single file yet - though concerns have been raised previously about the arbitrary splitting up of translations. the web app areas that I've gone with don't make sense for everyone.

a better explanation is on the [i18next site](https://www.i18next.com/principles/namespaces)

[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: > are there any problematic ones ?

Potentially 2,3,4,5 are. can't say without looking at each file and finding which translations are in use. Quicker to just fix them up. I'd recommend a separate issue though.

Note that there's also scripts to check translation usage:

```
yarn i18n-unused-display
yarn i18n-unused-remove
yarn i18n-missing
```

[the remark this answers is not in the document]
Comment (andreievg) [reply client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx]: 🙏 @mark-prins, https://github.com/openmsupply/open-msupply/issues/1266
