### PR TITLE
1326 arv section update

### LINKED ISSUE #1326: Programs: HIV Care & Treatment Encounter ARV / Medication
## What went wrong? 😲

The values for `Regimen Change Reason` do not depend on the value selected for `Regimen Status`

Note: there are `Regimen Change Reason` for all Regimen Status

## Expected behaviour 🤔

- [x] The values for `Regimen Change Reason` should depend on the value selected for `Regimen Status` as per [this table](https://docs.google.com/spreadsheets/d/17rON9mmUjPQzYbPlaTr1IYFJ68YowvsqX7hNx4n000E/edit#gid=1338315103&range=A1)
- [x] `Regimen Change reason` to be renamed to `Regimen reason` cause you can enter a reason for any of the status, not only when there is a "change"

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Dispensary' > 'Patients' > 'Encounters' tab
2. Select an HIV Care Encounter
3. Click on 'ARV / Medication' section
4. Select a Regimen status from the DDL
6. See error

## Your environment 🌱
 - Version 1.1.4
 - Platform: https://demo-open.msupply.org:88/

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1326 

# 👩🏻‍💻 What does this PR do? 
- Add a conditional filter for the Select component. (as needed for the issue)
- Fix custom errors

# 🧪 How has/should this change been tested? 

- Select ARV status and reason
- Change status and check that reason list is updated
- If an invalid reason for the current status is selected an error is shown
- If you have an invalid reason for the CONTINUE status there are no other options in the list and you have to clear the field to make the error go a await, is this intuitive enough?

### CODE REVIEW

**Comment by CarlosNZ** [comment]
> * If you have an invalid reason for the CONTINUE status there are no other options in the list and you have to clear the field to make the error go a await, is this intuitive enough?

Maybe it's best to *hide* the "Regimen Reason" field when "Continue" is selected to avoid this problem altogether?

**Comment by CarlosNZ** [comment]
Can you just clarify one thing for me -- how is the Select component with the `fieldFilter` property different to the "Conditional Select" component?

File: client/packages/programs/src/JsonForms/common/components/Select.tsx [hunk 1]
```diff
@@ -168,22 +185,69 @@ const getHighlightParts = (
...
+    if (current !== undefined && !filtered.includes(current)) {
+      setVisibleItems([current, ...filtered]);
+      setError('Please select a valid option');
+    } else {
+      setVisibleItems(filtered);
+      setError(undefined);
+    }
+  }, [options, current, conditionField]);
+
+  useEffect(() => {}, [current, visibleItems]);
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/Select.tsx:218]: ` useEffect(() => {}, [current, visibleItems]);`
Assume this shouldn't be here?

File: client/packages/programs/src/JsonForms/common/components/Select.tsx [hunk 2]
```diff
@@ -168,22 +185,69 @@ const getHighlightParts = (
...
+  const [visibleItems, setVisibleItems] = useState(items ?? []);
+
+  const conditionField = extractProperty(
+    core?.data ?? {},
+    options?.fieldFilter?.field ?? ''
+  );
+  useEffect(() => {
+    if (!items || !options?.fieldFilter) {
+      return;
+    }
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/Select.tsx:206]: Maybe it would be a bit clearer to escape early when there's no `conditionField`, as none of the mapping stuff applies:
```
if (!conditionField) {
  setVisibleItems(items)
  setError()
  return
}

```

File: client/packages/programs/src/JsonForms/common/components/Select.tsx [hunk 3]
```diff
@@ -168,22 +185,69 @@ const getHighlightParts = (
   );
 };
 
+/** Either the full list or the narrowed list from conditional option */
+
+const useFilteredItems = (
+  items: string[] | undefined,
+  current: string | undefined,
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/Select.tsx:192]: Maybe these variables could be called `allItems` and `currentItems` - it makes it clearer that one is a subset of the other.

**Review by CarlosNZ — COMMENTED** [review]
Looks pretty good thanks. I just have a couple of questions and suggestions -- see comments :)

**Comment by clemens-msupply** [comment]
> > * If you have an invalid reason for the CONTINUE status there are no other options in the list and you have to clear the field to make the error go a await, is this intuitive enough?
> 
> Maybe it's best to _hide_ the "Regimen Reason" field when "Continue" is selected to avoid this problem altogether?

Yes good point, this was what it was before. I then realized the problem the you can select a reason then change the status to "Continue" and as a result you have an invalid reason set in the data.

We might have an option to clear fields on certain conditions? Anyway its probably not much of an issue since you wouldn't usually do this...

Since it doesn't make sense to have an empty dropdown I will just hide it again...

**Comment by clemens-msupply** [comment]
> Can you just clarify one thing for me -- how is the Select component with the `fieldFilter` property different to the "Conditional Select" component?
> 
> They almost seem like two different ways to do the same thing.

Yes this was my first reaction as well and I actually tried to merge them. However, the ConditionalSelect component works on a `string` while the Select component works on a predefined `enum`, i.e. a `string[]`. For the later I have some predefined options from the schema while for the former the is just an arbitrary string which is restricted only in the UI

- Select: schema defined enum which can be further narrowed down in the UI
- ConditionalSelect: arbitrary string in the schema but its value is restricted by a selection provided in the UI

I added a comment in the ConditionalSelect component, is this clear enough?

File: client/packages/programs/src/JsonForms/common/components/Select.tsx (hunk 3 above)
Comment (clemens-msupply) [reply client/packages/programs/src/JsonForms/common/components/Select.tsx:192]: thanks I called it currentSelection and added some more in the comment

File: client/packages/programs/src/JsonForms/common/components/Select.tsx (hunk 2 above)
Comment (clemens-msupply) [reply client/packages/programs/src/JsonForms/common/components/Select.tsx:206]: I can't return before a hook but I added the "unset" calls in the the useEffect hook

**Comment by CarlosNZ** [comment]
> Yes good point, this was what it was before. I then realized the problem the you can select a reason then change the status to "Continue" and as a result you have an invalid reason set in the data.

Yeah, I actually think this is a flaw in JSON Forms -- IMHO when an item goes invisible, its data should be removed (or at least there should be an option to do so). I might post on the JSON Forms discussion or repo and see what the thinking is behind this.

**Comment by CarlosNZ** [comment]
> * Select: schema defined enum which can be further narrowed down in the UI
> 
>     * ConditionalSelect: arbitrary string in the schema but its value is restricted by a selection provided in the UI
> 
> 
> I added a comment in the ConditionalSelect component, is this clear enough?

Yeah, that makes sense, but I think the naming is a little unclear -- after all, they can both be "conditional".

It might be too much hassle to change them, but perhaps "ConditionalSelect" could be called "RestrictedTextSelect" or something similar? -- the "Conditional" feature is just a bonus (like it is in the standard Select) -- it's the fact that it's for a string field that is the defining quality that differentiates it from the normal Select, I think.

But not a big deal, I just think it's potentially confusing.

File: client/packages/programs/src/JsonForms/common/components/Select.tsx (hunk 2 above)
Comment (CarlosNZ) [reply client/packages/programs/src/JsonForms/common/components/Select.tsx:213]: Yeah, I meant return early *within* the useEffect hook:
```ts
useEffect(() => {
    if (!allItems || !options?.fieldFilter) {
      setVisibleItems(allItems ?? []);
      setError(undefined);
      return;
    }

    if (!conditionField) {
      setVisibleItems(items)
      setError(undefined)
      return
    }

   // The following only applies if we have a condition to deal with:
    const mapping = options.fieldFilter.mapping[conditionField] ?? [];
    const filtered = allItems.filter(item => mapping.includes(item));
    if (
      currentSelection !== undefined &&
      !filtered.includes(currentSelection)
    ) {
      setVisibleItems([currentSelection, ...filtered]);
      setError('Please select a valid option');
    } else {
      setVisibleItems(filtered);
      setError(undefined);
    }
```

File: client/packages/programs/src/JsonForms/common/components/Select.tsx [hunk 4]
```diff
@@ -168,22 +185,78 @@ const getHighlightParts = (
   );
 };
 
+/**
+ * Returns either the full list or the narrowed list from conditional option.
+ *
+ * If, after applying the filter condition, the currentSelection is not in the filtered list
+ * the currentSelection item is added to the returned list and an error message is returned.
+ */
```
Comment (CarlosNZ) [inline client/packages/programs/src/JsonForms/common/components/Select.tsx:193]:
```suggestion
/**
 * Returns either the full list or the narrowed list from conditional option.
 *
 * If, after applying the filter condition, the currentSelection is not in the
 * filtered list the currentSelection item is added to the returned list and an
 * error message is returned.
 */
```

The line wrapping is weird on mine -- this is how my comment auto-formatter breaks it up.

**Review by CarlosNZ — APPROVED** [review]
Looks good, thanks. Some minor suggestions, nothing important. (Have a think about the naming, we can change it later if we think of a better name)

File: client/packages/programs/src/JsonForms/common/components/Select.tsx (hunk 2 above)
Comment (clemens-msupply) [reply client/packages/programs/src/JsonForms/common/components/Select.tsx:213]: Ok I see, thanks I leave it though to reduce the number of setError, setVisibleItems...

**Comment by clemens-msupply** [comment]
Thanks for the review!
