### PR TITLE
2270 display long medicine names

### LINKED ISSUE #2270: Long medicine names are not able to be fully displayed
## What went wrong? 😲
Unable to see full medicine names for longer items 
Screenshot 2023-09-21 at 4 21 02 PM

## Expected behaviour 🤔
Would need to see the full name of the drug for users to know what they are supplying or dispensing 

1. ?Expect to be able to as a user drag the column out to see the entire description or hover over the item and have the full name appear in the list page
Screenshot 2023-09-22 at 9 24 43 AM

3. when selecting on the item would expect to be able to see the full name of the medicine. note also some medicine names can be very long (e.g. HIV meds like: efavirenz 600 mg + emtricitabine 200 mg + tenofovir disoproxil maleate 300 mg ) so maybe the text should adjust itself to fit to size of the row instead of being the same font size and the row be made longer? 

Screenshot 2023-09-22 at 9 21 02 AM

## How to Reproduce 🔨
No

## Your environment 🌱
 Desktop v 1.3

## Agreed solution 
- expand the width of the item name in the modal, make the top half of the modal bigger to allow shifting down the Unit-pack toggle
- add a tooltip over the item names column in the listboxes

### PR DESCRIPTION
**Pull request by fergie-nz**
Fixes #2270 

# 👩🏻‍💻 What does this PR do? 
Adds a number of tooltip and ui changes.

# 🧪 How has/should this change been tested? 
You can view the changes in inbound shipments -> Internal orders:

Firstly tooltips have been added to list items where name is a longer string:
8CC5F219-4E2E-43A5-89F5-5F899DA3A9A7

After selecting a detail view of a specific item, the modal is adjusted to give more space for the selected item name string:
FD70A135-B857-4288-B663-8D3BBB156EFD

A tooltip is also added for this text in case the name string is still too long:

FCD98D90-38E7-4BD9-9566-C2DC2F7BFFA6

Additionally, when selecting an item to be added, the name string is wrapped rather than running off the screen:

9E49FC2F-2ABC-4088-9402-4BE5B2DFE6BC

Finally a tooltip is also added to another item list in Inventory -> stock

4A4ACDF4-4ED1-4935-8EA0-547DF236BFA8

## 💌 Any notes for the reviewer?
CSS grid management refactor in the RequestLineEditForm component felt overly complex and awkward, but I couldn't manage a way to simply make the changes requested.

### CODE REVIEW

File: client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx [hunk 1]
```diff
@@ -32,6 +34,24 @@ const useHighlightPlaceholderRows = (
...
+          overflow: 'hidden',
+          textOverflow: 'auto',
+        }}
+      >
+        {String(itemName)}
+      </div>
+    </Tooltip>
+  );
+};
+
```
Comment (fergie-nz) [inline client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx:54]: This feels like it could be a generic component, however the type being passed to the item cell is different for two different lists, so I've made it twice.

I wonder if anyone knows how I could make this accept either type / be generic?

Comment (fergie-nz) [reply client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx:54]: Further to this, where it is shared between two lists (Inventory/Stock, and Internal Order), I wasn't sure where to put it. 

So have arbitrarily placed it in the StockListComponent, and then imported into the column file of RequestRequisitions.

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx [hunk 2]
```diff
@@ -65,18 +67,24 @@ export const RequestLineEditFormLayout = ({
...
+          direction="row"
+          justifyContent="space-between"
+        >
+          <Grid item xs={6}>
+            {Left}
+          </Grid>
+          <Grid item xs={6}>
+            {Middle}
+          </Grid>
+        </Grid>
```
Comment (fergie-nz) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:87]: Maybe this is okay - but felt a bit janky and fragile.

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx [hunk 3]
```diff
@@ -220,8 +229,8 @@ export const RequestLineEditForm = ({
             InputProps={{
               sx: { backgroundColor: theme => theme.palette.background.menu },
             }}
-            minRows={6}
-            maxRows={6}
+            minRows={6.2}
+            maxRows={6.2}
```
Comment (fergie-nz) [inline client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:233]: I also wanted to make this dynamic to fit the size of neighbouring grid components. 
I couldn't figure out an easy way to do this, however.

I've left it hard coded as it previously was, but adjusted it to align heights for the new layout.

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx (hunk 2 above)
Comment (mark-prins) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:87]: I think it's ok - it was a little janky to begin with.
Don't think that it's fragile - though it does mess with the `left`, `right` etc now that there's a `top` in the mix..

The form is looking a little cramped now - I wondered about lining up the two stacks of label:value pairs like this:

image

by changing the left bit:

```
<Grid
            item
            xs={6}
            flexDirection="column"
            display="flex"
            justifyContent="flex-end"
          >
```

File: client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx (hunk 3 above)
Comment (mark-prins) [reply client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx:233]: not sure if that's possible - couldn't see how to do that with the multiline prop set on a TextField without setting rows / minRows / maxRows.
I'd suggest `rows={6.2}` though it needs a change to TextArea to prevent a console warning:

```
export const TextArea: FC<StandardTextFieldProps> = ({
  value,
  onChange,
  maxRows = 4,
  minRows = 4,
  InputProps,
  rows,
  ...props
}) => (
  <BasicTextInput
    sx={{ width: '100%' }}
    InputProps={{
      ...InputProps,
      sx: {
        backgroundColor: 'white',
        ...InputProps?.sx,
      },
    }}
    multiline
    value={value}
    onChange={onChange}
    maxRows={rows ? undefined : maxRows}
    minRows={rows ? undefined : minRows}
    rows={rows}
    {...props}
  />
);
```

and I've suggested this before.. but perhaps in an as yet unmerged PR? I can't find it anyway..

File: client/packages/system/src/Item/ListView/ListView.tsx [hunk 4]
```diff
@@ -38,10 +40,35 @@ const ItemListComponent: FC = () => {
...
+        </div>
+      </Tooltip>
+    );
+  };
+
   const columns = useColumns<ItemWithStats>(
     [
       'code',
-      'name',
+      {
```
Comment (mark-prins) [inline client/packages/system/src/Item/ListView/ListView.tsx:64]: we'd normally override the existing column definition, and just include the required difference. In this case, the column still needs to be sortable, and the label should be 'name'.. so..

```
      [
        'name',
        {
          Cell: TooltipTextCell,
          maxWidth: 350,
        },
      ],
```

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 5]
```diff
@@ -69,7 +88,14 @@ const StockListComponent: FC = () => {
         align: ColumnAlign.Center,
       },
       ['itemCode', { accessor: ({ rowData }) => rowData.item.code }],
-      ['itemName', { accessor: ({ rowData }) => rowData.item.name }],
+      {
```
Comment (mark-prins) [inline client/packages/system/src/Stock/ListView/ListView.tsx:91]: I'd prefer to have the existing override: 
```
      [
        'itemName',
        {
          accessor: ({ rowData }) => rowData.item.name,
          Cell: ItemCell,
          maxWidth: 350,
        },
      ],
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
🎉  that's much better thanks!
Addresses the immediate concern, and for the inbounds that works nicely on web and android. 
It would be even better if you could you make the change to inbound and outbound shipments and client/response requisitions. They also struggle and would be better with a tooltip on the item name.

I've played around and have lifted out the new cell into a common area - so that it can be used in the other list views too. I think it will be a useful addition, so wanted it in a common place:

[2270-display-long-medicine-names...2270-display-long-medicine-names-suggestion](https://github.com/openmsupply/open-msupply/compare/2270-display-long-medicine-names...2270-display-long-medicine-names-suggestion)

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 6]
```diff
@@ -58,6 +59,24 @@ const StockListComponent: FC = () => {
     />
   );
 
+  const ItemCell = <T extends StockLineRowFragment>({
```
Comment (mark-prins) [inline client/packages/system/src/Stock/ListView/ListView.tsx:62]: how did we miss this one? Can you remove the `ItemCell` please 🙏

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 7]
```diff
@@ -69,7 +88,14 @@ const StockListComponent: FC = () => {
         align: ColumnAlign.Center,
       },
       ['itemCode', { accessor: ({ rowData }) => rowData.item.code }],
-      ['itemName', { accessor: ({ rowData }) => rowData.item.name }],
+      [
+        'itemName',
+        {
+          accessor: ({ rowData }) => rowData.item.name,
+          Cell: ItemCell,
```
Comment (mark-prins) [inline client/packages/system/src/Stock/ListView/ListView.tsx:95]:
```suggestion
          Cell: TooltipTextCell,
```

File: client/packages/system/src/Stock/ListView/ListView.tsx [hunk 8]
```diff
@@ -58,6 +59,24 @@ const StockListComponent: FC = () => {
...
+  const ItemCell = <T extends StockLineRowFragment>({
+    rowData,
+  }: CellProps<T>): React.ReactElement<CellProps<T>> => {
+    const itemName = rowData.item.name;
+    return (
+      <Tooltip title={String(itemName)} placement="bottom-start">
+        <div
+          style={{
+            overflow: 'hidden',
+            textOverflow: 'auto',
```
Comment (mark-prins) [inline client/packages/system/src/Stock/ListView/ListView.tsx:71]: Sorry! Didn't notice this before.. I really like having the ... when the text is truncated
```suggestion
            textOverflow: 'ellipsis',
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
🙏 thanks for making the changes - I think it looks great!
One small thing I missed - I'd prefer to have ellipses added when the text is truncated.. like this:

image

and I spotted another place where the `ItemCell` was still used.

**Review by mark-prins — APPROVED** [review]
🙏  thanks for the changes. Looks great!
