### PR TITLE
1702 When editing stock, the location field doesn't retain the new location choice when there is already an assigned location

### LINKED ISSUE #1702: When editing stock, the location field doesn't retain the new location choice when there is already an assigned location
## What went wrong? 😲
 
As title however the location that has been chosen has been saved even though the old location is still displayed in the list. It is working if you selected a location for the first time.
location selected is not the right one

## Expected behaviour 🤔
The new location chosen should be the one selected in the list

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to "Show stock"
2. Click on a line that has already a location assigned to it
3. Try to change the location
4. See error. The new selected location is not the one selected in the list

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [e.g. windows desktop]

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1702 

# 👩🏻‍💻 What does this PR do? 
Sets stock location to state, so that it changes on UI when user changes locations

# 🧪 How has/should this change been tested? 
- Have stock line with location already saved 
- Go to edit stock
- Change location and see it reflected in UI

### CODE REVIEW

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 1]
```diff
@@ -163,9 +165,12 @@ export const StockLineForm: FC<StockLineFormProps> = ({ draft, onUpdate }) => {
...
               autoFocus={false}
               disabled={false}
-              value={draft.location ?? null}
+              value={location ?? draft.location ?? null}
               width={160}
-              onChange={location => onUpdate({ locationId: location?.id })}
+              onChange={(location) => {
+                onUpdate({ locationId: location?.id });
+                setLocation(location);
+              }}
```
Comment (mark-prins) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:173]:
```suggestion
              onChange={location => {
                onUpdate({ location, locationId: location?.id });
              }}
```

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 2]
```diff
@@ -163,9 +165,12 @@ export const StockLineForm: FC<StockLineFormProps> = ({ draft, onUpdate }) => {
             <LocationSearchInput
               autoFocus={false}
               disabled={false}
-              value={draft.location ?? null}
+              value={location ?? draft.location ?? null}
```
Comment (mark-prins) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:168]:
```suggestion
              value={location}
```

File: client/packages/system/src/Stock/Components/StockLineForm.tsx [hunk 3]
```diff
@@ -49,6 +50,7 @@ export const StockLineForm: FC<StockLineFormProps> = ({ draft, onUpdate }) => {
   const supplierName = draft.supplierName
     ? draft.supplierName
     : t('message.no-supplier');
+  const [location, setLocation] = useState<LocationRowFragment | null>();
```
Comment (mark-prins) [inline client/packages/system/src/Stock/Components/StockLineForm.tsx:53]:
```suggestion
  const location = draft.location ?? null;
```

**Review by mark-prins — CHANGES_REQUESTED** [review]
The state isn't required - would you mind changing please?
The problem is that the component isn't re-rendering because the `location` on draft is being used for the value, but we are updating the `locationId`
changing this, so that the `location` is updated on the draft, is all that's required to make it work

File: client/packages/system/src/Stock/Components/StockLineForm.tsx (hunk 3 above)
Comment (roxy-dao) [reply client/packages/system/src/Stock/Components/StockLineForm.tsx]: [d7cb9a7](https://github.com/openmsupply/open-msupply/pull/1716/commits/d7cb9a7784e636ac1ef5f46c343021b8eed6ff84) 🙏🏻

**Review by mark-prins — APPROVED** [review]
🙏
