### PR TITLE
#2141 Fix Notes maxAge edit restriction

### LINKED ISSUE #2141: Ignore note maxAge when not set and fix maxAge check
If maxAge is not set in the config, the maxAge check should not be done. Furthermore, there is a hard coded value in the code:

In `packages/programs/src/JsonForms/common/components/Array/Notes.tsx`
```ts
    // Must not be older than `maxAge` days
    if (DateUtils.ageInDays(child.created) >= 1) return false;
```

There were some type changes in https://github.com/openmsupply/open-msupply/pull/2124, i.e. wait till this is merged...

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #2141

# 👩🏻‍💻 What does this PR do? 
 

Updated the check to actually *use* the maxAge value (instead of the hard-coded 1 day), and use `Infinity` as a fallback if `maxAge` is not specified (i.e. can always be edited)

# 🧪 How has/should this change been tested? 

Tested with "Notes" on Patient JSON Form (PNG schema).
- Checked correct behaviour with new notes (can be edited) and after setting the created date to more than one day
- Manually changed UI JsonSchema to remove `maxAge` property --notes are always editable

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx [hunk 1]
```diff
@@ -144,7 +144,11 @@ const NotesComponent = (props: ArrayControlCustomProps) => {
       return false;
 
     // Must not be older than `maxAge` days
-    if (DateUtils.ageInDays(created) >= 1) return false;
+    if (
+      DateUtils.ageInDays(created) >= options['editRestrictions']['maxAge'] ??
+      Infinity
+    )
+      return false;
```
Comment (mark-prins) [inline client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx:151]: What about using the zod typing and update line 65 to

```
  const options = NotesOptions.parse(props.uischema.options);
```

then the options object is correctly typed, and ts forces you to make this change:

```suggestion
    if (
      DateUtils.ageInDays(created) >=
      (options['editRestrictions']['maxAge'] ?? Infinity)
    )
      return false;
```

**Review by mark-prins — COMMENTED** [review]
will parsing the options cause any issues? It seems to work for me

File: client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx (hunk 1 above)
Comment (CarlosNZ) [reply client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx]: Okay, thanks 116702a30

**Review by mark-prins — APPROVED** [review]
👍 Looking good!

File: client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx [hunk 2]
```diff
@@ -62,7 +62,7 @@ const NotesComponent = (props: ArrayControlCustomProps) => {
   const { enabled, data, config } = props;
   const { localisedDateTime } = useFormatDateTime();
 
-  const options = props.uischema.options;
+  const options = NotesOptions.parse(props.uischema.options);
```
Comment (clemens-msupply) [inline client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx:65]: Nit: there is our `useZodOptionsValidation` hook which also returns some validation errors that are a bit nicer formatted and which can be shown in the UI (targeting developer)

Comment (mark-prins) [reply client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx:65]: ooh.. with a `safeParse` that's much nicer 🙏

Comment (CarlosNZ) [reply client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx:65]: Ah, right. Trying to remember why we weren't already using that hook in here -- I think it's because the options object is passed intact to the child `Note` components, and the zod validation is already done there. So didn't want to double up?

Anyway, makes sense to keep the same pattern regardless, so I'll make a small tweak in my next PR and note it. Thanks.
