### PR TITLE
Don't show 0 sync badge

### LINKED ISSUE #1469: Sync badge shouldn't show if there are no records to sync
## What went wrong? 😲
Screen Shot 2023-03-31 at 12 27 42 PM

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1469

# 👩🏻‍💻 What does this PR do? 
 
Fixed when looking at something else, so have put in a PR. Sorry for the distraction.
The problem is that the sync count is coming through as a string, i.e. `'0'` the Badge component won't show `0` by default, but the string is being shown.

Have parsed as a number to prevent the 0 showing.

# 🧪 How has/should this change been tested? 

Take my word for it? 🤷 It's only showing up sometimes. I passed in the value `'0'` to the `badgeContent` prop when testing

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/host/src/components/AppDrawer/SyncNavLink.tsx [hunk 1]
```diff
@@ -18,8 +18,17 @@ export const SyncNavLink = () => {
     POLLING_INTERVAL_IN_MILLISECONDS
   );
 
+  // the Badge does not show if the content is 0
+  // somehow though the numberOfRecordsInPushQueue can be '0' which does show
+  const badgeContent = (
+    !numberOfRecordsInPushQueue
+      ? 0
+      : // parse, after casting to string to satisfy ts
+        Number.parseFloat(`${numberOfRecordsInPushQueue}`)
```
Comment (CarlosNZ) [inline client/packages/host/src/components/AppDrawer/SyncNavLink.tsx:27]: You can just do `Number(numberOfRecordsInPushQueue)`, which also avoids having to do the explicit string conversion.

Is there any difference?

File: client/packages/host/src/components/AppDrawer/SyncNavLink.tsx [hunk 2]
```diff
@@ -18,8 +18,17 @@ export const SyncNavLink = () => {
...
+  ) as React.ReactNode;
+
   const badgeProps = {
-    badgeContent: numberOfRecordsInPushQueue as React.ReactNode,
+    badgeContent,
     max: 99,
```
Comment (CarlosNZ) [inline client/packages/host/src/components/AppDrawer/SyncNavLink.tsx:32]: Just out of interest -- what does it show when there is more than 99?

**Review by CarlosNZ — APPROVED** [review]
Cool, thanks.  👍🏼 

One tiny suggestion.

File: client/packages/host/src/components/AppDrawer/SyncNavLink.tsx (hunk 1 above)
Comment (mark-prins) [reply client/packages/host/src/components/AppDrawer/SyncNavLink.tsx:27]: thanks, yeah. not an important difference in this case and it has reminded me to check for NaN too. 
have changed it up.

File: client/packages/host/src/components/AppDrawer/SyncNavLink.tsx (hunk 2 above)
Comment (mark-prins) [reply client/packages/host/src/components/AppDrawer/SyncNavLink.tsx:32]: just `99+` 😄
