### PR TITLE
1113 enforce sync api version

### LINKED ISSUE #1113: Enforce sync API version
For SYNC use Option 4 from this KDD: https://github.com/openmsupply/open-msupply/pull/1112

* Add API version that remote server uses to constants
* Push this version through headers to server
* Deal with incompatible version error
* Setup documentation of version compatibility (matrix)
* Central server issue (to implement Option 4)
   * Add a constant for current sync V5 version
   * Add a constant for backwards compatible sync V5 version
   * Check sync API version that is being sent by API consumer through header and return error if compatibility mismatch

### LINKED ISSUE #1339: omSupply doesn't send the exact version to cloud server desktop
## What went wrong? 😲
 
If I install version 1.1.4 or 1.1.5 the version I see only the major version number 1.0 instead of the exact version (minor and patch) in the "App version" field of the sync settings window. 

omSupply
image

mSupply
image

The problem might be on the desktop side but put that issue here first to make sure that omSupply send back the right version

## Expected behaviour 🤔

Should probably for our sake what is the major, minor, patch versioning 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install omSupply 1.1.5
2. Put the site credentials and initialise
3. Go back to the cloud and in Special > Sync > your site, check the app version. See error 

## Your environment 🌱
 - Version [e.g. 1.1.4, 1.1.5]
 - Platform [e.g. tablet, desktop for the cloud server]

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1113
Fixes #1339 

requires this 4d branch to test: https://github.com/sussol/msupply/pull/12520 (can work without that branch)

# 👩🏻‍💻 What does this PR do? 

* Added version to sync api which is added to header in sync api request
* Added a new sync error variant `ApiVersionIncompatible`, which also required adding sync_log error variant and sync_log translations (from api error to database to graphql)
* Added some docs for when to increment version
* Added new translation to front end for sync-api-incompatible (yay front end failed to compile after `yarn generate`, meaning exhaustive check worked)

Snuck Ins:
* Added actual version to headers for sync api
* migrate() method on the trait has default implementation (we can do postgres flag implementation without making one for sqlite)

# 🧪 How has/should this change been tested? 

With 4D branch mentioned above:

### Quick server test 

Using sync settings in local.yaml, change sync version to 2 in: 

https://github.com/openmsupply/open-msupply/blob/b692ba4402923e5e1b42ec5acad7714db708cdae/server/service/src/sync/settings.rs#L4

Run `rm -rf omsupply-database* && cargo run`, should see an error, change it back to 1, should be fine. Can also change version in 4D: syncV5API, should adhere to this formula: (min server api version <= site version <= max server api version)

### Server and UI test

Make sure version is not compatible between central and remote (see above test instructions), try to initialise, should get this error:

Screenshot 2023-03-09 at 12 15 21 PM

Now to test that api incompatibility error is saved in sync_log and can be displayed to user from there

Fix version compatibility and initialise, then stop server and change versions to be incompatible, start server again and try to sync, should get an error like this:

Screenshot 2023-03-09 at 12 21 20 PM

## 💌 Any notes for the reviewer?

I only ran integration tests for the test I added

## Carry over

Add issue for:
* Displaying to the user what version should be used
* Some compatibility matrix, built from both repos (mSupply/omSupply)

### CODE REVIEW

File: server/graphql/general/src/sync_api_error.rs [hunk 1]
```diff
@@ -162,7 +165,7 @@ mod test {
                 source: ParsedError {
                     code: SyncErrorCodeV5::SiteIncorrectHardwareId,
                     message: "n/a".to_string(),
-                    data: Some("n/a".to_string()),
+                    data: Some(json!("n/a")),
```
Comment (andreievg) [inline server/graphql/general/src/sync_api_error.rs:168]: This was changed, it looks like `String` type for `data` was failing to deserialize from object

File: server/repository/src/migrations/mod.rs [hunk 2]
```diff
@@ -22,7 +23,9 @@ use thiserror::Error;
 
 pub(crate) trait Migration {
     fn version(&self) -> Version;
-    fn migrate(&self, connection: &StorageConnection) -> anyhow::Result<()>;
+    fn migrate(&self, _: &StorageConnection) -> anyhow::Result<()> {
```
Comment (andreievg) [inline server/repository/src/migrations/mod.rs:26]: Added default so that when postgres specific migrations are done we don't have to create empty migrate method for sqlite

File: server/repository/src/migrations/mod.rs [hunk 3]
```diff
@@ -60,6 +63,7 @@ pub fn migrate(
         Box::new(V1_01_01),
         Box::new(V1_01_02),
         Box::new(V1_01_03),
+        Box::new(v1_01_05::V1_01_05),
```
Comment (andreievg) [inline server/repository/src/migrations/mod.rs:66]: A little bit less import when fully qualifying with, `v1_01_05::V1_01_05` vs `V1_01_05` and `use self::v1_01_05::V1_01_05`

File: server/repository/src/migrations/v1_01_05/mod.rs [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+impl Migration for V1_01_05 {
+    fn version(&self) -> Version {
+        Version::from_str("1.1.5")
+    }
+    #[cfg(feature = "postgres")]
+    fn migrate(&self, connection: &crate::StorageConnection) -> anyhow::Result<()> {
+        use crate::migrations::sql;
+        sql!(
+            connection,
+            r#"ALTER TYPE sync_api_error_code ADD VALUE IF NOT EXISTS 'API_VERSION_INCOMPATIBLE';"#
```
Comment (andreievg) [inline server/repository/src/migrations/v1_01_05/mod.rs:14]: there is actually a test for this that i quite like: 
https://github.com/openmsupply/open-msupply/blob/b692ba4402923e5e1b42ec5acad7714db708cdae/server/repository/src/db_diesel/sync_log_row.rs#L153-L168

File: server/service/src/sync/api/core.rs [hunk 5]
```diff
@@ -20,22 +21,25 @@ pub(crate) struct SyncApiV5 {
...
     let mut headers = HeaderMap::new();
     headers.insert(
         HeaderName::from_static("msupply-site-uuid"),
         format!("{}", hardware_id).parse().unwrap(),
     );
-    // TODO get version from version system
     headers.insert(
         HeaderName::from_static("app-version"),
-        "1.0".parse().unwrap(),
+        Version::from_package_json().to_string().parse().unwrap(),
```
Comment (andreievg) [inline server/service/src/sync/api/core.rs:32]: this is not part of the issue, but thought to add it as it's somewhat related

File: server/service/src/sync/api/error.rs [hunk 6]
```diff
@@ -40,13 +40,13 @@ pub enum SyncApiErrorVariant {
...
 #[derive(Error, Debug, Serialize, Deserialize)]
-#[error("code: '{code:?}' message: '{message}' data: '{data:?}")]
+#[error("code: '{code:?}' message: '{message}' data: '{}'", serde_json::to_string(data).unwrap())]
 pub struct ParsedError {
     #[serde(serialize_with = "sync_error_code_v5_se")]
     #[serde(deserialize_with = "sync_error_code_v5_de")]
     pub code: SyncErrorCodeV5,
     pub message: String,
-    pub data: Option<String>,
+    pub data: Option<serde_json::Value>,
```
Comment (andreievg) [inline server/service/src/sync/api/error.rs:49]: As per earlier comment, there was an issue with deserialising object data into string

File: server/service/src/sync/test/integration/errors.rs [hunk 7]
```diff
@@ -119,29 +118,80 @@ mod tests {
...
+                        ..
+                    }
                 },
                 ..
-            }
+            }))
         );
     }
+
+    // This test was checking for `html` type return from 4d server, this seems to be captured now
```
Comment (andreievg) [inline server/service/src/sync/test/integration/errors.rs:168]: this was weird, I didn't quite delete this test yet, not sure if I should or not, since I do like the test for AsText variant (this happens when we fail to deserialize error input, due to it's shape or json validity), but didn't know how to replicate it now without adding new endpoint

File: server/service/src/sync/api/core.rs (hunk 5 above)
Comment (mark-prins) [reply server/service/src/sync/api/core.rs:32]: Nice!

**Review by mark-prins — APPROVED** [review]
👍 Looks good! thanks Andrei - tested and working well

**Comment by andreievg** [comment]
Thanks for review @mark-prins, just waiting now for back end branch to be approval, just in case it requires changes here

File: server/service/src/sync/api/core.rs [hunk 8]
```diff
@@ -204,7 +210,7 @@ mod tests {
         let mock = mock_server.mock(|when, then| {
             when.method(POST)
                 .header("msupply-site-uuid", "site_id")
-                .header("app-version", "1.0")
+                .header("app-version", Version::from_package_json().to_string())
```
Comment (Chris-Petty) [inline server/service/src/sync/api/core.rs:213]: yay!
