### PR TITLE
#1183 Date input fix

### LINKED ISSUE #1183: Entering a date manually on the Add Encounter Modal window throws an error
In Patients > Patient Detailed View > Add Encounter Modal: 

When entering a date manually for `Visit Date`, it automatically goes to the "Oops! Something's gone wrong." window: 

Feb-14-2023 16-50-38

Works fine when using the date picker. 

Demo: https://demo-open.msupply.org:88/dispensary/patients/8d2d45fa-b446-47fc-9629-5571a50feba3
version: 1.1.1

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fixes #1183 

This is the "quick fix" for just the date error -- adding full validation (and checking for compulsory fields) will be done in #1264.

# 👩🏻‍💻 What does this PR do? 
 

The main problem was the `formatRFC3339` function from `date-fns` -- it would throw an error on invalid dates. So I've just changed the exported version of this (in "DateUtils.ts") to return `null` rather than throw on invalid date inputs.

Found implementations in both the Create Encounter modal and the Encounter detail page Toolbar -- the time pickers needed and additional check so they didn't reset the date when the input time returned `null`.

# 🧪 How has/should this change been tested? 

Create a new encounter and check that both the Visit Date and Start and End times can be entered manually. (Time needs to match the format exactly though, so "11:59 pm")

Also, check the Date and Times on the created Encounter page can also be changed manually as above.

### CODE REVIEW

**Comment by mark-prins** [comment]
started testing.. and while I can create an encounter by manually entering times and dates, if I edit the time on the encounter itself I get this:

image

I was just playing around.. clearing out the auto generated `12:00` and the error popped up

File: client/packages/common/src/intl/utils/DateUtils.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ export const DateUtils = {
     differenceInDays(Date.now(), dateInputHandler(date)),
   startOfDay,
   startOfYear,
-  formatRFC3339,
+  formatRFC3339: (date: Date) => (isValid(date) ? formatRFC3339(date) : null),
```
Comment (mark-prins) [inline client/packages/common/src/intl/utils/DateUtils.ts:89]: is there a reason to return `null`? it would simplify the usage if you could return `undefined` instead 😄

**Review by mark-prins — COMMENTED** [review]
Changes look fine to me.. wondering if you can fix the issue of clearing the input as well?

File: client/packages/common/src/intl/utils/DateUtils.ts (hunk 1 above)
Comment (CarlosNZ) [reply client/packages/common/src/intl/utils/DateUtils.ts]: Yeah, true. 45ff8470d

**Comment by CarlosNZ** [comment]
> *Edit* this appears to be in the `x-date-pickers/DatePicker` component. good luck? not sure if you can fix that?

Yes, I just came to that conclusion, although I thought it was `x-date-pickers/TimePicker` -- the error is happening before any `onChange` method I provide.

I'll have a bit more of a look, but it might not be easy to fix. Maybe updating dependencies will help? 🤷‍♂️

**Review by clemens-msupply — COMMENTED** [review]
If I understood correctly you will fix these issues below in another PR so just what I found during testing...

No error message:
image

But it shows an error for this one:

image

I haven't found the pattern yet but not sure why it likes some inputs and dislikes others...

**Comment by CarlosNZ** [comment]
> If I understood correctly you will fix these issues below in another PR so just what I found during testing...
> 
> No error message: image
> 
> But it shows an error for this one:
> 
> image
> 

Yeah, I didn't try and add any additional validation at this point, just letting the internal validation handle things, which, as you noticed, is way more accepting than it probably should be. 

> I haven't found the pattern yet but not sure why it likes some inputs and dislikes others...

It seems to try hard to interpret whatever the user enters as a valid date -- I did find a way to inspect what it thought the date was at one point, but I can't remember how I did that now. The problem is an invalid date that doesn't show the error doesn't get saved, but there's no user feedback. I'll see if I can do more standardised validation for these date fields when I do #1264.

**Review by clemens-msupply — APPROVED** [review]
