### PR TITLE
2158 fix stock item search autocomplete limit list with pagination

### LINKED ISSUE #2158: More than 5k records of item list do not appear in transaction window
## What went wrong? 😲
 
When the datafile has more than 5k no. of items, it turns out it won't show all the list of items while issuing or any other transaction like stocktakes or replenishments as well.

## Expected behaviour 🤔
All items (not just limited 5k items but all) should load properly.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure your data has more than 5k items. (5k seems to be the limit currently as per @raviSussol )
2. Go to that master-list window
3. See first error: it takes some noticeable time to load all those items. **Maybe add pagination in that window as well?**
4. Check the last time, for eg: `test` item in the last
5. Now create any transaction, for eg: create anew stocktake
6. Click 'Add item' button
7. Search for `test` item
8. See error: the list doesn't even show that `test` item at all. (since it doesn't lie within the 5k loaded items in that list)

## Recordings
https://recordit.co/dwYRFP8k4i

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)
 
## Additional context
@raviSussol seems to be working [on similar issue](https://github.com/openmsupply/health-supply-hub/pull/1036) in hsh, so can apply the same fix here as well?

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #2158 

# 👩🏻‍💻 What does this PR do? 
 
- Loads stock items asynchronously with the help of pagination for a large dataset
- Handles search to the back when a user types in the autocomplete field

# 🧪 How has/should this change been tested? 

Follow the reproducible steps in the #2158 to test

## 💌 Any notes for the reviewer?

We faced the same issue in the [health supply hub](https://github.com/openmsupply/health-supply-hub/issues/1030) and thought to solve with same approach here as well by async loading of autocomplete list records with the help of the pagination.

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+
+    return (option as { label?: string }).label ?? '';
+  };
+
+  const debounceOnPageChange = useDebounceCallback(
+    (page: number) => {
+      onPageChange && onPageChange(page);
+    },
+    [onPageChange],
+    paginationDebounce || 500
```
Comment (mark-prins) [inline client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx:103]: the `useDebounceCallback` function has a default of 500 anyway

```suggestion
    paginationDebounce
```

File: client/packages/system/src/Item/Components/StockItemSearchInput/hooks.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  return {
+    filter,
+    onFilter: (searchText: string) => setFilter(filterBy(searchText)),
+  };
+};
+
+export const usePagination = () => {
+  const [pagination, setPagination] = useState({
+    page: 0,
+    first: 1000,
```
Comment (mark-prins) [inline client/packages/system/src/Item/Components/StockItemSearchInput/hooks.ts:18]: I thought that 1000 seemed pretty high, given that pagination is now in place. have added this as a prop and defaulted to 500 🤷

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+      loadingText={loadingText}
+      noOptionsText={noOptionsText}
+      options={options}
+      size="small"
+      renderInput={renderInput || defaultRenderInput}
+      renderOption={renderOption || defaultRenderOption}
+      onChange={onChange}
+      getOptionLabel={getOptionLabel || defaultGetOptionLabel}
+      PopperComponent={popperMinWidth ? CustomPopper : StyledPopper}
+      ListboxProps={
```
Comment (mark-prins) [inline client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx:136]: the nesting is getting pretty deep, makes it harder to read!
I've lifted this out to try and tidy a bit

**Review by mark-prins — CHANGES_REQUESTED** [review]
🎉  thanks Ravi! that's excellent. I was hoping that we could add an infinite scroll to the item selector and we have never got around to it.

There's a re-render issue to resolve, and I also thought that a loading indicator would improve the usability. for me, it's hard to tell that the new api request has been fired off.

I've made a [suggestion](https://github.com/openmsupply/open-msupply/compare/2158-fix-stock-item-search-autocomplete-limit-list-with-pagination...2158-suggestion) to add in a loader indication. 

I also started lifting out common components.. but only got as far as one! hardly worth it 🙄

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+        (pagination &&
+          onPageChange && {
+            onScroll: (event: SyntheticEvent) => {
+              const listboxNode = event.currentTarget;
+              if (
+                listboxNode.scrollTop + listboxNode.clientHeight ===
+                listboxNode.scrollHeight
+              ) {
+                // testing
+                console.log('at the end', pagination);
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx]: Oops! cc37e1e0e

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 5]
```diff
@@ -19,16 +22,40 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
+  const options = extraFilter ? items.filter(extraFilter) ?? [] : items ?? [];
+
+  const cachedSearchedItems = useMemo(() => {
+    const newItems = ArrayUtils.uniqBy(
+      [...items, ...(data?.nodes ?? [])],
+      'id'
+    );
+    const sorted = ArrayUtils.orderBy(newItems, ['name'], ['asc']);
+    return sorted;
+  }, [items, data]);
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx]: After you said, tried inspecting component rerender in devtools and ah... that's awful! Thanks for the pinpoint. Resolved by 0960565a6

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+      onChange={onChange}
+      getOptionLabel={getOptionLabel || defaultGetOptionLabel}
+      PopperComponent={popperMinWidth ? CustomPopper : StyledPopper}
+      ListboxProps={
+        (pagination &&
+          onPageChange && {
+            onScroll: (event: SyntheticEvent) => {
+              const listboxNode = event.currentTarget;
+              if (
+                listboxNode.scrollTop + listboxNode.clientHeight ===
```
[the remark this answers is not in the document]
Comment (raviSussol) [reply client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx]: That's weird... I'm getting the exact values of scroll position and scroll height.


But I also think that it'd be safe to increase the scroll position by 1 and compare with `>=` to scroll height.
Updated with 0819371c6

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx (hunk 3 above)
Comment (raviSussol) [reply client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx]: Make sense. Updated by 0819371c6

File: client/packages/system/src/Item/Components/StockItemSearchInput/hooks.ts (hunk 2 above)
Comment (raviSussol) [reply client/packages/system/src/Item/Components/StockItemSearchInput/hooks.ts]: Fair enough. 8e160ebd2

**Comment by raviSussol** [comment]
Thanks for the review @mark-prins - were helpful suggestions. I've updated the pr with changes now.
> I've made a [suggestion](https://github.com/openmsupply/open-msupply/compare/2158-fix-stock-item-search-autocomplete-limit-list-with-pagination...2158-suggestion) to add in a loader indication.

Hmm. I think the `isLoading` from the `useQuery` also seems to work but loading of data quickly enough to make a person there's no any update happened.

**Comment by nisha-dangol** [comment]
@raviSussol : Tested in v1.3.0-IS2158
Looks [good so far](https://recordit.co/50Y3UzSzDH) as I can search and select all the items (in large number of items list as well unlike the original issue)

File: client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (mark-prins) [reply client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx]: yeah, it was weird. sometimes it was exact for me too.. but mostly was slightly out. I couldn't see a pattern why it might be doing that though sorry

**Comment by mark-prins** [comment]
> I think the isLoading from the useQuery also seems to work

ah, right. yeah - I did wonder if that would trigger it. That's partly why I added the timeout, so make the loader more visible. Best to leave my suggestion out then thanks!

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx [hunk 7]
```diff
@@ -19,25 +24,50 @@ export const StockItemSearchInput: FC<StockItemSearchInputProps> = ({
...
   const formatNumber = useFormatNumber();
 
-  const value = data?.nodes.find(({ id }) => id === currentItemId) ?? null;
+  const value = items.find(({ id }) => id === currentItemId) ?? null;
   const selectControl = useToggle();
 
-  const options = extraFilter
-    ? data?.nodes?.filter(extraFilter) ?? []
-    : data?.nodes ?? [];
+  const options = extraFilter ? items.filter(extraFilter) ?? [] : items ?? [];
```
Comment (mark-prins) [inline client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx:41]: doing this change also removes a few extra renders (and makes the options prop below simple (`options={options}`)
```suggestion
const options = React.useMemo(
    () =>
      defaultOptionMapper(
        extraFilter ? items.filter(extraFilter) ?? [] : items ?? [],
        'name'
      ),
    [items]
  );
```

**Review by mark-prins — APPROVED** [review]
👍 that's great and thanks for the changes Ravi

File: client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx (hunk 7 above)
Comment (raviSussol) [reply client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx]: Oops, sorry I missed this part to update. Here 7bb6a3dfb
