### PR TITLE
188 changing supplier/customer on shipments can cause strife for sync

### LINKED ISSUE #188: Changing supplier/customer on shipments can cause strife for sync
image

When editing an inbound shipment you can change the supplier. This is a useful feature - say you spent a day entering in a 500 lines of information only to realise you selected the wrong supplier! AH! Thankfully you can just correct the supplier rather than start again.

I have one assumption: that currently the logic just updates the `invoice.name_id` of the shipment record. Please correct me if that's not true! 

The central server forwards records to the other party (based on `invoice.name.store.site`) so that they can process the transfer on their end, given that it is a store active on a different site to the store you made the invoice. This leads to an awkward scenario:

1. Create an invoice, select supplier and add some lines.
2. Sync - the central server forwards the records to the supplying store's site indicated by `invoice.name.store.site`.
3. On the invoice, change the supplier.
4. Sync - the central server forwards the records to the new supplier indicated by `invoice.name.store.site`. Any further updates or even deleting the invoice will never get synced to the original supplier. The original supplier has a bunch of records that it really shouldn't have, and we have no means of identifying previous suppliers to correct this.

Further:
- Changing the supplier multiple times, syncing each time, would send records to each supplier that will never get updated 

## What do our other apps do?

- mSupply mobile doesn't let you change the name on an invoice. So this can't happen! Sucks if you chose the wrong supplier though, you'll simply have to delete it and start again.
- mSupply desktop only lets you delete an invoice after deleting all the lines, and lines are always synced before the parent. This makes sure that they can get forwarded correctly before the `name_id` is updated (except for the parent record itself...). Also, it doesn't matter that much, I don't think desktop actually does anything with lines from other sites/stores. Basically still suffer from having to start from scratch if you chose the wrong supplier, though.

### 1. Duplicate the invoice and lines and delete old

Selecting a new supplier will create a new invoice and and clone lines. The old invoice will be deleted immediately. Reuse the same serial number.

On the central server, block updates of `name_id` FKs.

_Pros:_
- the FKs on records don't change, so all the sync logic works correctly.
- UX doesn't change

_Cons:_
- A little more complex/expensive. But it should be a relatively rare event
- Blocking `name_id` updates might be too hardball, but we'll know client apps making invalid updates pretty quickly!

### 2. Duplicate the invoice and lines, warn user

Add an extra step or so to communicate that selecting a new supplier will create a new invoice with all the same lines. Perhaps give the option to delete the original invoice too.

On the central server, block updates of `name_id` FKs.

_Pros:_
- the FKs don't change, so all the sync logic works correctly.

_Cons:_
- A little more complex/expensive. But it should be a relatively rare event
- BLOCKER? If done on an "allocated" invoice, it should affect stock. If not deleting the original then we'll need to allocate more stock, of which we may not have enough. Then the duplicate won't have the same quantities.
  - Likely better to just immediately delete and create the new lines with identical quantities as in option 1, don't need to update stock levels.
- Maybe annoying UX. If the user chooses not to delete then they may end up with a whole lot of invoices that are of no use
- Blocking `name_id` updates might be too hardball, but we'll know client apps making invalid updates pretty quickly!

### 3. Central server has special code handling the update

Whenever an invoice syncs with a `name_id` change to sync v5, the central server does the additional task of sending a `delete` for it and all the lines to the old `invoice.name.store.site`. Additionally, ensure that all the lines are sent to the new `invoice.name.store.site` to ensure the invoice is in a complete state.

_Pros:_
- omSupply doesn't have to change. Changing supplier seems completely seamless which is great UX.

_Cons:_
- Complexity on the central server. Unique rules for records affected must be applied (hoping to have general rules when we can).
- Overhead on the central server. Trying to keep it as fast as possible!

Note: In some ways this is equivalent to omsupply creating a new invoice with the new supplier and deleting the old one. In the end it still results in the new `invoice.name.store.site` getting the inserts, and the old site getting the deletes.

## Additional context

This should affect all records that are forwarded based on `name_id`:
- invoices
- requisitions
- purchase orders
- more?

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #188 

- Copy all details of invoice/invoice lines into a new invoice when the name has been changed. 
- New endpoint to update name.
- FE changes coming in a different PR

### CODE REVIEW

File: server/service/src/invoice/outbound_shipment/update_name/generate.rs [hunk 1]
```diff
@@ -0,0 +1,64 @@
+use repository::{
+    EqualFilter, InvoiceLine, InvoiceLineFilter, InvoiceLineRepository, InvoiceLineRow, Name,
+};
+use repository::{InvoiceRow, StorageConnection};
+use util::uuid::uuid;
+
+use super::{UpdateOutboundShipmentName, UpdateOutboundShipmentNameError};
+
+pub struct GenerateResult {
```
Comment (roxy-dao) [inline server/service/src/invoice/outbound_shipment/update_name/generate.rs:9]: Batches should stay the same since everything from the old invoice/invoice line has been copied over to the new invoice, so have not returned anything to adjust stock levels.

File: server/service/src/invoice/outbound_shipment/update/mod.rs [hunk 2]
```diff
@@ -42,10 +41,6 @@ pub enum UpdateOutboundShipmentError {
     NotThisStoreInvoice,
     // Error applies to unallocated lines with above zero quantity
     CanOnlyChangeToAllocatedWhenNoUnallocatedLines(Vec<InvoiceLine>),
-    // Name validation
```
Comment (roxy-dao) [inline server/service/src/invoice/outbound_shipment/update/mod.rs:45]: Moved over to new endpoint

File: server/service/src/invoice/outbound_shipment/update_name/mod.rs [hunk 3]
```diff
@@ -0,0 +1,334 @@
...
+
+        let service_provider = ServiceProvider::new(connection_manager, "app_data");
+        let context = service_provider
+            .context(mock_store_c().id, "".to_string())
+            .unwrap();
+        let service = service_provider.invoice_service;
+        let invoice_row_repo = InvoiceRowRepository::new(&connection);
+        let invoice_line_repo = InvoiceLineRowRepository::new(&connection);
+
+        let update_invoice = service
```
Comment (mark-prins) [inline server/service/src/invoice/outbound_shipment/update_name/mod.rs:285]: :nit 
```suggestion
        let updated_invoice = service
```

**Review by mark-prins — APPROVED** [review]
👍  very classy! nice solution and a great bit of functionality, it's something that I found annoying in the mSupply

File: server/graphql/invoice/src/mutations/outbound_shipment/update_name.rs [hunk 4]
```diff
@@ -0,0 +1,383 @@
...
+
+        assert_graphql_query!(
+            &settings,
+            mutation,
+            &Some(empty_variables()),
+            &expected,
+            Some(service_provider(test_service, &connection_manager))
+        );
+
+        //OtherPartyNotVisible
```
Comment (clemens-msupply) [inline server/graphql/invoice/src/mutations/outbound_shipment/update_name.rs:241]:
```suggestion
        // OtherPartyNotVisible
```

File: server/service/src/invoice/outbound_shipment/update_name/validate.rs [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+impl From<InvoiceIsNotEditable> for UpdateOutboundShipmentNameError {
+    fn from(_: InvoiceIsNotEditable) -> Self {
+        UpdateOutboundShipmentNameError::InvoiceIsNotEditable
+    }
+}
+
+impl From<NotThisStoreInvoice> for UpdateOutboundShipmentNameError {
+    fn from(_: NotThisStoreInvoice) -> Self {
+        UpdateOutboundShipmentNameError::NotThisStoreInvoice
+    }
```
Comment (clemens-msupply) [inline server/service/src/invoice/outbound_shipment/update_name/validate.rs:73]: In newer endpoints we went over to do the error mapping directly because the From trait adds some indirection here that is sometimes harder than necessary to follow. Since you copied it I am fine to leave it as it but if you feel like doing some refactoring...

**Review by clemens-msupply — APPROVED** [review]
Looks great thanks!

File: server/service/src/invoice/outbound_shipment/update_name/validate.rs (hunk 5 above)
Comment (roxy-dao) [reply server/service/src/invoice/outbound_shipment/update_name/validate.rs:73]: https://github.com/openmsupply/open-msupply/pull/796 (:
