### PR TITLE
1807 Show error when deleting inbound line that is already used 

### LINKED ISSUE #1807: Show error when deleting inbound line that is already used
See last comment

## What went wrong? 😲
 

1. I created a new inbound shipment for one item: 
Screenshot 2023-05-20 at 2 11 26 PM

2. I confirmed the inbound shipment as "delivered"

3. When looking for the stock line in "View Stock", I can already see it: 
Screenshot 2023-05-20 at 2 11 43 PM

## Expected behaviour 🤔

I think we should confirm the stock movement (goods in) when shipment has been verified ?

## How to Reproduce 🔨

see What went wrong? 😲

## Your environment 🌱

 - Version: 1.1.13
 - Platform:
   - [ ] desktop (windows)
   - [ ] desktop (macOS)

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1807

# 👩🏻‍💻 What does this PR do? 
Show snack if inbound shipment line cannot be deleted.

# 🧪 How has/should this change been tested? 
- Create a manual inbound with any item
- Confirm delivered (this will create a stock line for the item)
- Create a stocktake with said item and change stock (change counted packs)
- Go back to the manual inbound invoice that was created and try to delete line
- See snack

### CODE REVIEW

File: client/packages/common/src/hooks/useDeleteConfirmation/useDeleteConfirmation.ts [hunk 1]
```diff
@@ -45,7 +48,9 @@ export const useDeleteConfirmation = <T>({
           const successSnack = success(deletedMessage);
           successSnack();
         })
-        .catch(err => console.log(err.message));
+        .catch(() => {
```
Comment (andreievg) [inline client/packages/common/src/hooks/useDeleteConfirmation/useDeleteConfirmation.ts:51]: should log err.message still

**Review by andreievg — APPROVED** [review]
Thanks, just a small request that should be done before merging, otherwise it's good, thanks
