### PR TITLE
Handle dashboard errors

### LINKED ISSUE #1224: An authentication permission denied alert is displayed on login in to omSupply with a user that has no permissions
## What went wrong? 😲
 
When login to omSupply with a user with no permissions we receive an - Authentication error (permission denied)  without let us know what I am being denied. On logging in, it was seeing stock as the Expired stock was not showing as the progress bar was just turning and turning with nothing happening. There is also a second grey button OK that seems to belongs to nothing in particular.

image

## Expected behaviour 🤔

Probably a better indicator of what is being denied would be good

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Create a user with no permission except the ability to connect to the store you are using on omSupply
1. Login to omSupply with that user 
2. See error

## Your environment 🌱
 - Version [e.g. omSupply 1.1.3, Desktop Server 7.00.06]
 - Platform [e.g. tablet]

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1224 

# 👩🏻‍💻 What does this PR do? 
 
There's a few file changes, but don't be put off! 
Essentially this is picking up on existing work, fixing an incorrect implementation in it and extending to a newer query that missed out on the change.

The process is:
- the `GqlContext` has a list of api calls which might throw a permission error but should not show an alert if they do ( the `itemCounts` dashboard query needed to be added to this list )
- the api calls should provide an `onError` which swallows the error ( note that errors are still logged to console, as an fyi )
- the `isError` prop is set on the `useQuery` response and this can be used to modify the UI response

As an extension to the current process, I've added a message when you don't have permission to view the stats. Simply hiding the panels ( previous behaviour ) results in a big blank page, with no indication that anything should be there. 

image

If there is a problem fetching, other than permission, you get a more generic notification:

Screenshot 2023-03-08 at 10 44 56 AM

# 🧪 How has/should this change been tested? 

1. Create a new user in mSupply
2. Grant them rights to login to one of the stores in the site which syncs to omSupply
3. Make that store default, and then do not assign any permissions in that store
4. login to omSupply as that user

You should see permission denied for the stats panels.

Extra for experts: grant permission for some of the requested permission and see what happens..

- InboundShipmentQuery (View supplier invoices )
- OutboundShipmentQuery (View customer invoices)
- StockLineQuery (View stock)

Unfortunately, the way the invoice counts query works, you need both inbound and outbound permission to see either widget 🙄 

## 📃 Documentation

- [ ] Useful to add a note in the setup or dashboard sections about this with screenshot

### CODE REVIEW

File: client/packages/common/src/types/exceptions.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+}
+
+interface ApiException {
+  extensions: Extensions;
+  locations: Location[];
+  message: string;
+  path: string[];
+}
+
+export const isPermissionDeniedException = (e?: any) =>
```
Comment (andreievg) [inline client/packages/common/src/types/exceptions.ts:19]: I couldn't quite trace this, when is this actually used ? StatusPanel doesn't get called with error prop

File: client/packages/common/src/types/exceptions.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  !!e && (e as ApiException).message === AuthError.PermissionDenied;
```
Comment (andreievg) [inline client/packages/common/src/types/exceptions.ts:20]: I think this would need to be guarded as having message ?

File: client/packages/dashboard/src/widgets/StockWidget.tsx [hunk 3]
```diff
@@ -19,31 +19,28 @@ const LOW_MOS_THRESHOLD = 3;
...
+    isLoading: isItemStatsLoading,
+    isError: hasItemStatsError,
+  } = useDashboard.statistics.item(LOW_MOS_THRESHOLD);
 
   const { mutateAsync: onCreate } = useRequest.document.insert();
   const onError = (e: unknown) => {
     const message = (e as Error).message ?? '';
-    const errorSnack = error(`Failed to create requisition! ${message}`);
+    const errorSnack = errorNotification(
+      `Failed to create requisition! ${message}`
```
Comment (andreievg) [inline client/packages/dashboard/src/widgets/StockWidget.tsx:42]: Maybe a little ToDo to localise ?

File: client/packages/common/src/types/exceptions.ts (hunk 1 above)
Comment (andreievg) [reply client/packages/common/src/types/exceptions.ts:19]: Sorry I see it now, go to references in vs code didn't quite work : /

File: client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx [hunk 4]
```diff
@@ -58,51 +56,89 @@ export const StatsPanel: FC<StatsPanelProps> = ({
...
+  error: any;
+  isError: boolean;
+  isLoading: boolean;
+  stats: Stat[];
+}) => {
+  const t = useTranslation();
+  const isPermissionDenied = isPermissionDeniedException(error);
+
+  switch (true) {
+    case isError:
```
Comment (andreievg) [inline client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx:76]: this is interesting way to do early return (through switch statement vs traditional if () return), one extra level of indentation but still very readable

**Review by andreievg — APPROVED** [review]
Thanks, look good I've tested, I have some more comments to make, I'll make issues: 

About `any` typescript type (cast at root and avoid in props)

About permissions, knowing which permissions apply to each `place` without looking at code , also inbound and outbound permissions are consolidated

File: client/packages/dashboard/src/widgets/StockWidget.tsx (hunk 3 above)
Comment (mark-prins) [reply client/packages/dashboard/src/widgets/StockWidget.tsx:42]: oops. was just renaming `error` and didn't think about the actual message. will do.

File: client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx (hunk 4 above)
Comment (mark-prins) [reply client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx:76]: yeah, bit of a novelty - I picked up the `switch (true)` from @CarlosNZ and thought it was neat, so I've used it a bit

**Comment by mark-prins** [comment]
Thanks @andreievg for review! have made changes in c99a6a662
I didn't like using `any` so have cast as an `ApiException` and retested. it's much nicer
