### PR TITLE
818 sync translation handle empty datetime strings

### LINKED ISSUE #818: Invoices, requisitions and stocktakes missing when syncing previously mSupply Desktop site
## What's wrong?

If you create records in mSupply desktop on a remote site (using current production/master v6.06), then use mSupply desktop and sync to omSupply, you get errors recorded in the sync_buffer:

image

The outcome of this is that omSupply is missing transactional and ordering data when in use. All child lines will have FK constraint violations when integration is attempted for them.

```json
{"Colour":1710361,"Date_order_received":"0000-00-00","Date_order_written":"0000-00-00","ID":"0BC1BD19BD32413B817039E0BCD0AB28","amount_outstanding":0,"arrival_date_actual":"0000-00-00","arrival_date_estimated":"0000-00-00","authorisationStatus":"","budget_period_ID":"","category2_ID":"","category_ID":"","comment":"","confirm_date":"0000-00-00","confirm_time":0,"contact_id":"","currency_ID":"8009D512AC0E4FD78625E3C8273B0171","currency_rate":1,"custom_data":null,"diagnosis_ID":"","donor_default_id":"","encounter_id":"","entry_date":"2022-11-16","entry_time":75471,"export_batch":0,"finalised_date":"0000-00-00","foreign_currency_total":0,"goodsReceivedConfirmation":null,"goods_received_ID":"","hold":false,"insuranceDiscountAmount":0,"insuranceDiscountRate":0,"internalData":null,"invoice_num":2,"invoice_printed_date":"0000-00-00","is_authorised":false,"is_cancellation":false,"lastModifiedAt":1668585555,"linked_goods_received_ID":"","linked_transaction_id":"","local_charge_distributed":0,"mode":"store","mwks_sequence_num":0,"nameInsuranceJoinID":"","name_ID":"6582C406F549451DABDBFE141B34F766","number_of_cartons":0,"om_allocated_datetime":"","om_colour":"","om_created_datetime":"","om_delivered_datetime":"","om_picked_datetime":"","om_shipped_datetime":"","om_status":"","om_transport_reference":"","om_type":"","om_verified_datetime":"","optionID":"","original_PO_ID":"","paymentTypeID":"","pickslip_printed_date":"0000-00-00","prescriber_ID":"","requisition_ID":"","responsible_officer_ID":"","service_descrip":"","service_price":0,"ship_date":"0000-00-00","ship_method_ID":"","ship_method_comment":"","status":"nw","store_ID":"D0E298893F3945DABE80B138E25D3D15","subtotal":0,"supplier_charge_fc":0,"tax":0,"their_ref":"","total":0,"type":"si","user1":"","user2":"","user3":"","user4":"","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207","wardID":"","waybill_number":""}
```
Culprit: `"om_allocated_datetime":""` char 1152 is the value here

```json
{"ID":"E64719C276A84A6F9910A43616305A56","authorisationStatus":"none","colour":1,"comment":"","custom_data":null,"date_entered":"2022-11-16","date_order_received":"2022-11-16","date_required":"2022-11-16","date_stock_take":"2022-11-16","daysToSupply":30,"isRemoteOrder":false,"is_emergency":false,"lastModifiedAt":1668585555,"linked_purchase_order_ID":"","linked_requisition_id":"","name_ID":"6582C406F549451DABDBFE141B34F766","nsh_custInv_ID":"","om_colour":"","om_created_datetime":"","om_expected_delivery_date":"0000-00-00","om_finalised_datetime":"","om_max_months_of_stock":0,"om_sent_datetime":"","om_status":"","orderType":"","periodID":"","previous_csh_id":"","programID":"","requester_reference":"","requisition_category_ID":"","serial_number":3,"status":"sg","store_ID":"D0E298893F3945DABE80B138E25D3D15","thresholdMOS":0,"type":"response","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207"}
```
Culprit: `"om_created_datetime":""` char 486 is the value here

```json
{"ID":"E64719C276A84A6F9910A43616305A56","authorisationStatus":"none","colour":1,"comment":"","custom_data":null,"date_entered":"2022-11-16","date_order_received":"2022-11-16","date_required":"2022-11-16","date_stock_take":"2022-11-16","daysToSupply":30,"isRemoteOrder":false,"is_emergency":false,"lastModifiedAt":1668585555,"linked_purchase_order_ID":"","linked_requisition_id":"","name_ID":"6582C406F549451DABDBFE141B34F766","nsh_custInv_ID":"","om_colour":"","om_created_datetime":"","om_expected_delivery_date":"0000-00-00","om_finalised_datetime":"","om_max_months_of_stock":0,"om_sent_datetime":"","om_status":"","orderType":"","periodID":"","previous_csh_id":"","programID":"","requester_reference":"","requisition_category_ID":"","serial_number":3,"status":"sg","store_ID":"D0E298893F3945DABE80B138E25D3D15","thresholdMOS":0,"type":"response","user_ID":"0763E2E3053D4C478E1E6B6B03FEC207"}
```
Culprit: `"om_created_datetime":""` char 249 is the value here

## Relevant data from the willing

[demo_data 606 number test.zip](https://github.com/openmsupply/open-msupply/files/10019828/demo_data.606.number.test.zip)

Use the "Gryffindor" site. Data mostly relates to the store "Gryffindor District store".

## Solution

**Suggestion:** I suspect the solution is making sure sync translators can handle there potentially being empty string values for these datetime fields. While time will be lost in most cases, perhaps it should at least get the date from the old mSupply fields.

**Alternative:** mSupply central server could do the mapping when records are pulled from the v5 API. 

## Other areas to think about

I strongly believe applications shouldn't ignore errors that can affect data integrity. I think integration should fail and the app should not be usable until we fix integration errors, otherwise they may be inadvertently ignored until the app is in production. Fixing errors like these we should want to be apparent fast and jump to the top of the TODO list 🚀 !

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #818

- `empty_str_as_option_generic` new deserializer. Handles empty string values for generic type. `Option<T>` I think you could say.
- Fixes all all the `om_*` fields of type `Option<NaiveDateTime>` when the JSON value is `""`
- Fixes all all the `om_*` fields of type `Option<SomeEnum>` when the JSON value is `""`. E.g `om_status` and `om_type`.

### CODE REVIEW

File: server/service/src/sync/test/test_data/invoice.rs [hunk 1]
```diff
@@ -84,7 +84,14 @@ const TRANSACT_1: (&'static str, &'static str) = (
...
       "wardID": "",
-      "waybill_number": ""
+      "waybill_number": "",
+      "om_allocated_datetime": "",
+      "om_picked_datetime": null,
+      "om_shipped_datetime": "",
+      "om_delivered_datetime": "",
+      "om_verified_datetime": "",
+      "om_created_datetime": "",
+      "om_transport_reference": ""
```
Comment (Chris-Petty) [inline server/service/src/sync/test/test_data/invoice.rs:94]: Arguably should break out into 3 test JSON:
- Where the `datetime` string is `""`
- `datetime` string is `null`
- the properly is outright missing entirely, i.e. no key.

Proooobably don't need to do that exhaustively for _every_ field though...

File: server/service/src/sync/test/test_data/requisition.rs [hunk 2]
```diff
@@ -39,7 +39,14 @@ const REQUISITION_REQUEST: (&'static str, &'static str) = (
       "programID": "F36DBBC6DBCA4528BDA2403CE07CB44F",
       "lastModifiedAt": 1594273006,
       "is_emergency": false,
-      "isRemoteOrder": false
+      "isRemoteOrder": false,
+      "om_created_datetime": "",
+      "om_sent_datetime": "",
+      "om_finalised_datetime": "",
+      "om_expected_delivery_date": "0000-00-00",
```
Comment (Chris-Petty) [inline server/service/src/sync/test/test_data/requisition.rs:46]: @andreievg @clemens-msupply in mSupply this is a `Date` field type rather than string. Might be an idea to go to string if strictly for omSupply?

File: server/service/src/sync/translations/requisition.rs [hunk 3]
```diff
@@ -91,35 +93,47 @@ pub struct LegacyRequisitionRow {
...
     /// relates to max_months_of_stock
     pub daysToSupply: i64,
 
-    #[serde(deserialize_with = "empty_str_as_option")]
+    #[serde(deserialize_with = "empty_str_as_option_string")]
     pub comment: Option<String>,
 
+    #[serde(default)]
     #[serde(rename = "om_created_datetime")]
+    #[serde(deserialize_with = "empty_str_as_option_generic")]
```
Comment (Chris-Petty) [inline server/service/src/sync/translations/requisition.rs:110]: `#[serde(default)]` Handles the key/value not being included at all. Needed after adding `#[serde(deserialize_with = "empty_str_as_option_generic")]` to handle value being `""`

File: server/service/src/sync/sync_serde.rs [hunk 4]
```diff
@@ -1,11 +1,27 @@
...
 
-pub fn empty_str_as_option<'de, D: Deserializer<'de>>(d: D) -> Result<Option<String>, D::Error> {
+pub fn empty_str_as_option_string<'de, D: Deserializer<'de>>(
+    d: D,
+) -> Result<Option<String>, D::Error> {
     let s: Option<String> = Option::deserialize(d)?;
     Ok(s.filter(|s| !s.is_empty()))
 }
 
+pub fn empty_str_as_option_generic<'de, T: Deserialize<'de>, D: Deserializer<'de>>(
```
Comment (clemens-msupply) [inline server/service/src/sync/sync_serde.rs:14]: Just call it `empty_str_as_option`?  appending generic sounds a bit weird...

File: server/service/src/sync/test/test_data/invoice.rs (hunk 1 above)
Comment (clemens-msupply) [reply server/service/src/sync/test/test_data/invoice.rs:94]: Think its ok since you mixed the null case in.

**Review by clemens-msupply — APPROVED** [review]
Looks good to me, thanks! see renaming comment...

File: server/service/src/sync/sync_serde.rs (hunk 4 above)
Comment (Chris-Petty) [reply server/service/src/sync/sync_serde.rs:14]: I do agree it's a bit weird, but wanted to differentiate from the other one. Happy to trim!

Just a note, the `empty_str_as_option_string` is faster if genuinely just looking for a string.

Comment (clemens-msupply) [reply server/service/src/sync/sync_serde.rs:14]: think its already differentiated enough because the other one is called `empty_str_as_option_string`

Comment (Chris-Petty) [reply server/service/src/sync/sync_serde.rs]: e8c8fd751ff21090229157626296aef97df46a97
