### PR TITLE
2093 keyed item array fix

### LINKED ISSUE #2093: KeyedItemArray doesn't render with missing data
## What went wrong? 😲
 

image

The control children are not shown if the data contain an empty array...

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #2093 

I also added a workaround that avoid creating empty array entries for FirstItemArray and KeyedItemArray. This avoids data editing without user input, e.g. user visits the form and data is modified because an empty object had been added to the array.

# Testing
- Create a new patient with minimal details
- Check in the history that contacts and contactDetails arrays are empty.
- Re-visit patient, data shouldn't be automatically modified.
- Update contact details and enter next of kin details
- Check that changes are made correctly (history view)

### CODE REVIEW

File: client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx [hunk 1]
```diff
@@ -63,6 +67,12 @@ const FirstItemArrayComponent = (props: FirstItemArrayControlCustomProps) => {
     [uischemas, schema, uischema.scope, path, uischema, rootSchema]
   );
 
+  // If there are definitions they need to be added to the child schema
+  const schemaWithDefs = {
+    ...(schema as JsonSchema7),
+    definitions: rootSchema.definitions as Record<string, JsonSchema7>,
+  };
```
Comment (clemens-msupply) [inline client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx:74]: This seems slightly hacky but seems to work...

Comment (mark-prins) [reply client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx:74]: :nit I would have the `rootSchema.definitions` first and spread the schema, so that the schema takes precedence if there are any conflicts. Realistically though, I don't think that it makes any difference in this case.

**Review by mark-prins — APPROVED** [review]
👍  LGTM!
