### PR TITLE
1191 arv medication 2

### LINKED ISSUE #1191: Programs: "ARV / Medication" section's enhancements
## How to Reproduce 🔨

Dispensary > Patients > Select Patient > Add Encounter: "HIV Care Encounter" > Section: ARV / Medication

### Pills counts: 

|Field|Type|Definition                                                                        |Suggested new name            |
|-----|----|----------------------------------------------------------------------------------|------------------------------|
|`Pill Count after last Visit:`|read-only|total qty of pills patient had at the end of the last visit                       |Pill Count (at last visit end)|
|`Pill Count before Visit:`|manual entry|remaining qty of pills patient has at the start of the new/current visit          |Pill Count (at visit  start)   |
|`Number of pills dispensed:`|manual entry|number of pills dispensed by the clinician to the patient during the current visit|Quantity of pills dispensed   |
|`Pill Count after visit:`|read-only|`Pill Count before Visit:` + `Number of pills dispensed:` Except if a new regimen has been selected I guess, then should only be   `Number of pills dispensed:`                      |Pill Count (at visit end)     |

- [x] Add an intermediate field (`Number of pills dispensed:`) so user can enter the quantity of pills dispensed during the visit. Two main reasons: 1. it's easier for the user to enter what has been given to the patient rather than making the sum of the remaining pills + dispensed quantity. System can make the sum itself. 2. we need this information captured separately so we can create a "dispensing records" to update inventory (in the future, we think it would be great to generate a dispensing record from the encounter)
- [x] `Number of pills dispensed:` since you are dispensing after having selected 
- [x] rename the fields for more clarity, see above table for reference (I'm open to suggestions by the way)
- [x] Rename `Adherence Status` to `Adherence Score`
- [x] `End of Supply:` calculated based on `Pill Count (at visit end)` except if

### Regimen: 

- [x]  `Current ARV Regimen` is showing the ARV Regimen of the patient until the start of the current visit. This field must be empty if this is patient's first visit, if no regime has yet been given to the patient (No ARV) if patient stopped taking the ARV in the last encounters (Stop ARV)
- [x]  `Regimen Status` is **always** empty by default. User must select a value for every encounter even if it is not the patient's first visit
- [x] If `Regimen Status` = `No ARV` then `ARV Regimen` is disabled, same for `Regimen Change Reason:` (note: ideally they should not be visible unless they are required)
- [x]  If `Regimen Status` = `Start ARV` or `Changes to ARV Regimen` then user must select a new value for `ARV Regimen` and user must select a `Regimen Change Reason:`
- [ ] #1265
- [x] If `Regimen Status` = `Continue ARV` then `ARV Regimen` field is disabled and show the same value as in `Current ARV Regimen`. `Regimen Change Reason:` & `Regimen Change Note:` fields also disabled (note: ideally, should not even be visible).
- [x] If `Regimen Status` = `Stop ARV` then `ARV Regimen` is disabled and is empty. User must select a `Regimen Change Reason:` and `Regimen Change Note:` is enabled (note: stopping the ARV also require the user to give an explanation). 

- [x]  for questions of clarity, I would rename `ARV Regimen` to `New ARV Regimen`

### Other medication: 

- [x] `Relevant Co Medication:`: something wrong here ;-)
Screen Shot 2023-02-16 at 12 58 41 PM

- [x] Missing field `Prophylaxis Medication:`: drop down list, you can select more than one value (similar to Symptoms and Opportunistic infections field from the Physical Exam section). Values: 

|Prophylaxis Medications|
|----------------------|
|Albendazole|           |
|Amoxicilin |           |
|Artemeter  Injection  |
|Chlorampanical|           |
|Chloroquine|           |
|Ciproxicilin|           |
|CMP        Injection  |
|Cotrimoxazole|           |
|Crystopan  |           |
|Fansidar   |           |
|Flucloxicilin|           |
|Fluconazole|           |

Screen Shot 2023-02-16 at 1 00 45 PM

### overall layout of the section: 

- [x] Here is a suggestion for a new layout of this section's form (**open to suggestions**): 

First, the clinician is going to make a decision regarding the patient's treatment (ARV Regimen)

1. Current ARV Regimen:
2. Regimen Status: 
3. New ARV Regimen
4. Regimen Change Reason; 
5. Regimen Change Note: 

Then, clinician is going to decide what to dispense to the patient: 

6. Pill count (at last visit end):
7. Pill count (at visit start):
8. Adherence Score:
9. Quantity of pills dispensed: 
10. Pill count (at visit end): 

Then clinician adds the "other medications":

11. Relevant Co Medication: 
12. Prophylaxis Medication: 

13. I would put the Adherence Chart at the end of the section's form (similar to Weight

## Your environment 🌱
 - Version: 1.1.3
 - Platform: https://demo-open.msupply.org:88/login

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1191 

Changes for the "pill count" section:
- change/rename the QuantityDispensed control
- Update schemas
- Tweak the EncounterProgramEvent control
- Fix for duplicated error counts in the CategorizationTabLayout

# 🧪 How has/should this change been tested? 

Go to an HIV care encounter:
- change the quantity dispensed count -> Pill count after visit and end of supply date should update correctly
- next encounter should show the correct "Pill Count (at last visit end)" count from previous encounter

### CODE REVIEW

**Comment by clemens-msupply** [comment]
I just sneaked in a fix for duplicated error counts...

File: client/packages/programs/src/JsonForms/components/EncounterProgramEvent.tsx [hunk 1]
```diff
@@ -89,19 +93,43 @@ const UIComponent = (props: ControlProps) => {
...
-        required: props.required,
-        sx: DefaultFormRowSx,
-        error: !!errors,
-        helperText: errors,
-      }}
-      labelWidthPercentage={FORM_LABEL_WIDTH}
-      inputAlignment={'start'}
-    />
+    <>
+      {options?.displayType && options?.displayType === 'number' ? (
```
Comment (mark-prins) [inline client/packages/programs/src/JsonForms/components/EncounterProgramEvent.tsx:97]: if you add to the style constant as suggested in the previous PR, then perhaps this could be refactored so that only the `Input` prop differs between the cases here

File: client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx [hunk 2]
```diff
@@ -0,0 +1,238 @@
...
+  const { data, handleChange, label, path, uischema } = props;
+  const [localData, setLocalData] = useState<number | undefined>(data);
+  const [remainingQuantity, setRemainingQuantity] = useState(0);
+  const [baseTime, setBaseTime] = useState<string | undefined>();
+  const { errors, options } = useZodOptionsValidation(
+    Options,
+    uischema.options
+  );
+  const dateFormat = useFormatDateTime();
+  const t = useTranslation(['common', 'programs']);
```
Comment (mark-prins) [inline client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx:83]: neither required, nor actually working in my experience. The `common` namespace is the default fallback, so does not need to be specfiied:

```suggestion
  const t = useTranslation('programs');
```

**Review by mark-prins — APPROVED** [review]
👍  Looks good thanks!

**Comment by mark-prins** [comment]
I do get this though, when testing:

Screenshot 2023-03-02 at 1 45 44 PM

there were no errors indicated on the ARV form though, so I don't know what the `14` are

**Comment by clemens-msupply** [comment]
> I do get this though, when testing:
> 
> Screenshot 2023-03-02 at 1 45 44 PM
> 
> there were no errors indicated on the ARV form though, so I don't know what the `14` are

thanks! I added fix for it

**Comment by roxy-dao** [comment]
> I do get this though, when testing:
> 
> Screenshot 2023-03-02 at 1 45 44 PM
> 
> there were no errors indicated on the ARV form though, so I don't know what the `14` are

It's for the number of unfilled fields! 😄

**Comment by clemens-msupply** [comment]
I merged and fill fix remaining style suggestion in parent branch...

@roxy-dao there where a couple of issues why the count was wrong so now it should show the number of fields that are not filled in correctly
