### PR TITLE
1439 android client server preference

### LINKED ISSUE #1439: Client and Server options are not persisted
## What went wrong? 😲
 
A tablet is set up - one of the client/server options is chosen.
The tablet seems to forget what was selected when you try to use it later.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Install on a tablet, select 'server' mode
2. Initialise
3. Close app; reopen and see if you get back to the previous server
4. Repeat if various combinations

## Your environment 🌱
 - Version 1.1.6 and below
 - Platform: tablet

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1439

# 👩🏻‍💻 What does this PR do? 
 
Removed localStorage and have used the android SharedPreference instead.
Tried to use Capacitor Preferences but could not get the plugin to work 🙄 

It can be a little jumpy on the initial loads.. but does now work reliably. The client/server switch in Settings is working correctly too. I've also added the local server to the list of servers even when running in server mode - this is because the server has to exist in the list in order to connect to it.

image

### Offroads
- Added the name of the server to the failed to connect error:
- The 'failed to connect' message is not shown if there was no previous server saved.
- Tweaked the layout of the screen to remove additional whitespace
- If the user is not logged in, then redirect to the login screen : otherwise the dashboard is shown, but as soon as you interact you are shown the logged out modal

# 🧪 How has/should this change been tested? 

Cleared data - ran in client mode, then checked that:

- [ ] you are taken to the server discovery screen & servers are available
- [ ] connecting to a remote server works
- [ ] after connecting to a remote server, turning off that server and restarting the android app shows the appropriate error
- [ ] reset again and connect to the local server, will take you to the initialisation screen
- [ ] Run various combinations of the above: closing the app, checking that you get back to what you expect, change client/server mode, clear data etc.

cleared data - ran in server mode

- [ ] taken to the initialisation screen ( this was taking you to the dashboard, though you aren't logged in )

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java [hunk 1]
```diff
@@ -327,26 +330,25 @@ private NsdServiceInfo createLocalServiceInfo() {
...
     }
 
     // Had issues resolving local server when wifi and mobile data is off
-    // getting onResolveFailed with errorCode = 0 (internal error) with no more information
+    // getting onResolveFailed with errorCode = 0 (internal error) with no more
+    // information
     // manually adding this server should work
     private void addLocalServerToDiscovery() {
-        if(isAdvertising && isDiscovering && discoveredServers != null) {
+        if (isDiscovering && discoveredServers != null) {
```
Comment (andreievg) [inline client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java]: So when we run as client we `do` want local server to be discovered ?

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts [hunk 2]
```diff
@@ -139,7 +93,7 @@ export const useNativeClient = ({
 
     let connectToPreviousTimer: NodeJS.Timer | undefined = undefined;
 
-    if (autoconnect) {
+    if (autoconnect && !!state.previousServer) {
```
Comment (andreievg) [inline client/packages/common/src/hooks/useNativeClient/useNativeClient.ts]: Great ! I also noticed this and had similar idea for fix, but that was when localStorage was `sync` method, not sure if this would always work now, since state.previousServer may not be set yet due to async nature of getting previousServer

File: client/package.json [hunk 3]
```diff
@@ -107,6 +107,7 @@
   },
   "dependencies": {
     "@bugsnag/js": "^7.16.2",
+    "@capacitor/core": "^4.7.1",
```
Comment (mark-prins) [inline client/package.json:110]: the core versions were inconsistent - I've moved to the root rather than common, since the plugin was using Capacitor, and have left it here. We've used Capacitor in `useNativeClient` and that's used in a number of packages so it makes sense to have it at the root.

File: client/packages/common/src/hooks/useNativeClient/useNativeClient.ts [hunk 4]
```diff
@@ -1,74 +1,32 @@
...
-  connectToServer: (server: FrontEndHost) => void;
-  // Will return currently connected client (to display in UI)
-  connectedServer: () => Promise<FrontEndHost | null>;
-  goBackToDiscovery: () => void;
-  advertiseService?: () => void;
-  startBarcodeScan: () => Promise<number[]>;
-  stopBarcodeScan: () => void;
-  readLog: () => Promise<{ log: string; error: string }>;
-}
+import {
```
Comment (mark-prins) [inline client/packages/common/src/hooks/useNativeClient/useNativeClient.ts:3]: the file was getting pretty long, so I broke it up. Hopefully it makes sense like this

File: client/packages/common/src/hooks/useNativeClient/helpers.ts [hunk 5]
```diff
@@ -0,0 +1,56 @@
+import { Capacitor, registerPlugin } from '@capacitor/core';
+import { FrontEndHost, NativeMode, NativeAPI } from './types';
+
+export const setPreference = async (
```
Comment (mark-prins) [inline client/packages/common/src/hooks/useNativeClient/helpers.ts:4]: the preference methods are new - the rest of this is just moved from `useNativeClient`

File: client/packages/electron/src/electron.ts [hunk 6]
```diff
@@ -135,6 +136,16 @@ const start = (): void => {
   ipcMain.handle(IPC_MESSAGES.CONNECTED_SERVER, async () => connectedServer);
   ipcMain.handle(IPC_MESSAGES.START_BARCODE_SCAN, () => barcodeScanner.start());
   ipcMain.on(IPC_MESSAGES.STOP_BARCODE_SCAN, () => barcodeScanner.stop());
+  // preference method stubs: not currently implemented for electron
+  ipcMain.on(IPC_MESSAGES.GET_PREFERENCE, (_event, preference: Preference) => ({
```
Comment (mark-prins) [inline client/packages/electron/src/electron.ts:140]: am thinking to implement with `electron-store` but thought to make a new issue for that

File: client/packages/host/src/Admin/Settings.tsx [hunk 7]
```diff
@@ -179,6 +181,10 @@ export const Settings: React.FC = () => {
       </>
     ) : null;
 
+  useEffect(() => {
```
Comment (mark-prins) [inline client/packages/host/src/Admin/Settings.tsx:184]: this should be in `useNativeClient` but having the internal state in there wasn't working. The hook wasn't refreshing the value in the component that was using it. Since there's only two places that its used (here and `Android.tsx`), I have moved it out to those.

File: client/packages/host/src/components/Android.tsx [hunk 8]
```diff
@@ -122,15 +135,16 @@ export const Android = () => {
...
+        connectToServer({ ...localServer, path });
       }
     }
   }, [mode, servers]);
 
   useEffect(() => {
     if (
       mode === NativeMode.Client &&
-      (!previousServer || connectToPreviousTimedOut)
+      (!previousServer?.ip || connectToPreviousTimedOut)
```
Comment (mark-prins) [inline client/packages/host/src/components/Android.tsx:147]: slightly clumsy - this is because there's no removePreference, and I'm setting the previousServer to an empty object when clearing it

File: client/packages/common/src/hooks/useNativeClient/helpers.ts
Comment (andreievg) [inline client/packages/common/src/hooks/useNativeClient/helpers.ts:1]: I like the file split, nicely structured (and useNativeClient was getting too big)

File: client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useDraftServiceLines.ts [hunk 9]
```diff
@@ -46,12 +46,13 @@ export const useDraftServiceLines = () => {
   const update = (patch: RecordPatch<DraftInboundLine>) => {
     setDraftLines(currLines => {
       const newLines = currLines.map(line => {
-        const taxAmount =
-          (patch.totalBeforeTax ?? 0) * ((patch.taxPercentage ?? 0) / 100);
-        const totalAfterTax = (patch.totalBeforeTax ?? 0) + taxAmount;
-        const newPatch = { ...patch, totalAfterTax };
-        if (line.id === patch.id)
-          return { ...line, ...newPatch, isUpdated: true };
+        if (line.id === patch.id) {
```
Comment (andreievg) [inline client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useDraftServiceLines.ts:49]: I can't see description of this change, what should it do, how to test it ?

File: package.json [hunk 10]
```diff
@@ -1,10 +1,10 @@
 {
   "name": "open-msupply",
   "//": "Main version for the app, should be in semantic version format (any release candidate or test build should be separated by '-' i.e. 1.1.1-rc1 or 1.1.1-test",
-  "version": "1.1.6",
+  "version": "1.1.7",
```
Comment (andreievg) [inline package.json:4]: do we do this in main or in develop ?

File: client/packages/host/src/Admin/Settings.tsx [hunk 11]
```diff
@@ -133,8 +134,9 @@ export const Settings: React.FC = () => {
     const mode =
       nativeMode === NativeMode.Server ? NativeMode.Client : NativeMode.Server;
 
-    localStorage.removeItem(PREVIOUS_SERVER_KEY);
-    setNativeMode(mode);
+    setPreference('previousServer', {} as FrontEndHost);
```
Comment (andreievg) [inline client/packages/host/src/Admin/Settings.tsx:137]: technically for async operations, something like below or in a new promise, etc.. not sure if it could be the case, but if setting preferences take longer then navigation would have an issue here

```
    (async () => {
      await setPreference('previousServer', {} as FrontEndHost);
      await setPreference('mode', mode);
      navigate(RouteBuilder.create(AppRoute.Android).build());
    })();
```

File: client/packages/android/README.MD
Comment (andreievg) [inline client/packages/android/README.MD:1]: I think it's worth adding something to this file: `if you have "gradle" errors, try File ->  Sync Project with cradle files, in android studio`

**Review by andreievg — CHANGES_REQUESTED** [review]
Preference plugin works for me, but we do need to remember to add plugins to ExtendedWebViewClient, as per: https://github.com/openmsupply/open-msupply/compare/1439-android-client-server-preference...1439-example

As per README, this is somewhat tricky

```
Apart from usual local/packaged plugin setup for Capacitor, make sure to add plugin name to `onPageStarted` method in `ExtendedWebViewClient.java` (you can see what plugin names are available by using Android Studio debug and inspecting `bridge.plugins`). See point 2. in Capacitor Modifications (below).
```
Add Prefrences plugin


Also I think ideally we would need to overwrite localStorage (probably as a separate issue), for things like language etc, and to be confident that localStorage works uniformly across different apps, this would require LocalStorage to be rewritten, I wasn't sure why we would useListeners there rather then just zustand (which would be simpler). We would need to load all of the values from preferences/localStorage at the start, and await for them to be loaded (since local storage would be loaded in async manner)

The only required change, is trying to use the @capacitor/preferences plugin

File: client/packages/host/src/Admin/Settings.tsx (hunk 7 above)
Comment (andreievg) [reply client/packages/host/src/Admin/Settings.tsx:184]: I think this would be the only real place that we would need to use `preferences` since url may not match discovery url, at this point I would just add url parameter to discovery page (that would trigger overwrite the localStorage)

File: client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java (hunk 1 above)
Comment (mark-prins) [reply client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java]: I have reverted that - I thought that it was required, but cannot see why now after re-reading the code. will run a few more tests, but my view is that we don't need local when running in client mode.

File: package.json (hunk 10 above)
Comment (mark-prins) [reply package.json:4]: true. usually only in develop if a migration is needed. will revert

File: client/packages/android/README.MD
Comment (mark-prins) [reply client/packages/android/README.MD:1]: ah yes, good idea. it was in the block that I removed as part of the deps ugprade.

File: client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useDraftServiceLines.ts (hunk 9 above)
Comment (mark-prins) [reply client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useDraftServiceLines.ts:49]: It came from [this suggestion](https://github.com/openmsupply/open-msupply/pull/1311#discussion_r1141466686), which wasn't taken up by the dev before merging. I still think that it's a good idea, and functionally equivalent. 

To test - check that the total value is updated in the inbound shipment service line edit modal, when you make a change to the tax or amount values. The PR has more details.. perhaps too many details!

File: client/packages/host/src/Admin/Settings.tsx (hunk 11 above)
Comment (mark-prins) [reply client/packages/host/src/Admin/Settings.tsx:137]: thanks - that's much better

**Comment by mark-prins** [comment]
> As per README

I should have read the docs! 😆 
Thanks - that was a good pickup, and well explained. I've changed to use the Preferences, removed the manual implementation and retested it all. agree, that's much better. Changes in bb2f3962a 🙏

**Review by andreievg — APPROVED** [review]
Looks great, thanks for changes @mark-prins. 

I was wondering, maybe we need to add to carry over:
* For current Timor sites, when they upgrade to the future, they might get init screen ?
* Other localStorage things to use preferences ?

**Comment by mark-prins** [comment]
> For current Timor sites, when they upgrade to the future, they might get init screen ?

yeah, I was unsure about adding a migration for them. They will get prompted to select 'server mode' again - though the data won't need to be synced. Nick thought it would be ok to have a one-off, click-the-button for them

> Other localStorage things to use preferences ?

I thought that for the other localStorage uses, it's probably ok to have them site-specific. It is unlikely that users will be changing the server, and the transient nature of the storage is probably ok for site customisations ( which columns to show, should the details panel / menu be opened ). The language might be annoying - but if set on the user account in central server then that's not an issue too.
