### PR TITLE
1362 disable the stock charges tax entry when the total stock charges are $0 

### LINKED ISSUE #1362: disable the stock charges tax entry when the total stock charges are $0
## What went wrong? 😲
disable the stock charges tax entry when the total stock charges are $0

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add lines with no price
2. Add service charge item

## Your environment 🌱
 - Version [1.1.4]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1362

# 👩🏻‍💻 What does this PR do? 
Disable service tax edit for inbound and outbound shipments if the total is 0

# 🧪 How has/should this change been tested? 
- Add empty service tax line - see that tax pen is still disabled.
- Add service line with total - see that tax pen has been enabled 

Do we want to do this with stock charges as well? Issue is only talking about service charge...

### CODE REVIEW

File: client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx [hunk 1]
```diff
@@ -40,6 +41,11 @@ export const PricingSectionComponent = () => {
     pricing?.serviceTotalAfterTax
   );
 
+  const disableServiceTax =
+    serviceLines
```
Comment (bijaySussol) [inline client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx:45]: I thought we are disabling the `stock charge > Tax pen icon` if there ain't any stock charges but here it seems to me we are disabling the Service charges > Tax pen icon.

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx [hunk 2]
```diff
@@ -41,6 +41,10 @@ const ServiceCharges = ({ pricing, isDisabled }: PricingGroupProps) => {
   );
 
   const { updateServiceLineTax } = useOutbound.document.updateTax();
+  const disableServiceTax =
```
Comment (bijaySussol) [inline client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx:44]: Same here

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx [hunk 3]
```diff
@@ -73,7 +77,7 @@ const ServiceCharges = ({ pricing, isDisabled }: PricingGroupProps) => {
         <PanelLabel>{`${t('heading.tax')} ${Formatter.tax(tax)}`}</PanelLabel>
         <PanelField>
           <TaxEdit
-            disabled={!serviceLines?.length || isDisabled}
+            disabled={disableServiceTax || isDisabled}
```
Comment (bijaySussol) [inline client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx:80]: Is not `disableServiceTax` would be the same if True but `isDisabled` is False?

**Review by bijaySussol — CHANGES_REQUESTED** [review]
requesting changes

File: client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx (hunk 1 above)
Comment (roxy-dao) [reply client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx:45]: I was confused since issue title said stock but issue itself said `2. Add service charge item`, will change (:

File: client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx (hunk 3 above)
Comment (roxy-dao) [reply client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx:80]: `isDisabled` is just checking if the invoice data exists... So will always be true if invoice is in DB... The pen will always be disabled if service total is 0, regardless if isDisabled is false since it's checking OR...
Is that what you mean?

**Review by bijaySussol — APPROVED** [review]
@roxy-dao : 

Looks good to me
although in need to resolve the conflicts
thanks
